### ISSUE TITLE
to_numpy_array() does not preserve node numbers

### ISSUE THREAD

**Issue by melicheradam** [networkx/networkx#6649] opened 2023-04-18 09:16 UTC
Function to_numpy_array() does not preserve node numbers, even when nodelist is provided

### Current Behavior

```python
print(whole.keys())
np_whole = nx.to_numpy_array(bipartite_graph, nodelist=whole.keys())
tmp = nx.from_numpy_array(np_whole)
tmp = nx.to_dict_of_lists(tmp, whole.keys())
print("List of dicts\n",whole)
print("Numpy array\n",np_whole)

```

Notice that the array should have 1 at index 0,2 and 2,0 (...and others)

```
dict_keys([0, 1, 3, 4, 2, 5, 6, 7, 8, 10, 11, 9, 12, 13])
List of dicts
 {0: [1, 2, 7], 1: [0, 3, 4], 3: [1], 4: [1], 2: [0, 5, 6], 5: [2], 6: [2], 7: [8, 9, 0], 8: [7, 10, 11], 10: [8], 11: [8], 9: [7, 12, 13], 12: [9], 13: [9]}
Numpy array
 [[0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
```
### Expected Behavior

```python
print(whole.keys())
np_whole = nx.to_numpy_array(bipartite_graph, nodelist=whole.keys())
tmp = nx.from_numpy_array(np_whole)
tmp = nx.to_dict_of_lists(tmp, whole.keys())
print("List of dicts\n",whole)
print("Numpy array\n",np_whole)
```

Notice the matrix should be the same as list of dicts

```
dict_keys([0, 1, 3, 4, 2, 5, 6, 7, 8, 10, 11, 9, 12, 13])
List of dicts
 {0: [1, 2, 7], 1: [0, 3, 4], 3: [1], 4: [1], 2: [0, 5, 6], 5: [2], 6: [2], 7: [8, 9, 0], 8: [7, 10, 11], 10: [8], 11: [8], 9: [7, 12, 13], 12: [9], 13: [9]}
Numpy array
 [[0. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0, 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 ...
```
### Steps to Reproduce

Create a graph from provided list of dicts and run the code in example

### Environment

MacOS 13.3.1 Apple M1 Max

Python version: 3.10.9
NetworkX version: 3.1

**Comment by dschult** [comment] 2023-04-18 12:36
I don't think the array should have a 1 at indexes 0,2 and 2,0.  The order of the nodes in your nodelist have index 0 and 2 pointing to node values 0 and 3. And there is no edge in the dict_of_lists between 0 and 3. But maybe I am missing something.

**Comment by melicheradam** [comment] 2023-04-18 12:52
I have node 0 connected to node 1,2 and 7

Now I have noticed what's wrong in here, when I use `nodelist=range(len(whole.keys()))` it works.

So It is just an inconsistency/misunderstanding in the usage, because when I use `nx.to_list_of_dicts(bipartite_graph)` it produces the output you see in Current Behavior List of dicts (node 0 -> 1,2,7) , and when I use `nx.to_numpy_array(bipartite_graph)` (even without nodelist) it produces the numpy array you can see in the Current Behavior output (node 0 -> 1, 4, 7) . I would expect two export functions to produce same results in different format, not different results.

**Comment by dschult** [comment] 2023-04-18 20:56
It is important to distinguish between a nodes label (it's number in this case) and its position in the matrix. The order of the nodes in the graph is not 0,1,2,3,4,5,6,7,8,9,10,11,12,13. It is: 0,1,3,4,2,5,6,7,8,10,11,9,12,13. 
When you export, the graph is represented correctly in any order you use. But you have to understand that e.g. the array will look very different if you change the order of the rows and columns. The number representing a node is not the row number for that node. And for the dict_of_list format, the value you see in the dict-of-lists **is** the number representing the node.

**Comment by rossbar** [comment] 2023-04-20 18:38
Thanks @dschult for the thorough explanation. I agree that the behavior is as intended and I think the answer sufficiently addresses the initial question, so I will close this. If there is something to follow up on @melicheradam please feel free to reopen.

There is likely an opportunity to improve the documentation surrounding how nodes in the dict-of-dict structure map to indices in an adjacency matrix representation. PRs welcome!

**Closed by rossbar** 2023-04-20 18:38 UTC
Labels: Question
