### ISSUE TITLE
deorator.py isgeneratorfunction circular import error

### ISSUE THREAD

**Issue by charlesdwright** [networkx/networkx#5806] opened 2022-06-22 14:19 UTC
### Current Behavior
When attemtpting to debug koala2 in Pycharm, process ends with circular import error pointing to networkx/decorators.py

### Expected Behavior
Shouldn't error out.

### Steps to Reproduce
See screenshot of console output when attempting to step through debug.

### Environment
Python version: 3.9.10
NetworkX version: 2.8.4

### Additional context
Pycharm 2021.1.3 (Community Edition)
Build #PC-211.7628.24 built on June 30, 2021

![Screen Shot 2022-06-22 at 10 03 16 AM](https://user-images.githubusercontent.com/71340308/175052431-7643e883-d83b-4a05-ab13-bef93b3f9a28.png)

**Comment by dschult** [comment] 2022-06-22 14:49
The thread of imports makes it look like Python's `inspect` library is importing `ast`. But your naming conventions for the koala project have a module named `ast`.  So, inspect is importing the koala_project `ast` instead of the intended Python library `ast`.

In the end the `inspect` module is not fully loading because your `ast` module imports networkx which dependson `inspect`. Perhaps you could rename your koala_project module `ast` so it doesn't conflict with Python's `ast` module.

**Comment by rossbar** [comment] 2022-06-27 07:58
Thanks @dschult I will close this since the root cause here is the accidental shadowing of the built-in `inspect.ast` package.

**Closed** 2022-06-27 07:58 UTC
