### ISSUE TITLE
How to build relation from subgraph to nodes 

### ISSUE THREAD

**Issue by HankerSia** [networkx/networkx#4328] opened 2020-11-09 00:56 UTC
![subgraphNodes](https://user-images.githubusercontent.com/32951817/98489474-14c07600-2269-11eb-9e7d-294d88548ee8.png)
My target is as shown in above figure, I can build subgraph, but how to build edge from subgraph to nodes. Or if this graph can be achieved by networkx, Thank you very much!

**Comment by dschult** [comment] 2020-11-09 01:41
By design, nodes can be anything, so you can make a subgraph be a node and create edges to that subgraph. That will not easily construct the picture you show. But it can store the information in that picture.

```python
G = nx.Graph([("A", "B1"), ("A", "B2"), ("E", "B1"), ("E", "B2")])
H = G.subgraph(["A", "B1", "B2"])
G.add_edge("D", H)
nx.set_node_attributes(G, {(n if not isinstance(H, nx.Graph) else "C") for n in G}, "node_label")
```

**Comment by HankerSia** [comment] 2020-11-09 02:29
@dschult Thank you very much! However, in this way, the subgraph can not be changed in follow-up process. Is there any other methods?

**Comment by HankerSia** [comment] 2020-11-09 07:20
@dschult I tested your code, 
![subGraph1](https://user-images.githubusercontent.com/32951817/98510912-e9587e00-229e-11eb-9567-ed64d6376ef2.png)

import networkx as nx
import matplotlib.pyplot as plt

G=nx.Graph([("A","B1"),("A","B2"),("B1","E"),("B2","E")])
H=G.subgraph(["A","B1","B2"])
G.add_edge("D",H)
    
nx.set_node_attributes(G, {(n if not isinstance(H, nx.Graph) else "C") for n in G}, "node_label")

plt.figure()
nx.draw(G, with_labels=True)
plt.show()

The node C did not get a node label.

**Comment by dschult** [comment] 2020-11-09 14:03
The subgraph is a view on the graph. But you can make a copy of it and then it is a read/write graph just like G is.
```python
H = G.subgraph(["a", "B1", "B2"]).copy()
```

As for labels, the default labels in the matplotlib drawing package just use `str(node)` to get the labels. In order to use the `node_labels` node attribute as the labels, you'll have to use the `nx.draw_networkx_labels` and maybe [other features of the drawing subpackage](https://networkx.org/documentation/stable/reference/drawing.html).

**Comment by HankerSia** [comment] 2020-11-19 09:48
@dschult  I am sorry to disturb you again.  I had tried the following example. It worked when i add a graph as a node. But how can i build edges from one of the nodes of G1 to a new nodes in G. For example,  it would like this "G.add_edge(G1["B1"], "E")    "
import networkx as nx
import matplotlib.pyplot as plt
G1=nx.Graph([("A","B1"),("A","B2")])

G=nx.Graph()
G.add_node(G1)

G.add_edge(G1, "D")

**Comment by dschult** [comment] 2020-11-19 11:10
I think you are missing the distinction between adding a graph as a node and adding all the nodes and edges of a graph.  `G.add_node(G1)` only adds one node to `G`. There are no "nodes of G1" in the graph `G`.  If you want them in G, you have to add them too: `G.update(G1)` -- but in G the nodes "A" and "B1" are still not known to be part of G1. That info is stored in G1, not G.  

You say you want `G.add_edge(G1["B1"], "E")`.  But `G1["B1"]` is an adjacency of the neighbors of "B1". I think you want `G.add_edge("B1", "E")`  Right?

**Comment by HankerSia** [comment] 2020-11-19 16:57
> I think you are missing the distinction between adding a graph as a node and adding all the nodes and edges of a graph. `G.add_node(G1)` only adds one node to `G`. There are no "nodes of G1" in the graph `G`. If you want them in G, you have to add them too: `G.update(G1)` -- but in G the nodes "A" and "B1" are still not known to be part of G1. That info is stored in G1, not G.
> 
> You say you want `G.add_edge(G1["B1"], "E")`. But `G1["B1"]` is an adjacency of the neighbors of "B1". I think you want `G.add_edge("B1", "E")` Right?

Yes, I want G.add_edge("B1", "E"), but the "B1" is a node of G1

**Comment by dschult** [comment] 2020-11-20 05:57
So, you have to decide what it means to add an edge from a node of G1 to a node of G.
A Graph is a set of nodes and a set of pairs of those nodes called edges. 

If you `G.add_edge("B1","E")`, then "B1" will be a node in both G and in G1. The edge between "B1" and "E" will be in G, but it will not be in G1. Indeed there will not be a node "E" in G1. 

If you draw G you will see G1 as a node in G. You will also see "B1" and "E" as nodes in G. The graph G will not know that "B1" is also in G1. G1 will know that "B1" is a node in G1, but it will not know that "B1" is also a node in G.

**Comment by HankerSia** [comment] 2020-11-20 07:54
> So, you have to decide what it means to add an edge from a node of G1 to a node of G.
> A Graph is a set of nodes and a set of pairs of those nodes called edges.
> 
> If you `G.add_edge("B1","E")`, then "B1" will be a node in both G and in G1. The edge between "B1" and "E" will be in G, but it will not be in G1. Indeed there will not be a node "E" in G1.
> 
> If you draw G you will see G1 as a node in G. You will also see "B1" and "E" as nodes in G. The graph G will not know that "B1" is also in G1. G1 will know that "B1" is a node in G1, but it will not know that "B1" is also a node in G.

I just want to build an edge from a node of one graph ("B1" of G1) to a node of another graph ("E" of G).

**Comment by HankerSia** [comment] 2020-11-20 08:02
@dschult 
It seems that i need a solution of building edge from one graph to another graph.  For i need to change all graph dynamically, so subgraph can not be selected. 
For example, it would like this "G.add_edge(G1["B1"], "E") "

**Comment by dschult** [comment] 2020-11-20 14:55
Think about what you are saying/wanting a little more.  Every edge must live in a graph. That means the two nodes must be in that graph.  

Your syntax `G.add_edge(G1["B1"], "E")` doesn't make sense because G1["B1"] is an adjacency dictionary with keys that are the neighbors of "B1" in the graph G1.  The node you want is "B1", not G1["B1"].

Said another way, I think you are viewing the nodes as being attached to a graph. The nodes exist as python objects independent of a graph. So "B1" is a python object that can be in both G and in G1 (or not...).
Edges are **NOT** python objects independent of the graph.  The edge only exists within a graph and it represents a relationship between nodes in *that* graph.

I think what you want is to add all the nodes from G1 to G. Then you cn connect them as in your picture. The object G1 can also be a node in G. But G will not make use of any relationship between G1 (what the drawing calls Node C) and the nodes.  

What are you actually trying to do in the long run/big picture?

**Comment by HankerSia** [comment] 2020-11-20 16:28
> picture

I just want build an edge from a node of one graph to a node of another graph. It seems that networkx do not support this type operation. Right?
But I do not think it is a quite strange operation, for node "B1" is a node of "G1", and "G1" is a node of "G". "E" is a node of "G". Why edge between "B1" of "G1" to "E" is not allowed.

**Comment by dschult** [comment] 2020-11-22 01:48
`G.add_edge("B1", "E")` does what you want.

**Comment by HankerSia** [comment] 2020-11-22 08:38
> `G.add_edge("B1", "E")` does what you want.

I am sorry it did not ...
In this way "B1" would be a node of "G", while we need it should be "B1" of "G1"

**Comment by jarrodmillman** [comment] 2020-11-26 19:54
It looks like what you are talking about it is not a graph.  And I am not sure which graph algorithms (if any) would make sense on such a structure.

I did some google searching for you and it looks like what you are interested in may be called a higraph (https://en.wikipedia.org/wiki/Higraph) or a statechart (https://www.inf.ed.ac.uk/teaching/courses/seoc/2005_2006/resources/statecharts.pdf).  I did more google searching and there does appear to be some Python packages for statecharts.

Here is a paper about algorithms for higraphs (e.g., they extend some graph algorithms to higraphs):
- http://www.wisdom.weizmann.ac.il/~harel/SCANNED.PAPERS/Algorithmics%20of%20Higraphs.pdf

I also found this paper:
- https://hal.archives-ouvertes.fr/hal-01366350/document

I didn't read the paper, but from a quick visual scan it appears that they used NetworkX MultiDiGraphs to implement higraphs.  They provide some pseudocode that you may find useful if you need to implement this functionality.

I am not familiar with higraphs or statecharts and I haven't read the above paper.  From my google searching, I believe that statecharts are mostly used for diagramming things and don't have many algorithmic applications yet.  I also couldn't find many articles presenting algorithms for higraphs.  If you find additional algorithms for higraphs in the literature, please link to them here.

**Comment by HankerSia** [comment] 2020-11-28 12:53
> It looks like what you are talking about it is not a graph. And I am not sure which graph algorithms (if any) would make sense on such a structure.
> 
> I did some google searching for you and it looks like what you are interested in may be called a higraph (https://en.wikipedia.org/wiki/Higraph) or a statechart (https://www.inf.ed.ac.uk/teaching/courses/seoc/2005_2006/resources/statecharts.pdf). I did more google searching and there does appear to be some Python packages for statecharts.
> 
> Here is a paper about algorithms for higraphs (e.g., they extend some graph algorithms to higraphs):
> 
> * http://www.wisdom.weizmann.ac.il/~harel/SCANNED.PAPERS/Algorithmics%20of%20Higraphs.pdf
> 
> I also found this paper:
> 
> * https://hal.archives-ouvertes.fr/hal-01366350/document
> 
> I didn't read the paper, but from a quick visual scan it appears that they used NetworkX MultiDiGraphs to implement higraphs. They provide some pseudocode that you may find useful if you need to implement this functionality.
> 
> I am not familiar with higraphs or statecharts and I haven't read the above paper. From my google searching, I believe that statecharts are mostly used for diagramming things and don't have many algorithmic applications yet. I also couldn't find many articles presenting algorithms for higraphs. If you find additional algorithms for higraphs in the literature, please link to them here.
Thank you very much! I will find a solution! The detail will be linked here.

**Comment by rossbar** [comment] 2021-09-03 03:58
I'm going to close this as it's been a while. Feel free to update/reopen as needed.

**Closed by rossbar** 2021-09-03 03:58 UTC
Labels: Question
