### ISSUE TITLE
Defects of Bridges Algorithms

### ISSUE THREAD

**Issue by dtekinoglu** [networkx/networkx#5486] opened 2022-04-06 10:48 UTC
Algorithms in the [Bridges](https://networkx.org/documentation/stable/reference/algorithms/bridges.html) section only applicable for undirected graphs. However, this is not stated in the documentation. They `Raise` `NetworkXNotImplemented` when the input is a directed graph. However, I am a bit confused about the following point:

Output of `nx.bridges(G)` is `<generator object bridges at 0x7f70733bb050>` . So, it seems that it works for directed graphs as well. 
However, `list(nx.bridges(G))` raises `NetworkXNotImplemented`.

Is this expected? Should not `nx.bridges(G)` directly raise `NetworkXNotImplemented` instead?

With your guidance I am willing to work on this issue.
@rossbar @MridulS @dschult

**Comment by rossbar** [comment] 2022-04-09 06:26
> However, I am a bit confused about the following point:
> Output of nx.bridges(G) is <generator object bridges at 0x7f70733bb050> . So, it seems that it works for directed graphs as well.
> However, list(nx.bridges(G)) raises NetworkXNotImplemented.
> Is this expected? Should not nx.bridges(G) directly raise NetworkXNotImplemented instead?

Hmm interesting - I would've expected this to raise directly but it looks like there might be a slight behavior change here as a result of `argmap`, maybe due to `_lazy_compile`? FWIW this is a regression from NX 2.5 where the `NetworkXNotImplementedError` is raised when `nx.bridges` is called:

```python
>>> import networkx as nx
>>> nx.__version__
'2.5.1'
>>> G = nx.path_graph(3, create_using=nx.DiGraph)
>>> nx.bridges(G)
Traceback (most recent call last)
   ...
NetworkXNotImplemented: not implemented for directed type
```
@boothby what do you think about the `_lazy_compile` hypothesis? Is there an easy way to toggle raising exceptions eagerly e.g. in the `@not_implemented_for` case?

@dtekinoglu to answer your question - yes it'd be great to improve the documentation for the bridges module, though I think you've stumbled on a deeper issue here - thanks for bringing it up!

**Comment by dtekinoglu** [comment] 2022-04-10 23:18
I realized a few more problems regarding bridge algorithms. 

- Firstly, all three methods raise `NetworkXNotImplemented` if `G` is directed or multigraph. However, `@not_implemented_for("multigraph")` is statement only written for `local_bridges()` method. Considering the parts of source code that are related to multigraphs, I believe the intention was making these algorithms to work for multigraphs as well. Therefore, `NetworkXNotImplemented` is an unexpected behavior. If not, then `@not_implemented_for("multigraph")` should have been added to the source code.
- Secondly, in the documentation, it is stated that `bridges(G,root)` and `has_bridges(G,root)` raise `NodeNotFound` if `root` is not in `G`. However, this is not the current behavior. Consider the following example's output:

`G=nx.Graph([(0,1),(2,3),(1,3),(1,0)])`
`nx.bridges(G,root=5)`
Output: <generator object bridges at 0x7f3df18a9f50>

Above example might be result of `_lazy_compile` as you told. However, here is another unexpected behavior:

`G=nx.Graph([(0,1),(2,3),(1,3),(1,0)])`
`nx.has_bridges(G,5)`
Output: `True`

To my understanding, there are several defects regarding all three bridge algorithms. I fixed the documentation partly and opened a PR. However, for source code modification, I wanted to ask your opinion on what the expected behaviors of these algorithms actually are.

@rossbar @MridulS @dschult

**Comment by dschult** [comment] 2022-04-11 14:27
I think these results might be due to the recent changes to bridges.py #5397 
If you update your version of NetworkX to v2.8 does that get rid of these issues?

**Comment by dtekinoglu** [comment] 2022-04-11 15:10
Thank you @dschult , I got rid of the issue with multigraphs. However, `NodeNotFound` is still not working.

**Comment by rossbar** [comment] 2022-04-11 17:18
> I think these results might be due to the recent changes to bridges.py https://github.com/networkx/networkx/pull/5397

Ah of course, thanks @dschult 

I'm going to open a new, separate issue for the delayed-exception issue [mentioned above](https://github.com/networkx/networkx/issues/5486#issuecomment-1093738471).

**Comment by dschult** [comment] 2022-04-12 01:46
Yes -- the `NodeNotFound` does not work for `has_bridges`, as you demonstrate. :}
In fact, `has_bridges` does not even use the `root` argument at all!!

I think it needs to be put into the `nx.bridges(G, root)` call -- it must have been left out.
That means we should also create a test for `has_bridges` being called with a non-node.

Thanks very much @dtekinoglu ...  You are uncovering interesting traits of the codebase.

**Comment by rossbar** [comment] 2022-05-13 15:57
Most of the issues have been resolved, so I'm going to close this one so that no one's tempted to work on things that are already fixed :)

I opened a new issue for the remaining `root` problem. If I've missed anything here, please feel free to open a new issue or amend #5636 !

**Closed by rossbar** 2022-05-13 15:57 UTC
Labels: Defect
