### ISSUE TITLE
nx.adjacency_matrix returns the incorrect adjacency matrix

### ISSUE THREAD

**Issue by MooohMCPE** [networkx/networkx#7516] opened 2024-06-24 21:01 UTC
I believe there could be a bug with the built-in adjacency matrix function in Networkx

![image](https://github.com/networkx/networkx/assets/125153936/e2806e17-c317-4b01-a90e-95d0eea4da46)
The first matrix in the output terminal is one that I personally inputted. It was used to derive a minimum spanning tree M through Kruskal's algorithm.

The second matrix is the minimum spanning tree's adjacency matrix derived from the built-in method.

I have also printed the list of the minimum spanning tree's edges to demonstrate that an issue might exist in the built-in function's output, as it returns edges that do not exist in the edge list.

**Comment by Peiffap** [comment] 2024-06-24 22:47
I'm unable to reproduce this error on 3.3 with Python 3.12.3.

```pycon
Python 3.12.3 (main, Apr  9 2024, 16:54:45) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import networkx as nx
>>> import numpy as np
>>> g_arr = np.array([[0, 1, 0, 1, 0, 0, 0, 0, 0],
...                 [1, 0, 1, 0, 1, 0, 0, 0, 0],
...                 [0, 1, 0, 0, 0, 1, 0, 0, 0],
...                 [1, 0, 0, 0, 1, 0, 1, 0, 0],
...                 [0, 1, 0, 1, 0, 1, 0, 1, 0],
...                 [0, 0, 1, 0, 1, 0, 0, 0, 1],
...                 [0, 0, 0, 1, 0, 0, 0, 1, 0],
...                 [0, 0, 0, 0, 1, 0, 1, 0, 1],
...                 [0, 0, 0, 0, 0, 1, 0, 1, 0]], dtype=float)
>>> G = nx.from_numpy_array(g_arr)
>>> M = nx.minimum_spanning_tree(G, algorithm='kruskal')
>>> m_arr = nx.adjacency_matrix(M)
>>> print(m_arr)
  (0, 1)	1.0
  (0, 3)	1.0
  (1, 0)	1.0
  (1, 2)	1.0
  (1, 4)	1.0
  (2, 1)	1.0
  (2, 5)	1.0
  (3, 0)	1.0
  (3, 6)	1.0
  (4, 1)	1.0
  (4, 7)	1.0
  (5, 2)	1.0
  (5, 8)	1.0
  (6, 3)	1.0
  (7, 4)	1.0
  (8, 5)	1.0
>>> print(M.edges())
[(0, 1), (0, 3), (1, 2), (1, 4), (2, 5), (3, 6), (4, 7), (5, 8)]
```

**Comment by dschult** [comment] 2024-06-26 13:59
This looks like there might be a confusion between 0-based indexing and 1-based indexing. Check your conversion, for example the first matrix indicates edges `(0, 1)` and `(0, 3)`, but the second matrix indicates edges `(0, 1)` and `(0, 4)`.

**Comment by rossbar** [comment] 2024-07-11 10:52
I think @dschult and @Peiffap are correct that the confusion results from the data rather than a bug in `adjacency_matrix`. Therefore I will close this; however, if you believe there is still an issue, please feel free to reopen with a minimal reproducing example which includes all of the necessary info to reproduce the buggy behavior.

**Closed by rossbar** 2024-07-11 10:52 UTC
Labels: Question
