### ISSUE TITLE
Exporting graph with empty node name to pygraphviz causes error

### ISSUE THREAD

**Issue by SeanDS** [networkx/networkx#4834] opened 2021-05-25 07:45 UTC
### Current Behavior
NetworkX allows nodes to have empty names, e.g.

```python
import networkx

g = networkx.DiGraph()
g.add_node("")
```

Such a graph can be plotted using NetworkX's own Matplotlib plotting tools. However, when exported to a dot file via `networkx.drawing.nx_agraph.to_agraph`, an error is raised by `pygraphviz`:

```python
networkx.drawing.nx_agraph.to_agraph(g)
```

```
Traceback (most recent call last):
  File "/path/to/script.py", line 4, in <module>
    A.add_node("")
  File "/path/to/python3.9/site-packages/pygraphviz/agraph.py", line 326, in add_node
    node = Node(self, nh=nh)
  File "/path/to/python3.9/site-packages/pygraphviz/agraph.py", line 1843, in __new__
    n = super().__new__(self, gv.agnameof(nh), graph.encoding)
TypeError: decoding to str: need a bytes-like object, NoneType found
```

I think graphviz itself does not allow empty nodes, though I might be wrong. If this is the case then `pygraphviz` appears to be doing what's expected (refusing to create an empty node).

### Expected Behavior
I suggest that NetworkX should issue a warning or exception to tell the user that graphs containing empty nodes cannot be exported to graphviz format.

### Steps to Reproduce
See above.

### Environment

Python version: 3.9
NetworkX version: 2.5

**Comment by rossbar** [comment] 2022-05-15 07:29
Thanks for the report - taking a closer look at this I think the problem is in pygraphviz itself, so should be fixed there. I'm going to close the issue here and open one in the pygraphviz repo.

**Closed by rossbar** 2022-05-15 07:29 UTC
