### ISSUE TITLE
networkx.org banner display issue

### ISSUE THREAD

**Issue by mjschwenne** [networkx/networkx#6414] opened 2023-02-07 19:00 UTC
The primary banner for the NetworkX website is not displaying correctly, making 'Python' appear like 'Pythor'.

### Current Behavior

When visiting the networkx website, the logo and banner appear like below. The windows on the left are Brave Browser and the ones on the right are Firefox windows. 

![nx-banner-issue](https://user-images.githubusercontent.com/19698215/217340172-12475930-3e5a-4c20-bfcd-ff89b6a60339.png)

### Expected Behavior

'Python' should display correct, as it does when I view the image locally in Inkscape.

![nx-banner-local](https://user-images.githubusercontent.com/19698215/217340192-f2ca4626-3e15-43c0-a67d-3862bd25a055.png)

### Steps to Reproduce

Visit [networkx.org](https://networkx.org).

### Environment

Python version: NA
NetworkX version: NA

### Additional context

In the browsers, the text in the images is selectable, so the browsers may be trying to and failing to parse some of the vector information in the underlying `svg` file.

**Comment by MridulS** [comment] 2023-02-08 08:58
Can you reproduce this in other browsers? Which version are you using?

I tried it with Firefox 09.0.1, Chrome 109.0.5414.119, Safari 16.3 on a MacOS but I can't reproduce this.

**Comment by MridulS** [comment] 2023-02-19 19:20
@mjschwenne let me know if this is still an issue with any other browser you are using. If not we can close this issue :)

**Comment by mjschwenne** [comment] 2023-02-19 20:31
Sorry that I missed your original comment, I just checked again and the issue is still present in Firefox 110.0 and Brave 110.1.48.164

**Comment by mjschwenne** [comment] 2023-02-19 20:34
Also, the issue is present for me in Google Chrome 110.0.5481.100

**Comment by MridulS** [comment] 2023-02-19 20:37
Which OS are you using and which distribution of it?

**Comment by mjschwenne** [comment] 2023-02-19 20:39
I'm on Arco Linux right now.

**Comment by MridulS** [comment] 2023-02-21 13:13
I tried looking into this (started going into the SVG rendering rabbithole for browser engines, a lot of things can go wrong apparently) but I don't think this is something specific to our SVG logo/website. I would vote for closing this issue, unless you can reproduce this on any other machine. What do you think?

**Comment by rossbar** [comment] 2023-02-21 16:40
I too suspect this may be machine/platform/OS-specific. I've checked on Arch+firefox & chromium and Ubuntu+firefox & chromium and haven't reproduced the clipping.

**Comment by mjschwenne** [comment] 2023-02-21 19:20
Yes, it would seem that it is likely a machine specific thing. We can close the issue for now and if it starts to become more widespread, investigate further then.

**Closed** 2023-02-21 19:20 UTC
Labels: Documentation
