### ISSUE TITLE
DOC: plain text vs. links in "See Also" sections of docstrings

### ISSUE THREAD

**Issue by argriffing** [networkx/networkx#1176] opened 2014-05-26 14:59 UTC
In the generated sphinx documentation, the functions mentioned in the "See Also" section of the [`is_semiconnected`](http://networkx.github.io/documentation/development/reference/generated/networkx.algorithms.components.semiconnected.is_semiconnected.html) docstring are plain text rather than links.  Although I have not made a detailed study, this seems to be the case for several but not all docstrings in networkx.  I don't know which conditions are required for sphinx to add the links, and I'm not sure what would be the preferred way to change the docs so that sphinx would provide links instead of plain text.

**Comment by hagberg** [comment] 2015-01-10 16:15
Does #1221 address this?

**Comment by Michael-E-Rose** [comment] 2016-03-02 22:24
Since networkx has Napoleon enabled in [`doc/source/conf.py`](https://github.com/networkx/networkx/blob/master/doc/source/conf.py), I guess the answer to @hagberg's question is No: references to functions not in the same module stay plain text.

I believe, in this case adding the prefix `components.` to the see also-refs in [`semiconnected.py`](https://github.com/networkx/networkx/blob/master/networkx/algorithms/components/semiconnected.py) as prefix would fix the issue. At the same time, one should update [`strongly_connected.py`](https://github.com/networkx/networkx/blob/master/networkx/algorithms/components/strongly_connected.py) and [`weakly_connected.py`](https://github.com/networkx/networkx/blob/master/networkx/algorithms/components/weakly_connected.py)

On a more general level: The missing linking of methods outside the same module holds for quite some files and it takes a while to find them all. Isn't it possible to check for see also-links in nosetest or other pre-build tests?

**Comment by hagberg** [comment] 2016-04-16 18:45
Can we fix this or should we close this for now?

**Comment by Michael-E-Rose** [comment] 2016-04-16 19:17
Not sure if my suggested edit (adding the prefix) will work. But I'm willing to try!

**Comment by Michael-E-Rose** [comment] 2016-04-16 20:36
PR is live. Let's have a look to check whether the linking works. If so, there are many more docstrings to update.

**Comment by Michael-E-Rose** [comment] 2016-04-18 07:59
Apparently, the already merged PR #2082 didn't fix the problem. The first four entries in http://networkx.readthedocs.org/en/latest/reference/generated/networkx.algorithms.components.connected.is_connected.html#networkx.algorithms.components.connected.is_connected should be links.

I am confused: `numpy`'s [`HOWTO_DOCUMENT.rst`](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt#sections) clearly states: 

> Prefix functions from other sub-modules appropriately. E.g., whilst documenting the `random` module, refer to a function in `fft` by
   ` fft.fft2 : 2-D fast discrete Fourier transform`

So either my prefixing is wrong, or a setting differs from the one used by `numpy`, so something else. Let's reopen this issue and continue looking for an answer.

**Comment by dschult** [comment] 2016-04-18 22:53
You may need to prefix the see-also functions with the full path:
networkx.algorithms.components.connected.is_connected

**Comment by Michael-E-Rose** [comment] 2016-04-19 08:04
PR is live. Still unable to test whether it worked.

**Comment by Michael-E-Rose** [comment] 2016-04-19 12:41
I'm still unsure whether adding the full file path works.

Take a look at http://networkx.readthedocs.org/en/networkx-1.11/reference/generated/networkx.algorithms.centrality.betweenness_centrality.html: There is a link in "See also" to `load_centrality()`, although this method is in another file/module. Same goes for the link to `eigenvector_centrality()` on the page of [`katz_centrality()`](http://networkx.readthedocs.org/en/networkx-1.11/reference/generated/networkx.algorithms.centrality.katz_centrality.html). Then again, `pagerank()` does not get linked to, but this is in another folder.

What's different with the centralities?

**Comment by dschult** [comment] 2016-04-19 17:15
I notice that the centrality code has ```__init__.py``` use relative imports instead of full path. So, apparently sphinx could find the routines inside the centrality folder even if not inside the same module. But I can't reproduce that with the current version of sphinx used on ReadTheDocs, so maybe something has changed with the way sphinx looks for links.  I'll investigate further...

Why doesn't the sphinx documentation build for you? It should not work for Python3.4 (because make_gallery.py uses ```execfile``` -- also not worth fixing because examples are moving anyway).  But using Python2.7 with the PYTHONPATH variable pointing to your local git development copy of networkx should work.

**Comment by Michael-E-Rose** [comment] 2016-04-20 08:36
I got it. The trick was to remove `currentmodule` in `algorithms.component.rst` and list `automodule` only once.

PR #2095 updated.

**Closed** 2016-04-20 21:24 UTC
Labels: Documentation, Needs review
