### ISSUE TITLE
Crash in coreviews.py

### ISSUE THREAD

**Issue by staillefer** [networkx/networkx#6134] opened 2022-10-25 17:53 UTC
Hi,

I have a crash inside coreviews.py :

  m2 = ox.plot_route_folium(G, listeNoeuds, route_map = mapGraphe, weight = 3)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/osmnx/folium.py", line 96, in plot_route_folium
    gdf_edges = utils_graph.graph_to_gdfs(G.subgraph(route), nodes=False).loc[uvk]
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/indexing.py", line 1074, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/indexing.py", line 1280, in _getitem_axis
    key = list(key)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/osmnx/folium.py", line 95, in <genexpr>
    uvk = ((u, v, min(G[u][v].items(), key=lambda k: k[1]["length"])[0]) for u, v in node_pairs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/networkx/classes/coreviews.py", line 82, in __getitem__
    return AtlasView(self._atlas[name])
KeyError: 583097016

Node 583097016 exists in graph G
Is it a data problem ? A bug inside networkx ?

Thank you very much for your help.

**Comment by MridulS** [comment] 2022-10-25 18:12
Could you give some details how you ended up getting this output?
I see you are using osmnx, can you provide the code block that generated this output?

From the output it does look like node `583097016` is not in the Graph `G`

**Comment by staillefer** [comment] 2022-10-25 18:45
print( G.nodes[583097016])
{'y': 45.593018, 'x': -73.6822982, 'street_count': 3}

It  proves that the node exists in G.

    On Tuesday, October 25, 2022 at 02:12:43 p.m. GMT-4, Mridul Seth ***@***.***> wrote:  
 
 


Could you give some details how you ended up getting this output?
I see you are using osmnx, can you provide the code block that generated this output?

From the output it does look like node 583097016 is not in the Graph G

**Comment by rossbar** [comment] 2022-10-25 19:30
@staillefer the existence of the node in `G` is not particularly helpful in chasing down the problem. Generally, when reporting an issue it is useful to provide a minimum reproducing example along with the traceback, as one would need the full context in order to be able to determine the root cause of a problem.

For example - the node may be in `G`, but from the traceback above I see calls that are operating on a subset of the graph, e.g. `gdf_edges = utils_graph.graph_to_gdfs(G.subgraph(route), nodes=False).loc[uvk]`. Is the node in question in `G.subgraph(route)`? We can't determine this without a full reproducing example.

**Comment by staillefer** [comment] 2022-10-25 20:57
My code:

import osmnx as ox

OSM_DUVERNAY              = "Duvernay, Laval, Quebec, Canada"
OSM_SAINT_FRANCOIS        = "Saint-Francois, Laval, Quebec, Canada"
OSM_SAINT_VINCENT_DE_PAUL = "Saint-Vincent-de-Paul, Laval, Quebec, Canada"
OSM_AUTEUIL               = "Auteuil, Laval, Quebec, Canada"

districts = [OSM_DUVERNAY, OSM_SAINT_FRANCOIS, OSM_SAINT_VINCENT_DE_PAUL, OSM_AUTEUIL]

listNodes =  (583096989, 8931497693, 8931497690, 583097010, 583097011, 583097017, 583097016)

G = ox.graph_from_place(districts, network_type = "drive", simplify = False)
print(G.nodes[583097016])

subG = G.subgraph(listNodes)
print(subG.nodes[583097016])

m2 = ox.plot_route_folium(G, listNodes, weight = 3)

**Comment by rossbar** [comment] 2022-10-25 23:12
Thanks @staillefer this is helpful. The problem is that the `listNodes` doesn't seem to define a valid "route" in your graph, i.e. there is no edge between the final two nodes `583097017` and `583097016`.

I will close this as there isn't an underlying problem with NetworkX. You may want to consider opening an issue in `osmnx`, perhaps to propose a more informative exception message when the `route` is not a valid path.

**Closed by rossbar** 2022-10-25 23:12 UTC
Labels: Question

**Comment by staillefer** [comment] 2022-10-26 00:07
Thank you very much for your time !
