### ISSUE TITLE
contracted_nodes - KeyError when nodes are objects

### ISSUE THREAD

**Issue by n-samar** [networkx/networkx#2645] opened 2017-08-31 00:55 UTC
# Code that produces the bug
```python
class Stuff:
    def __init__(self, a, b):
        self.a = a
        self.b = b
```
Create a graph with nodes as instances of the above class:
```python
>>> g = netx.Graph()
>>> s1 = Stuff(1, 2)
>>> s2 = Stuff(1, 5)
>>> g.add_edge(s1, s2)
>>> netx.contracted_nodes(s1, s2)
KeyError: <__main__.stuff object at 0x036E5F50>
```
# The problem
The line of code that causes the issue is line 345 in _minors.py_:
```python
H = G.copy()
```
and later on when node _v_ is used as a key to _H_ in line 359:
```python
v_data = H.nodes[v]
```
Since _copy()_ will create new object instances for its nodes, _H.nodes_ will not contain the key _v_.

**Comment by dschult** [comment] 2017-08-31 02:07
hmm... I need some more information.
I can't reproduce the error with either python3.6 or 2.7 (with the master github branch of nx).

The G.copy() doesn't actually create new node instances. It just copies the pointer to each node, so H.nodes and G.nodes show the same memory locations in my tests. 

Also it seems that your code didn't include the graph in your call to ```contracted_nodes```. Is that a typo though? Because that should create a TypeError, not a KeyError...

What versions are you using?

**Comment by dschult** [comment] 2017-09-08 15:59
I'm going to close this issue -- if you can provide more information, reopen it.

**Closed by dschult** 2017-09-08 15:59 UTC
