### ISSUE TITLE
Strange behaviour with setting edge_attributes in nx.from_pandas_edgelist

### ISSUE THREAD

**Issue by amjass12** [networkx/networkx#4630] opened 2021-02-21 15:59 UTC
Hi!

I am encountering strange behaviour in assigning weights when creating an undirected graph using `nx.from_pandas_edgelist` - I am not sure if this is a bug, but would appreciate some clarification on this!

I have a pandas edgelist which looks as follows:

```
source | target | value
-- | -- | --
node1 | node2 | 0.855247
node1 | node3 | 0.883058
node1 | node4 | 0.878212
etc
```
now when i do:` graph = nx.from_pandas_edgelist(df, edge_attr=True).to_undirected()`, this works fine and i can also called communities using the community-louvain tool - `community.best_partition(graph)`

however: if i rename the value column in the edgelist to weights as follows:

```
source | target | weights
-- | -- | --
node1 | node2 | 0.855247
node1 | node3 | 0.883058
node1 | node4 | 0.878212
etc
```
and then do: `graph = nx.from_pandas_edgelist(df, edge_attr='weights').to_undirected()`
The function works, but there is something funny about the weight assignment as I get an error in community detection:

`community.best_partition(graph)` - ValueError: Bad node degree (-0.7013372005704317)

My specific question isn't about the community tool - but why renaming the value column to weights and the specifying this column in the graph function messes the weight assignment and then other things downstream. 

thank you!

**Comment by dschult** [comment] 2021-02-21 20:00
It's hard to tell without a short simple reproducible example. I can say that reading in the pandas dataframe gives the same resulting graph only with edge attribute "weights" instead of "value".  I suspect the problem is in how you call the community function. If you don't specify an edge attribute to use, it may default to having every edge have weight 1.

Here what I mean by a short simple example to show the problem or solution:
```python
import pandas as pd
import networkx as nx
df=pd.DataFrame({'source': [1, 1, 1], 'target': [2, 3, 4], 'weights': [.85, .88, .87]})
print(df)
G=nx.from_pandas_edgelist(df, edge_attr="weights")
print(G.edges.data())
df=pd.DataFrame({'source': [1, 1, 1], 'target': [2, 3, 4], 'value': [.85, .88, .87]})
print(df)
H=nx.from_pandas_edgelist(df, edge_attr=True)
print(H.edges.data())
```
 Output
```
   source  target  weights
0       1       2     0.85
1       1       3     0.88
2       1       4     0.87
[(1, 2, {'weights': 0.85}), (1, 3, {'weights': 0.88}), (1, 4, {'weights': 0.87})]
   source  target  value
0       1       2   0.85
1       1       3   0.88
2       1       4   0.87
[(1, 2, {'value': 0.85}), (1, 3, {'value': 0.88}), (1, 4, {'value': 0.87})]
```
Can you show your commands to `best_partition` in a similar small example and print what is happening?

**Comment by amjass12** [comment] 2021-02-21 21:52
Hi @dschult , 
thank you for your detailed reply - So i can confirm also the resulting graph is the same for me in the more extensive pandas dataframe (apologies i did not supply a more extensive reproducible one): 

Now in attempting to reproduce this error I cannot: I do really apologise, it has confused me somewhat. So now, if i name the column 'weights' instead of values, and use `edge_attr=True` or `edge_attr='weights'` calling community with default parameters:

`community_weights = community.best_partition(graph_weights)` actually now works.. with the same communities as when the column is called value and the same function with default parameters is called -

I get a partition of about 70 communities based on a graph with ~4k nodes

I am scratching my head, but I guess I will end with a question for clarity if it repeats later on, and I think this question is more about curiosity of the guts of how `nx.from_pandas_edgelist` is working internally:

I have not looked at the source code, but is there a default way by which the weight column is set to 'value' which may make this work downstream in functions such as community causing `best_partition` to know which column or attribute to look for when searching for weights? I guess this wouldn't explain now why it works when the value column name is changed to weights...

I would say that when specifying weight in best_partition as either 'value' or 'weights' depending on which is used to make the graph, I get the Bad node degree (-0.7013372005704317) error. If i do not specify the weight argument, the function works without issue... 

`community.best_partition(graph, weight='weights/values')`

**Comment by dschult** [comment] 2021-02-22 01:59
If you don't specify a weight in `best_partition` the edge weights are all considered to be `1.0`.
That is the difference between the case when you get the error (using edge weights which look negative!?) and the case when you don't (edge weights are considered to be 1).

**Comment by amjass12** [comment] 2021-02-22 07:13
Ok thank you, this makes sense. I am guessing though that the weights are not required to find communities? as communities are detected, and are also detected according to the structure of the graph... This seems like the correct behaviour to me.. 

I have asked on the community-louvain forum for clarification as the documentation is not completely clear to me...

**Comment by rossbar** [comment] 2021-05-18 16:32
I'm going to go ahead and close this as the discussion seems to have died down. If the issue persists or more clarification is required, please feel free to reopen with updated info on the current problem statement.

**Closed by rossbar** 2021-05-18 16:32 UTC
Labels: Question
