### ISSUE TITLE
Problem reading GML File

### ISSUE THREAD

**Issue by hernandcb** [networkx/networkx#1783] opened 2015-10-01 19:32 UTC
I have downloaded the gml file which contains the dolphins social network from http://www-personal.umich.edu/~mejn/netdata/dolphins.zip.

Some time ago I did some analysis on that network running python 3.4 and networkx 1.9 on a Windows7 machine, but now I am running on a Arch linux machine (with the same version of python but with networkx 1.10) and found an issue when tried to read the file.

This is the code used to read the file:

```python
import networkx as nx
nx.read_gml("dolphins.gml")
```
And this is the stack trace of the error:

```python
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "<string>", line 2, in read_gml
File "/usr/lib/python3.4/site-packages/networkx/utils/decorators.py",line 220, in _open_file
result = func(*new_args, **kwargs)
File "/usr/lib/python3.4/site-packages/networkx/readwrite/gml.py", line 210, in read_gml
G = parse_gml_lines(filter_lines(path), label, destringizer)
File "/usr/lib/python3.4/site-packages/networkx/readwrite/gml.py", line 383, in parse_gml_lines
graph = parse_graph()
File "/usr/lib/python3.4/site-packages/networkx/readwrite/gml.py", line 372, in parse_graph
curr_token, dct = parse_kv(next(tokens))
File "/usr/lib/python3.4/site-packages/networkx/readwrite/gml.py", line 323, in tokenize
(line[pos:], lineno + 1, pos + 1))
networkx.exception.NetworkXError: cannot tokenize 'graph' at (1, 1)
```

Do you know what can be generating this error?

**Comment by hernandcb** [comment] 2015-10-01 21:46
I tried with version 1.9.1 and It worked fine.. 
A newbie question: How can I install the latest version of the library to check if it works?

**Comment by joelmiller** [comment] 2015-10-02 11:42
A similar error  is also reported [here](http://stackoverflow.com/questions/31946029/networkx-read-gml-error-networkx-exception-networkxerror-cannot-tokenize-ugra)

**Comment by SanketDG** [comment] 2015-10-02 12:36
@hernandcb Do:
```shell
pip install git+https://github.com/networkx/networkx.git
```

This will install the `master` (latest) branch as a python package.

**Comment by nadesai** [comment] 2015-12-14 22:17
Don't know if this has been fixed yet (after installing the latest master per @SanketDG, the issue still manifests). The offending GML file looks like this:
```
graph
  [
  directed 0
  node
  [
    id 0
    label "Beak"
  ]
...
  edge
  [
    source 8
    target 3
  ]
...
```
networkx parses the file properly if I remove the newlines after `graph`, `node`, and `edge`, so that it looks like this:
```

**Comment by hagberg** [comment] 2015-12-26 17:48
I think the newline is valid whitespace.  If that is true then the parser needs to be adjusted to allow whitespace including newline after a key.

**Comment by wuhaochen** [comment] 2016-01-28 23:43
@hagberg I just read the code, it seems the problem is in the filter_lines function in gml.py (L206-207), the '\n' in the end of a line is explicitly deleted there. Is it necessary? The lines before(L204-205) are also suspicious, L205 probably should be line = str(line).

**Comment by Michael-E-Rose** [comment] 2016-04-21 09:20
I think this issue can be closed, as the corresponding PR has been merged. Question is: Is this related to issue #1985?

**Comment by hagberg** [comment] 2016-04-21 13:39
#1985 is a separate issue.

**Closed by hagberg** 2016-04-21 13:39 UTC
Labels: Defect
