### ISSUE TITLE
dag_longest_path(G) doesn't work with graphs of unorderable types

### ISSUE THREAD

**Issue by djcomlab** [networkx/networkx#1989] opened 2016-02-10 17:15 UTC
Hiya,

I'm building my graphs with my own types as nodes e.g. in a DiGraph

```
p1 = Process()
p2 = Process()
p3 = Process()
G.add_edge(p1, p2)
G.add_edge(p1, p3)
G.add_edge(p2, p3)
```

however if I run the longest_path function on it, it pops up with

```
line 425, in dag_longest_path
    node, (length, _) = max(dist.items(), key=lambda x: x[1])
TypeError: unorderable types: Process() > Process()
```

I would have guessed the algorithm should be working out the path lengths rather than trying to determine an order on my nodes (I don't really know graph algos, so I could be terrible wrong here).

Any ideas how to workaround this?

**Comment by dschult** [comment] 2016-02-10 20:29
It looks like a bug.
You can change line 425 to ```node, (length, _) = max(dist.items(), key=lambda x: x[1][0])```   (I just added ```[0]```near the end).  

the problem is that dist is a dict with node keys and values with form (length, node).  We tell ```max``` to look at the value to sort. That will usually work because (1, process)>(2,process).  But if they have the same length tuple compares go to the second argument of the tuple and that's not orderable.

The fix is to make the ```key``` argument for the ```max``` function strip off the node and just use the length.

If making that change works for you, the latest code has the same problem on line 448.  You could submit a pull request to fix it. Or, I will do so if that's too much to learn how to do.

Sorry for the bug--thanks for the report.

**Comment by jfinkels** [comment] 2016-02-20 05:50
This seems to be fixed in a newer version of NetworkX, in commit 1dc16026a654e6bca3f8d182a18e213b7fb31871. I'm creating a pull request now that adds a unit test for unorderable nodes.

**Closed** 2016-02-20 15:13 UTC
