### ISSUE TITLE
list attributes are not copied on a union 

### ISSUE THREAD

**Issue by BinduAtBaya** [networkx/networkx#6661] opened 2023-04-21 21:08 UTC
create graph1
create graph2
update graph1 as union of graph1 and graph2 with rename
update graph1 as union of graph 1 and graph2 with new rename
list attributes of graph2 are not copied but referenced  

### Steps to Reproduce
import networkx as nx
G=nx.DiGraph()
G.add_node("foo", unconn=["a","b","c"])
H=nx.DiGraph()
H.add_node("bar", unconn=["a","b","c"])
H=nx.union(H,G,rename=('',"l1"))
print(H.nodes(data=True))
H=nx.union(H,G,rename=('',"l2"))
print(H.nodes(data=True))
H.nodes['l2foo']['unconn'].remove('a')

this will remove a from both nodes l2foo and l1foo

### Environment

Python version:
NetworkX version:

**Comment by MridulS** [comment] 2023-04-23 16:20
Thanks for raising the issue, and this will indeed be an issue as the underlying attributes are shallow copies rather than deep copies (which is an expensive operation). This is also the reason networkx usually recommends not touching the graph data structure dictionaries directly with operations like `remove`/`add`. One quick way of fixing this is to use `nx.set_node_attributes` to explicitly state the node attributes. So in the given example if you change the last line from
``` python
H.nodes['l2foo']['unconn'].remove('a')
```
to
``` python
nx.set_node_attributes(H, {'l2foo': {'unconn': ['b', 'c']}})
```
it should work as intended.

I'm not too sure if we should be exposing these things via the API or not (like making deepcopy an argument through `union` and other operators). Maybe we should be doing a better job to document usage of  `set_node_attributes`/`set_edge_attributes` more prominently?

**Comment by rossbar** [comment] 2023-04-23 17:54
For functions that *do* copy attributes, maybe we could consider switching to `deepcopy` as the default? I doubt many users want/expect the attributes in the union graph to be references back to the same mutable object from the input graph(s).

**Comment by dschult** [comment] 2023-04-25 17:43
At the very least we should explain what we do and give examples in the doc_strings for how to do other things.
Perhaps out "operators" should not copy node or edge attributes at all, and just have the doc_strings give the code to move attributes for people who want the attributes moved.  Another extreme version could provide a keyword argument that lets the user choose between no-attributes, shallow-copy attributes, and deep-copy-attributes. 

To be clear, the current behavior is that attributes are shallow-copied. That is any containers are copied by copying the pointer to the container rather than copying that container.  

This saves memory and time compared to deepcopy where the containers and any containers they contain and so forth would be copied.  And this shallow-copy method works for most attributes.  Even the attributes which are containers work this way unless you expect to be able to access attributes on the original graph as separate things from the newly created graph's attributes.

**Comment by rossbar** [comment] 2023-05-19 06:28
From the discussion in #6667, it was noted that documenting this thoroughly would necessitate adding quite a lot of text to many docstrings. This may end up being a net-negative as a big chunk of the docstring would then be dedicated to a Python language feature (i.e. shallow copying by default) rather than to the functions themselves.

Perhaps we should close this one as not-actionable then? WDYT @MridulS ?

**Comment by MridulS** [comment] 2023-05-19 11:04
Yeah, this particular issue isn't actionable but we still probably need to have the shallow/deep copy discussion somewhere.

**Closed** 2023-11-28 02:44 UTC
Labels: type: Documentation, close ?
