### ISSUE TITLE
Add Global Reaching Centrality as measure of hierarchy (migrated from Trac #712)

### ISSUE THREAD

**Issue by networkx-trac** [networkx/networkx#698] opened 2012-07-20 23:42 UTC
Original ticket https://networkx.lanl.gov/trac/ticket/712
Reported 2012-04-05 by @conradlee, assigned to @conradlee.

Currently networkx implements one measure to measure how 'hierarchical' the structure of a directed graph is, located at networkx.hierarchy.flow_hierarchy.

Here I suggest another measure called "Global Reaching Centrality" suggested in the paper
'''
@article{mones2012hierarchy,
  title={Hierarchy measure for complex networks},
  author={Mones, E. and Vicsek, L. and Vicsek, T.},
  journal={Arxiv preprint arXiv:1202.0191},
  year={2012}
}
'''

I think the appropriate location for this measure is in networkx.hierarchy

This measure is defined for unweighted directed graphs, weighted directed graphs, and unweighted undirected graphs.  I will at least implement the measure for both weighted and unweighted directed graphs.

I plan to submit this implementation as a pull request on the github repository.

**Comment by mikk-c** [comment] 2017-02-01 15:23
Hi! I don't know if the issue is known and if it is planned a fix yet, but make sure "local_reaching_centrality" uses floats. The current development version uses ints and, as a result, it always returns the wrong result.

**Comment by jfinkels** [comment] 2017-02-06 04:19
Hi @mikk-c, can you provide a minimal working example that demonstrates the error (and what you expected as output)? Also what version of Python are you using? From what I see, the `from __future__ import division` should cause true division everywhere in the `networkx.algorithms.centrality.reaching` module.

**Comment by dschult** [comment] 2017-07-01 23:00
Closed by #2099

**Closed by dschult** 2017-07-01 23:00 UTC
Labels: Enhancement
