### ISSUE TITLE
Bug when checking flow feasibility in networksimplex.py

### ISSUE THREAD

**Issue by adamkatz10** [networkx/networkx#3408] opened 2019-04-28 15:20 UTC
In line 543-544 of network simplex.py the following code is ran:
    if any(x[i] != 0 for i in range(-n, 0)):
        raise nx.NetworkXUnfeasible('no flow satisfies all node demands')
I ran a debugger on my algorithm in PyCharm and noticed when I got to this point, some of my elements of x were 4.4 x 10^(-16). Clearly this number is 0, but the code does not recognize it as 0 and therefore returns and error to me when inputted with a graph where a flow is possible. I changed line 543 to read:
    if any(round(x[i], 10) != 0 for i in range(-n, 0)):
Once I made this change my code passed and no longer had any errors. I recommend y'all implement some kind of change like this so that elements of x that are essentially 0 recognized as such.

How will I know if/when this change is made?

Best!

**Comment by dschult** [comment] 2019-04-30 04:17
In the documentation for ```network_simplex``` (about line 95 in the file) there is a Notes section:

    Notes
    -----
    This algorithm is not guaranteed to work if edge weights or demands
    are floating point numbers (overflows and roundoff errors can
    cause problems). As a workaround you can use integer numbers by
    multiplying the relevant edge attributes by a convenient
    constant factor (eg 100).

This is a better fix than using some sort of tolerance for rounding. Any floating point computational problem will have round-off errors introduced. Flow feasibility does not tolerate round-off. Even rounding at 10 digits will cause inaccurate results for large graphs. So, don't use floating point values.

**Comment by adamkatz10** [comment] 2019-04-30 04:45
Thank you for your response!

In my journey to troubleshoot my issue I came across this. I would like to note all of my edge weights are integer values, as are my demands. The issue is arising for my capacities. Does the same answer apply?

Also, in my code when I create these capacities some are clearly not 0, but the other ones are entered in as exactly 0. In either python's representation of the capacity or through the networksimplex.py code, something is changing the representation to be 4.4*10^-16 (which of course is actually 0). So by the time it gets to line 543, a number that should be 0 is "no longer" 0.

**Comment by rossbar** [comment] 2022-06-28 18:39
I'm going to close this as one as a duplicate of #4641, as there's more discussion on the topic there.

**Closed by rossbar** 2022-06-28 18:39 UTC
Labels: floating-point
