### ISSUE TITLE
Long node names with an underscore make graphviz_layout fail 

### ISSUE THREAD

**Issue by jorge-cardoso** [networkx/networkx#3857] opened 2020-03-07 14:49 UTC
The following code makes graphviz_layout fail. The problem is related to the long name given to a node whichctntains an underscore: 'long_name_' * 40

import networkx as nx

G = nx.MultiDiGraph()
states = ['long_name_' * 40, 'a', 'b']
G.add_nodes_from(states)
G.add_edge(states[0], states[1], weight=1, label=1)
pos = nx.drawing.nx_pydot.graphviz_layout(G, prog='dot')
nx.draw_networkx(G, pos)

Traceback (most recent call last):
  File "C:/<removed>/sequence_model_mc_bug.py", line 10, in <module>
    pos = nx.drawing.nx_pydot.graphviz_layout(G, prog='dot')
  File "C:\<removed>\anaconda3\envs\py36\lib\site-packages\networkx\drawing\nx_pydot.py", line 268, in graphviz_layout
    return pydot_layout(G=G, prog=prog, root=root)
  File "C:\<removed>\anaconda3\envs\py36\lib\site-packages\networkx\drawing\nx_pydot.py", line 343, in pydot_layout
    node = node[0]
IndexError: list index out of range

**Comment by rossbar** [comment] 2020-08-06 23:10
I am unable to reproduce this error from the reported example on `master`. What version of NetworkX are you using? Also, the traceback reports an `IndexError` - it's not immediately obvious to me how that maps to the length of the string.

**Comment by MridulS** [comment] 2023-02-02 22:11
This works fine with `pygraphviz` BTW.

``` python
G = nx.Graph()
G.add_edge("long_name"*15, 1)
pos = nx.nx_agraph.graphviz_layout(G, prog="dot")
```

and as we are planning on deprecating `pydot` https://github.com/networkx/networkx/issues/5723, I'll go ahead and close this issue as a won't fix (this should be fixed in pydot anyway) :)

**Closed by MridulS** 2023-02-02 22:11 UTC
Labels: Pydot
