### ISSUE TITLE
max_weight_matching has different behavior based on which python version you use.

### ISSUE THREAD

**Issue by sukhwanchung** [networkx/networkx#3262] opened 2018-11-30 21:49 UTC
For my project, among (possibly) multiple maximum matchings of a (unweighted undirected) `Graph`, I want to select one maximum matching at random. It would be nice if I can guarantee that I can choose a maximum matching at uniformly random, but who knows how many maximum matchings exist and what they actually look like in a graph.

Since the `max_weight_matching` algorithm is deterministic, I try to add the randomness in choosing a maximum matching by permuting the node names and run the `max_weight_matching` algorithm and undo the permuting of namings. I ran something like below to see whether the output changes randomly:
```
import random
import networkx as nx

def relabel(G):
    shuffled_nodes = list(G.nodes())
    random.shuffle(shuffled_nodes)
    
    mapping = {u: v for u, v in zip(G.nodes(), shuffled_nodes)}
    inverse = {v: u for u, v in zip(G.nodes(), shuffled_nodes)}
    
    H = nx.relabel_nodes(G, mapping)
    
    return H, mapping, inverse

def relabel_then_find_matching(G):
    H, mapping, inverse = relabel(G)
    matching = nx.max_weight_matching(H)
    return set(((inverse[u], inverse[v]) for u, v in matching))


G = nx.Graph()
G.add_edges_from([(0, 1), (1, 2)])
print("Not relabeled")
print([nx.max_weight_matching(G) for i in range(10)])
print()
print("Randomly relabeled")
print([relabel_then_find_matching(G) for i in range(10)])
```

Firstly, I have noticed that in python 3.5 I do get different results but in python 3.6 and 3.7, permutation of node names do not affect the returned matching. I suspect that this is due to python's update happened in 3.6 on preserving orders in dictionaries. Is this right? I also want to know that kind of behavior is expected as you update from python 3.5 to 3.6.

Result of running the above code in python 3.5 with Networkx 2.1.
```
(py35) C:\Users\csukh>python C:\Users\csukh\Desktop\test.py
Not relabeled
[{(1, 2)}, {(1, 2)}, {(1, 2)}, {(1, 2)}, {(1, 2)}, {(1, 2)}, {(1, 2)}, {(1, 2)}, {(1, 2)}, {(1, 2)}]

Randomly relabeled
[{(2, 1)}, {(2, 1)}, {(0, 1)}, {(2, 1)}, {(1, 2)}, {(1, 0)}, {(1, 0)}, {(1, 2)}, {(1, 2)}, {(1, 2)}]
```
You can see that in python 3.5, randomly relabelling nodes makes `max_weight_matching` return between `(0,1)` and `(1,2)`.
However in python 3.6 with Networkx 2.1 (below) you always get the edge `(1,2)` as a maximum matching.
```
(py36) C:\Users\csukh>python C:\Users\csukh\Desktop\test.py
Not relabeled
[{(1, 2)}, {(1, 2)}, {(1, 2)}, {(1, 2)}, {(1, 2)}, {(1, 2)}, {(1, 2)}, {(1, 2)}, {(1, 2)}, {(1, 2)}]

Randomly relabeled
[{(1, 2)}, {(2, 1)}, {(1, 2)}, {(1, 2)}, {(2, 1)}, {(1, 2)}, {(2, 1)}, {(1, 2)}, {(2, 1)}, {(1, 2)}]
```

Secondly, it would be nice to have an optional parameter `random` in `max_weight_matching` that detremines whether the maximum matching is chosen at random.

Lastly, I wanted to know what would be the best way of adding randomness in `max_weight_matching`. I understand that the bossom algorithm itself might be biased in selecting maximum matching, but I want to reduce bias coming from the implementation of the algorithm.
For example, randomizing the initial node or edge where the algorithm starts.

Thanks for the great package.

**Comment by rossbar** [comment] 2022-06-28 19:16
There are quite a few different things going on here. Re: the first question - I suspect (but haven't don the work to prove) that the change is indeed due to the insertion-order guarantee of Python dictionaries introduced in Python 3.6. Seeing as the minimum supported Python version is currently 3.8, I'm not sure that issues surrounding dictionary ordering from the 3.5/3.6 transition are particularly relevant now.

Re: "randomizing" the results of `max_weight_matching` in a deterministic way, I don't think it makes sense to internally randomize a function that is not intended to be random. Since the outputs seem to depend on edge order, if you want to probe different outputs in a deterministic way, I'd probably try something along the lines of (untested):

```python
>>> edges = <your_edge_list>
>>> import random
>>> random.seed(0xdeadc0de)  # a new seed for each attempt
>>> random.shuffle(edges)
>>> G.add_edges_from(edges)
>>> nx.max_weight_matching(G)
```

Now that dicts are guaranteed to maintain insertion order, the above (or similar) should be a reliable way to deterministically reproduce "random" max weight matchings.

I will close this as (hopefully) no longer relevant given that we're well past the Python 3.6 boundary, but there may be more to do here. If so, please open a new issue so we can reframe the discussion outside of the context of old Python versions.

**Closed by rossbar** 2022-06-28 19:16 UTC
