### ISSUE TITLE
possible bug in read_gml?

### ISSUE THREAD

**Issue by joelmiller** [networkx/networkx#3157] opened 2018-09-13 15:45 UTC
If I go to Mark Newman's webpage and download the karate club graph: http://www-personal.umich.edu/~mejn/netdata/karate.zip

I do the command

    nx.read_gml('karate.gml')

and get the error 

    >NetworkXError: node #0 has no 'label' attribute

I get a different error when reading the example on the Wikipedia page for gml format.

https://en.wikipedia.org/wiki/Graph_Modelling_Language

    >NetworkXError: expected an int, float, string or '[', found 'n42' at (4, 5)

Am I misunderstanding something?

**Comment by dschult** [comment] 2018-09-13 20:15
The [technical report with specs for GML](http://www.fim.uni-passau.de/fileadmin/files/lehrstuhl/brandenburg/projekte/gml/gml-technical-report.pdf) linked to in the docs states that values need to be int, float, string or lists. And ```n42``` is not a string like ```"n42"``` would be.

It also looks like each node/edge should have a ```label``` attribute and the file karate.gml does not.

Perhaps our reader is being too demanding to 1) require quotes around a string and 2) require every node and edge to have a ```label```. But it is following the spec.

**Comment by ankitameht** [comment] 2018-10-04 16:05
Hey, can i take a look at this PR, if no else is looking.

**Comment by dschult** [comment] 2018-10-04 18:53
Sounds good!   Thanks!

We want a flexible reader, but it should write the official spec. :)

**Comment by ankitameht** [comment] 2018-10-05 17:35
Ok. I will have a look at the issue, although I am trying this for the first time!

**Comment by ankitameht** [comment] 2018-10-14 19:18
Hi Dan, 

Sorry for delay in responding. I suspect the error is coming from gml.py file at the following line:
https://github.com/networkx/networkx/blob/be7c67553d2d27db4c66ce20942e6e443c39bef5/networkx/readwrite/gml.py#L424

Now I have a question here - according to the logic, since `id` is like a unique identifier and `label` is its string name, why are both these supposed to be unique. Current issue could be resolved by creating a default label name (say using its `label-<id>`) if id is mentioned. 

Please let me know if I am looking in the right direction.

**Comment by dschult** [comment] 2018-10-15 00:28
I think the issue is that the reader gets to the token n42 (without quotes) in the gml file and creates this error:

    >NetworkXError: expected an int, float, string or '[', found 'n42' at (4, 5)

It expects n42 to be surrounded by quotes so it can be identified as a string. That would follow the official spec.  We want it to handle n42 by checking if it is an int, float, string or '[' and if not, to treat it like a string even though it doesn't have quotes around it.

I'm not sure that creating a default label name would help... I am sure that we don't want to make the resulting node anything other than 'n42'.  That is, we just want to treat the unquoted text as a string and make that the node in the output NetworkX graph.

**Comment by chebee7i** [comment] 2018-10-21 17:37
It may also make sense to provide a new argument such as `strict=False` that allows the user to turn off the flexible parsing of non-conformant gml files.

**Comment by mdeff** [comment] 2019-03-14 23:59
There's two different issues here:
1. Unquoted labels, i.e., `NetworkXError: expected an int, float, string or '[', found 'n42' at (4, 5)`.
2. Missing labels, i.e., `NetworkXError: node #0 has no 'label' attribute`.

If 1) is non-compliant, I think it's fair to fail, or to ignore the label.

For 2), I don't think the standard requires a label. As a fallback, NetworkX should use the `id`.
Note that Networkx does just that when importing a gexf with missing labels.

## Missing label example

For example, the following code produces a GML file that is not readable by NetworkX (while readable by graph-tool, gephi, and cytoscape).

```python
>>> import graph_tool as gt
>>> import networkx as nx

>>> graph = gt.Graph(directed=False)
>>> graph.add_edge(0, 1)
>>> graph.save('graph_gt.gml')

>>> G = nx.read_gml('graph_gt.gml')
NetworkXError: node #0 has no 'label' attribute
```

`graph_gt.gml`:
```
graph [
   node [
      id 0
   ]
   node [
      id 1
   ]
   edge [
      id 0
      source 0
      target 1
   ]
]
```

**Comment by RhodriM** [comment] 2019-04-15 19:08
> For 2), I don't think the standard requires a label. As a fallback, NetworkX should use the `id`.
> Note that Networkx does just that when importing a gexf with missing labels.

Slightly related, not sure if needs own issue: currently networkx doesn't seem to allow for multiple nodes with the same label. I don't see anything in the standard that states that the node label should be unique, only the id. I've used other tools (eg gephi etc) with gml that allow multiple nodes to have the same label. (to me the term 'label' itself doesn't imply a unique identifier, whereas 'id' certainly does).

Currently this is precluding me from using networkx with some other systems which use gml - but that doesn't mean networkx is at fault of course! Which is wrong? Should node labels for gml (or other file formats) be unique, or not?  

A related stackoverflow question:
https://stackoverflow.com/questions/43196192/networkx-allow-duplicate-node-labels

**Comment by dschult** [comment] 2019-04-21 10:06
We usually (for each format) try to write the graph using the standard for that format. These standards are publicly available and I think linked to from the docs. We sometimes (often?) deviate from the standards upon reading a formatted file to allow NetworkX to read files that are written by commonly used software that does not follow the standard.

@rhodrim . 
Can you explain what is precluded in NetworkX -- preferably, find the code that precludes it?
It seems to me you are confusing a node object with a node label. NetworkX allows any hashable object to be a node. You can also store node attributes (such as a label). The node is not the attribute and vice versa. The relabel_nodes_... function changes the node objects in the graph -- it does not change node attributes.

Perhaps by "labels" you mean the text written on each node when drawing using matplotlib -- see networkx.draw_networkx_labels() 
Perhaps you mean the "label" attribute presumably used to create GML files -- see networkx.set_node_attributes()
Be sure to get the right version of the docs for you networkx version.

**Comment by KanishkT123** [comment] 2019-09-11 15:20
I wonder if this also means that the `write_gml` method is technically out of spec, since it provides labels when the user does not, whereas GML seems to be fine with graphs that have node id's and no labels. 

Additionally, would it be alright for me to take a look at this particular issue? I am new to OSS so I definitely classify as a beginner!

**Comment by KanishkT123** [comment] 2019-09-11 15:30
Would it be alright for me to take a look at this! It seems to still be open and something I could probably handle as a first PR.

**Comment by KanishkT123** [comment] 2019-09-11 15:36
It actually seems like the second issue that @mdeff brings up was resolved, and the first isn't something that requires a fix (according to the same comment). Would that constitute closing this issue?

**Comment by KanishkT123** [comment] 2019-09-25 18:51
> It is certainly true that we can't read in the GML file available on Mark Newman's webpage. That file may be invalid GML, but we could probably read it anyway if we create our reader to be sufficiently flexible. 

I'm still working on this, had some personal stuff come up. I just wanted to point out that `nx.read_gml("karate.gml", label="id")` can correctly read Mark Newman's karate GML. Do you mean that the reader should read the GML file without having to be told that label="id"?

**Closed** 2019-09-28 18:40 UTC
Labels: Enhancement, Good First Issue
