### ISSUE TITLE
Unexpected results from Kernighan-Lin algorithm, also compared to another implementation

### ISSUE THREAD

**Issue by fawaz-dabbaghieh** [networkx/networkx#7230] opened 2024-01-16 02:06 UTC
Hi, I was trying to bisect a graph using the Kernighan-Lin algorithm implemented in Networkx. I have been testing on relatively simple graphs but the partitions I'm getting are quite random which doesn't make sense for a simple graph like that with the KL algorithm.
To test my theory, I tried another implementation of the same algorithm, namely [this one](https://github.com/mcavus/Kernighan-Lin), and the results given are much more stable or at least what is expected from the KL algorithm.

Looking at the screen shots below (made by a tool called Bandage for drawing genomic graphs). You can see how the results from the KL algorithm using Networkx seems somewhat random and not expected compared to the other implementation.

I can provide the codes if needed, but all I'm doing is simply loading the graph, calling `community.kernighan_lin_bisection` on the graph then giving each partition a color.

Please let me know if I can provide any more information.

![Netowrkx_implementation_KL](https://github.com/networkx/networkx/assets/23493178/e26b50e9-4296-42f2-8d0a-2bef0d58b80b)
![mcavus_implementation_KL](https://github.com/networkx/networkx/assets/23493178/4ba6a19d-b2db-4187-8f9b-cacda5ac0927)

P.S: I have tried other community algorithms implemented by networks and the results are more aligned to what is expected of the algorithm to do. E.g. using `greedy_modularity_communities` or using the, eignevector route with `nx.linalg.algebraicconnectivity.fiedler_vector`.

**Comment by dschult** [comment] 2024-01-16 02:41
Hard to say much with this much info. We know it seems to be changing from run to run more than expected. And we know that another implementation doesn't do that.
- does your network have weighted edges? Does it have multiedges (more than one edge between two nodes)? 
- have you tried increasing the number of iterations? If the results have not converged that might be a reason for variation from run to run.

**Comment by fawaz-dabbaghieh** [comment] 2024-01-16 03:19
Thank you for your swift reply. Please let me know if I can provide more information.

And yes, maybe I should run more tests and get back to you. but to answer your questions:

* The network does not have weighted edges, but there might be multiedges. A simple two-column file representing the edges between two nodes is attached below.
* I gave only 10 iterations before (not sure how many iterations should be given). I have now tried with different iterations values (500, 1000, 5000, 10000, 15000, 20000, and 100000), the results are attached below. This time I used `nx.draw_networkx_nodes` with `nx.kamada_kawai_layout` for drawing.
 
It doesn't seem to be converging, or at least with my understanding. But also it's now taking too much time for my use case with such high iteration values.

Thank you for your help.

[graph.txt](https://github.com/networkx/networkx/files/13944941/graph.txt)

![2087_mixed_mbg_200sample_netowrkx_500iterations](https://github.com/networkx/networkx/assets/23493178/7688c8f4-f759-4c5c-99dd-01bb43f4441e)
500 Iterations
![2087_mixed_mbg_200sample_netowrkx_1000iterations](https://github.com/networkx/networkx/assets/23493178/5fa59a5b-dc1a-4adb-b8f6-6d0246b32813)
1000 Iterations
![2087_mixed_mbg_200sample_netowrkx_5000iterations](https://github.com/networkx/networkx/assets/23493178/598de66c-fb73-423f-9ab6-e48202814179)
5000 Iterations
![2087_mixed_mbg_200sample_netowrkx_10000iterations](https://github.com/networkx/networkx/assets/23493178/6b2bb2a8-927c-4ab3-99f4-fc34596511e8)
10,000 Iterations
![2087_mixed_mbg_200sample_netowrkx_15000iterations](https://github.com/networkx/networkx/assets/23493178/55a6a637-0e10-46e4-b125-15a4258a3a18)
15,000 Iterations
![2087_mixed_mbg_200sample_netowrkx_20000iterations](https://github.com/networkx/networkx/assets/23493178/bc002e7a-0563-4461-be5c-a9918069a7c3)
20,000 Iterations
![2087_mixed_mbg_200sample_netowrkx_100000iterations](https://github.com/networkx/networkx/assets/23493178/fd876211-2c02-4902-a586-a8e4f4eae3c2)
100,000 Iterations

**Comment by fawaz-dabbaghieh** [comment] 2024-01-16 15:44
Thank you very much for taking a look at this.

I am guessing it has to do with the version used. I am currently using an old laptop as my current one broke, specifications:
- Ubuntu 18.04.6 LTS
- Python 3.6.9
- Networkx version 2.5.1

I ran your code exactly and got this.
![networkx_issue](https://github.com/networkx/networkx/assets/23493178/7d78a8bb-4c99-4e5a-995a-aeeef5c1dfd4)

So I re-ran things again on my work server with specifications:
- CentOS Linux version 7
- Python 3.10.13
- Netowrkx 3.2.1

and I got much better:
![networkx_issue](https://github.com/networkx/networkx/assets/23493178/dcc57d76-6b1c-44f5-9063-8dab5b573262)

I do not want to take more of your time. I am guessing I just need to make sure to work on current versions and maybe increase the number of iterations a bit.

**Comment by rossbar** [comment] 2024-01-16 18:05
Thanks all for trying this out - I think it's reasonable to expect that the root cause was the old version of networkx, so I will close this. If the behavior persists or something else comes up please feel free to reopen (or better yet open a new issue and link this one)!

**Closed by rossbar** 2024-01-16 18:05 UTC
