### ISSUE TITLE
`generate_random_paths` does not have a `seed` argument

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#7286] opened 2024-02-11 21:48 UTC
The `nx.generate_random_paths` iterator creates paths of specified length from `G`. This function is not seeded, so there is currently no way to reproduce results between runs.

**Comment by aaronzo** [comment] 2024-03-03 21:30
@rossbar I had a quick go at implementing this - changing the signature to:
```python
@py_random_state(5)
@nx._dispatchable(edge_attrs="weight")
def generate_random_paths(
    G, sample_size, path_length=5, index_map=None, weight="weight", seed=None
):
```
The convention in the codebase seems to be to use the numpy-backed `random.Random` subclass `PythonRandomViaNumpyBits` for new code. This was simple enough to achieve, but I had to substitute `np.random.choice` with `seed.choices` to get the same weighted choice behaviour. However, this generates different choices than `np.random.choice`, I guess through a different (probably less efficient) implementation that calls `seed.getrandbits`.

This would mean that user code that uses a set random seed would break when upgrading. Would we be okay with that? Or should we try and guarantee the state is the same as the current implementation if the global numpy RNG is seeded?

**Comment by dschult** [comment] 2024-03-04 04:01
This code uses a numpy random interface. Not a python random interface. So we should use `@np_random_state(5)`.
The documentation line about preferring `PythonRandomViaNumpyBits` for new code is supposed to be referring to the choice between numpybits and the old `PythonRandomInterface`. That choice determines how we use numpy random when the code uses the python random library.  Those classes wrap the numpy RNG to make it follow the Python random api. 

In this case the code uses the numpy random interface. So we should just use `@np_random_state`. No wrapper interface is needed.  Then replace `np.random.choice` with `seed.choice`.  I think this is correct and in alignment with our expected behavior.

**Comment by aaronzo** [comment] 2024-03-04 17:27
Ah - ok, wasn't aware of `np_random_state`. To get a random integer, `np.random.Generator` and `np.random.RandomState` aren't consistent with method names - the former has `integers` and the latter has `randint`. This seems like an issue? I've added the line:
```python
randint_fn = seed.integers if isinstance(seed, np.random.Generator) else seed.randint
```
and this does work but this seems a bit unsatisfactory

**Comment by rossbar** [comment] 2024-03-04 19:04
> This seems like an issue?

Yes, I think you're right. One of the original reasons for the `PythonRandomInterface` layer was to provide a consistent API between the Python random interface and the numpy random interface. However, I think the interface layer between numpy random interface layers doesn't exist (AFAIK). It may be possible to return an an interface layer from `create_random_state` to resolve this issue, though I'm not sure.

**Comment by aaronzo** [comment] 2024-03-04 20:36
There doesn't seem to be a natural interface to use in numpy (there's no shared base class), so it would have to be maintained in networkx. Do we consider this a requirement for this issue, or would we be ok with the instance check just for this function, for now, with a view to migrating all functions using `np_random_state` to a common interface? If so I can submit a PR

**Comment by dschult** [comment] 2024-03-04 20:42
I think your proposed solution is fine for this PR. 
I'll put this topic it in [the "community meeting"](https://scientific-python.org/calendars/) agenda for Wednesday.
But I think changing all the np_random_state, or changing `create_random_state` are out of scope for this PR.

Luckily I think (based on [the numpy docs](https://numpy.org/doc/1.23/reference/random/new-or-different.html) that we only have to create 4 methods in a subclass of generator to make this work.  

Then again, maybe we should just deprecate use of `RandomState` and get rid of a whole slew of issues. :)

**Closed** 2024-03-05 05:23 UTC
Labels: type: Enhancements
