### ISSUE TITLE
networkx-2.8-py3-none-any.whl wheel is NOT compatible with all python 3

### ISSUE THREAD

**Issue by mboisson** [networkx/networkx#5590] opened 2022-04-29 14:08 UTC
### Current Behavior
py3-none-any wheels (for networkx 2.8) should be compatible with all versions of python 3, or it should be a cp38, cp39, cp310, etc. Shouldn't it ? 

```
$ pip install networkx-2.8-py3-none-any.whl
Ignoring pip: markers 'python_version < "3"' don't match your environment
Processing ./networkx-2.8-py3-none-any.whl
ERROR: Package 'networkx' requires a different Python: 3.7.9 not in '>=3.8'
``` 

### Expected Behavior
That `py3` wheels don't have a requirement other than using python 3.x, for any x that is not EOL yet (python 3.7 is not EOL yet)

**Comment by jarrodmillman** [comment] 2022-04-29 18:17
networkx-2.8-py3-none-any.whl supports Python 3.8, 3.9, and 3.10.

**Comment by jarrodmillman** [comment] 2022-04-29 18:20
The command
```
pip install networkx
```
should install the most recent version of networkx that your system supports.

**Comment by mboisson** [comment] 2022-05-02 14:07
I get that, but shouldn't `py3` support all versions of Python 3 that are not end of life ? Python 3.7 is not yet end of life, and is still widely used.

**Comment by dschult** [comment] 2022-05-02 18:42
Are you saying that it should be named `networkx-2.8-py38.py39.py310-none-any.whl`?

**Comment by jarrodmillman** [comment] 2022-05-02 19:47
> then lead to confusing errors when it says that it can't install it.

The current error states:
```
ERROR: Package 'networkx' requires a different Python: 3.7.9 not in '>=3.8'
```

We can change this error message, if you have some suggestions.  It seems pretty clear to me, though. Would changing this to something like:
```
ERROR: Package 'networkx' version 2.8 requires a different Python: 3.7.9 not in '>=3.8'
```
make the error message clearer? We could also add something like:
```
If you can't upgrade your Python version, then you will need to use an older version of NetworkX.
```

**Comment by dschult** [comment] 2022-05-07 13:58
I’m going to close this since the names are chosen automatically, and since the error message is quite clear about what the problem is. Please comment more about suggestions for better error messages or other solutions. We will still see them and can re-open if needed.

**Closed by dschult** 2022-05-07 13:58 UTC
Labels: Question
