### ISSUE TITLE
Controlling the in_degree and out_degree of MultiDiGraph

### ISSUE THREAD

**Issue by vsharm29** [networkx/networkx#4175] opened 2020-08-21 05:51 UTC
```
def get_flowchart_nodes_by_type(graph):
    connector = []  
    process = []
    decision = []
    for node in graph.nodes:
        if graph.out_degree(node)>1:
            decision.append(node)
        elif graph.in_degree(node)==0 or graph.out_degree(node)==0:
            connector.append(node)
        else:
            process.append(node)

    return (connector, process, decision)
```

```
def plot_pydot(graph):
    pdot = nx.drawing.nx_pydot.to_pydot(graph)
    circle, rect, kite = get_flowchart_nodes_by_type(graph)
    for node in pdot.get_nodes():
        if node.get_name().strip('"') in kite:
            node.set_shape('diamond')
        elif node.get_name().strip('"') in circle:
            node.set_shape('rect')
        elif node.get_name().strip('"') in rect:
            node.set_shape('rect')

    outpath = os.path.join(__dirname__, 'pydot_out.png')
    pdot.write_png(outpath)
```
I am wondering is there any way to handle Degrees of the Graph. Rectangle can take multiple input and produce only one output. Decision will take multiple input and produce only two output.
Condition if Decision is having more than 2 outputs than there should be one more decision created with "xyz" name and connecting pending outputs of the decision.

Networkx output using pydot - https://ibb.co/PrzJB46
Third party app output - https://ibb.co/S30Rygm

**Comment by rossbar** [comment] 2020-10-08 02:05
I'm going to go ahead and close this one - the original question was difficult to understand because there seems to be a lot of missing context; also, the links are dead. If the issue persists, please feel free to reopen, preferably with a reproducible, minimal example.

**Closed by rossbar** 2020-10-08 02:05 UTC
Labels: Question
