### ISSUE TITLE
Can not pickle a graph once an edge iterator is obtained

### ISSUE THREAD

**Issue by glennehrlich** [networkx/networkx#2652] opened 2017-09-06 01:04 UTC
The following script causes an error when pickling a graph. Commenting out the line calling the edges method allows the pickling to happen. If I manually pickle with any combination of pickle/cPickle and protocol, it still fails if I call the edges method. I see that recently `__getstate__ ` and `__setstate__` methods were added to view classes. Maybe there's something still odd there?

```
# Python 2.7.13

import networkx as nx
import pickle as pickle
# import cPickle as pickle

n = nx.DiGraph()
print 'num edges: {}'.format(len(n.edges())) # commenting out this line makes it work
nx.write_gpickle(n, 'foo.gpickle')

```
The error message is:

```
num edges: 0
Traceback (most recent call last):
  File "foo2.py", line 9, in <module>
    nx.write_gpickle(n, 'foo.gpickle')
  File "<decorator-gen-352>", line 2, in write_gpickle
  File "/opt/anaconda/lib/python2.7/site-packages/networkx/utils/decorators.py", line 221, in _open_file
    result = func(*new_args, **kwargs)
  File "/opt/anaconda/lib/python2.7/site-packages/networkx/readwrite/gpickle.py", line 70, in write_gpickle
    pickle.dump(G, path, protocol)
TypeError: expected string or Unicode object, NoneType found

```

**Comment by glennehrlich** [comment] 2017-09-06 01:09
I'm wondering if the iterable that's saved in the view's `__setstate__` might be causing an issue. Some googling shows that some iterables aren't pickleable.

**Comment by dschult** [comment] 2017-09-06 12:18
Thanks very much for the report!  I'm looking into it.

**Comment by zorroblue** [comment] 2017-09-07 15:47
I am able to run the code snippet successfully. Is this issue due to some version incompatibility?

**Comment by glennehrlich** [comment] 2017-09-07 15:53
I'll try a couple of different platforms and versions of python and report back. Will be a day or so before I can get to it.

The python/platform under question is ubuntu 16.04 and anaconda python (mine says python 2.7.13). The networkx version was whatever commit it was when I wrote the message (as I had installed from the repo at that time).

**Comment by dschult** [comment] 2017-09-07 16:05
It definitely depends on version. And the error messages change too...  
But pickle problems are indeed caused by pickling iterators, lambda function, and other objects that require information outside of what is held in that object's __dict__.  I think the way to eliminate these errors is to have getstate/setstate avoid pickling these objects.

I can get rid of the reported error regarding G.edges (where G is a base graph class) by changing the __getstate__ and __setstate__ methods for EdgeView et al. But I am still chasing similar errors for pickling edges on a GraphView -- That is, for when G is a view of a graph.  I'll try to post a PR soon for people to look at.

**Comment by glennehrlich** [comment] 2017-09-07 16:17
Ahh, thanks for the report. I'll not try different versions then. Good luck on chasing down the issues and thanks for looking at this.

**Comment by dschult** [comment] 2017-09-08 15:11
I've added a bunch of tests for pickling and fixed any bugs they identified (including the one posted here :).  It would be great to have people check this by running their code against it. I'll merge which will close this Issue, but you can either reopen or just comment on the closed issue to provide feedback.

Thanks @glennehrlich for finding and reporting this.

**Closed** 2017-09-08 15:12 UTC

**Comment by glennehrlich** [comment] 2017-09-08 15:23
I've run tests and this fixes the problem. Thank you so much for the incredible turn around on this!
