### ISSUE TITLE
maximum_flow crashes on some pairs of nodes

### ISSUE THREAD

**Issue by ooii** [networkx/networkx#2842] opened 2018-01-23 13:45 UTC
I have a graph composed of 1037 edges, and 360 nodes. I want to compute `max flow` between some pairs of nodes and it happens, for some of them, that `nx.maximum_flow` ends with the pasted error, despite the fact that a path exists between the two concerned nodes and that `nx.maximum_flow_value` returns a value.

Here is the output of the crash which happens, at least, between "Sink_0" and "Aircraft3_37", "Sink_0" and "Aircraft4_40", and "Sink_0" and "Aircraft2_32":
Graph in `gexf` format is available [here](https://www.pastefile.com/ZPQAUM).
Python 2.7.10
networkx 1.11

```
ValueError                                Traceback (most recent call last)
<ipython-input-186-6dae3501e3d0> in <module>()
      1 #print(nx.shortest_path(G,source="Sink_0",target="node_32"))
----> 2 nx.maximum_flow(G, "Sink_0", "Aircraft2_32")

/Library/Python/2.7/site-packages/networkx/algorithms/flow/maxflow.pyc in maximum_flow(G, s, t, capacity, flow_func, **kwargs)
    156         raise nx.NetworkXError("flow_func has to be callable.")
    157 
--> 158     R = flow_func(G, s, t, capacity=capacity, value_only=False, **kwargs)
    159     flow_dict = build_flow_dict(G, R)
    160 

/Library/Python/2.7/site-packages/networkx/algorithms/flow/preflowpush.pyc in preflow_push(G, s, t, capacity, residual, global_relabel_freq, value_only)
    420     """
    421     R = preflow_push_impl(G, s, t, capacity, residual, global_relabel_freq,
--> 422                           value_only)
    423     R.graph['algorithm'] = 'preflow_push'
    424     return R

/Library/Python/2.7/site-packages/networkx/algorithms/flow/preflowpush.pyc in preflow_push_impl(G, s, t, capacity, residual, global_relabel_freq, value_only)
    279                 break
    280             u = next(iter(level.active))
--> 281             height = discharge(u, False)
    282             if grt.is_reached():
    283                 # Global relabeling heuristic.

/Library/Python/2.7/site-packages/networkx/algorithms/flow/preflowpush.pyc in discharge(u, is_phase1)
    156                 # We have run off the end of the adjacency list, and there can
    157                 # be no more admissible edges. Relabel the node to create one.
--> 158                 height = relabel(u)
    159                 if is_phase1 and height >= n - 1:
    160                     # Although the node is still active, with a height at least

/Library/Python/2.7/site-packages/networkx/algorithms/flow/preflowpush.pyc in relabel(u)
    125         """
    126         grt.add_work(len(R_succ[u]))
--> 127         return min(R_node[v]['height'] for v, attr in R_succ[u].items()
    128                    if attr['flow'] < attr['capacity']) + 1
    129 

ValueError: min() arg is an empty sequence
```

**Comment by jtorrents** [comment] 2018-01-24 18:51
Hi @ooii 

Thanks for the report. I cannot reproduce the error with the last release of NetworkX (2.1):

```python
In [29]: import networkx as nx
In [30]: G = nx.read_gexf('graph.gexf')
In [31]: flow_value, flow_dict = nx.maximum_flow(G, "Sink_0", "Aircraft3_37")
In [32]: flow_value
Out[32]: 77266.346
In [33]: flow_value == nx.maximum_flow_value(G, "Sink_0", "Aircraft3_37")
Out[33]: True
In [34]: flow_value, flow_dict = nx.maximum_flow(G, "Sink_0", "Aircraft4_40")
In [35]: flow_value
Out[35]: 84470.023
In [36]: flow_value == nx.maximum_flow_value(G, "Sink_0", "Aircraft4_40")
Out[36]: True
In [37]: flow_value, flow_dict = nx.maximum_flow(G, "Sink_0", "Aircraft2_32")
In [38]: flow_value == nx.maximum_flow_value(G, "Sink_0", "Aircraft2_32")
Out[38]: True
```

Can you upgrade NetworkX to 2.1? Version 1.11 is quite old (was released 2 years ago).

**Comment by ooii** [comment] 2018-01-25 07:57
Hi,
I upgraded to 2.1 and I don't have this issue anymore.
I should have posted a message to tell that.
Should I close the issue since it concerns an old version?

**Comment by dschult** [comment] 2018-01-25 16:36
Yes, close the issue...  it will still show up if someone searches for it. And we won't be fixing the old version.

**Closed by dschult** 2018-01-25 16:36 UTC
