### ISSUE TITLE
write/read/update/write again in Gexf create parallel edges

### ISSUE THREAD

**Issue by paulgirard** [networkx/networkx#1296] opened 2014-11-27 18:04 UTC
Dear networkx,

I hope this time my issue will target a real bug and not a RTFM.

Here is my test code : 

``` python
import networkx

g=networkx.Graph()
g.add_edges_from([(1,2),(2,3),(1,3)])
networkx.write_gexf(g,"test.gexf")

g=networkx.read_gexf("test.gexf")
g.add_edges_from([(4,5),(3,4),(1,5)])
networkx.write_gexf(g,"test_2.gexf")
```

Basically I create a very simple graph which I write as gexf.
Then I open this very same gexf as a graph.
I update this graph adding a few links.
And finally rewrite back in gexf.

Here is the gexf of test_2.gexf

``` xml
<gexf version="1.1" xmlns="http://www.gexf.net/1.1draft" xmlns:viz="http://www.gexf.net/1.1draft/viz" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3.org/2001/XMLSchema-instance">
  <graph defaultedgetype="undirected" mode="static">
    <nodes>
      <node id="1" label="1" />
      <node id="3" label="3" />
      <node id="4" label="4" />
      <node id="5" label="5" />
      <node id="1" label="1" />
      <node id="3" label="3" />
      <node id="2" label="2" />
    </nodes>
    <edges>
      <edge id="0" source="1" target="5" />
      <edge id="1" source="3" target="4" />
      <edge id="2" source="4" target="5" />
      <edge id="1" source="1" target="3" />
      <edge id="0" source="1" target="2" />
      <edge id="2" source="3" target="2" />
    </edges>
  </graph>
</gexf>
```

Now, the problem is the duplicated ids in edges.

When reading Gexf, ids are well stored in edge data if it exists ([see L854](https://github.com/networkx/networkx/blob/master/networkx/readwrite/gexf.py#L854)).
But when writing Gexf id edges are ([see L342 in gexf.py](https://github.com/networkx/networkx/blob/master/networkx/readwrite/gexf.py#L342) ) taken form edge data or generated by a itertools.count ([see L265](https://github.com/networkx/networkx/blob/master/networkx/readwrite/gexf.py#L265)).

The problem occurs when we add edges on top of edges imported from gexf.

The itertools.count() might be initialized with the max of existing id in edges data.
That requires to loop on edges before writing (which will loop over them again) but well.
Or one should check that the id proposes by the itertools.count() is not already taken. If yes iterates again on the count() ?

Thanks in advance for addressing this issue.
If I can help, please ask me.

Paul

**Comment by hagberg** [comment] 2015-01-09 02:05
Any opinion on the best fix for this?  I like the uuid approach for the simplicity in implementation but it would lead to some pretty ugly  id values.

**Comment by hagberg** [comment] 2017-08-14 21:59
Generating uuids seems overkill.   

The issue is that when reading the GEXF file NetworkX loads the edge id value as the edge attribute 'id'.  That value obviously can be changed or other edges can be added with the same id.   

When writing the networkx  GEXF implementation looks for an id attribute and if it doesn't find one starts generating integers starting at 0.  This clearly will cause conflicts.  

One approach would be to ignore the id attributes that GEXF uses and just generate new ones.  That breaks identity in round-trip reading/writing though.

Another approach is to loop through all of the edges before writing to discover the existing id attributes.  Then for edges without ids generate new ones with some algorithm that don't conflict with existing ids.

 This should be fixed but since we haven't decided on an approach I'm moving to networkx-2.1.

**Comment by hagberg** [comment] 2017-11-24 17:05
Needs design decision.

**Closed** 2019-03-29 13:07 UTC
Labels: Defect, Needs PR
