### ISSUE TITLE
`ordered.Graph` reorders edges on insert

### ISSUE THREAD

**Issue by Demetrio92** [networkx/networkx#3781] opened 2020-01-16 12:06 UTC
While `ordered.Graph` uses python's `OrderedDict` and the nodes' order is preserved (e.g. follows the order of nodes in which they were added), edges ordering is not. 

**Reproducible Example**
```python
import networkx as nx
G = nx.ordered.Graph()
nodes = ['A','B','C']
G.add_nodes_from(nodes)
G.add_edge(
    u_of_edge='A',
    v_of_edge='C',
    attr=1
)
G.add_edge(
    u_of_edge='B',
    v_of_edge='C',
    attr=2
)
G.add_edge(
    u_of_edge='B',
    v_of_edge='A',
    attr=3
)
```
```python
>>> print([id for id in G.nodes()])
['B', 'A', 'C']
```
```python
>>> print(G.edges(data=True))
[('B', 'C', {'attr': 2}), ('B', 'A', {'attr': 3}), ('A', 'C', {'attr': 1})]
```

-------
This is important and has far-reaching consequences, e.g. changing naming convention of the nodes, changes the results of METIS (https://github.com/networkx/networkx-metis), even with the same seed and `ordered.Graph` being used. 

-------
My system:
`python 3.7.5`
`Ubuntu 18.04.3 LTS`
`nx.__version__`: `2.4`

**Comment by dschult** [comment] 2020-01-16 18:08
Your example shows that both nodes and edges order is not maintained. But that's because your example uses ```nx.ordered.Graph``` instead of nx.ordered.OrderedGraph``` (which is more easily accessed as ```nx.OrderedGraph```).

But, your remarks do hold true for OrderedGraph. 
The OrderedGraph family of classes only orders the nodes in the order they were entered.
The edges have an order, but it is not the order that they were added.
(In fact it is the order of the adjacencies.)
The docs are careful to state that there are many potential orders and this one might not be what you expect. It is an ordering of the edges. It may not be the order that you expect.

Now that Python 3.6+ makes dict ordered, you probably don't need the OrderedGraph class. The order is determined and consistent across platforms and sessions, but again, it might not be the order you want.

This restriction should not affect the naming convention of nodes -- that is determined by you (or metis??). With the same input graph and the same seed I would definitely expect the same results. What are you changing between runs that are different?

**Comment by kakila** [comment] 2020-08-02 22:26
Thank you for your answer @dschult,
I hit the same issue when trying to reproduce an "edge ordered graph"
```python3

   g = nx.MultiDiGraph()
    for e in [(1,0), (2,0), (3,0), (1,4), (1,5), (4,2)]:
        g.add_edge(*e)
    print('g: ', g.edges)

    # doesn't conserve edge order
    g2 = nx.MultiDiGraph()
    for e in g.edges:
        g2.add_edge(*e)
    print('g2:', g2.edges)

g:  [(1, 0, 0), (1, 4, 0), (1, 5, 0), (2, 0, 0), (3, 0, 0), (4, 2, 0)]
g2: [(1, 0, 0), (1, 4, 0), (1, 5, 0), (4, 2, 0), (2, 0, 0), (3, 0, 0)]

```
Is there a recipe to create anew graph with the same edge order? I couldn't find anything.

**Comment by kakila** [comment] 2020-08-02 22:29
and as I wrote the answer I came up with the solution!
```python3
    g = nx.MultiDiGraph()
    for e in [(1,0), (2,0), (3,0), (1,4), (1,5), (4,2)]:
        g.add_edge(e[0], e[1])
    print('g: ', g.edges)

    # conserve edge order
    g2 = nx.MultiDiGraph()
    g2.add_nodes_from(g.nodes)
    for e in g.edges:
        g2.add_edge(e[0], e[1])
    print('g2:', g2.edges)

g:  [(1, 0, 0), (1, 4, 0), (1, 5, 0), (2, 0, 0), (3, 0, 0), (4, 2, 0)]
g2: [(1, 0, 0), (1, 4, 0), (1, 5, 0), (2, 0, 0), (3, 0, 0), (4, 2, 0)]
```

**Comment by dschult** [comment] 2020-08-02 23:57
It is true that the adjacency order is the same if you add all nodes before adding edges.
This can also be accomplished by using ```H=nx.MultiDiGraph(G)```, or if you prefer:
```python
H=nx.MultiDiGraph()
H.update(G)
```

In summary, the order of the edges is based on the adjacency dict-of-dict structure.
So, in general G.edges will not preserve the order of edges being added. But it does
preserve the order of the adjacencies and that can be propagated to another graph
by adding nodes from G before adding edges from G. This order preserving nature
is coded into the constructor ```nx.Graph``` as well as the update method ```H.update(G)```.

I'm going to close this issue, but post here with questions and I'll reopen if needed.

**Closed by dschult** 2020-08-02 23:57 UTC
