### ISSUE TITLE
Lazy imports cause broken numpy

### ISSUE THREAD

**Issue by RazerM** [networkx/networkx#5838] opened 2022-06-30 14:27 UTC
With modules that use astropy/numpy we experienced "AttributeError: Module 'numpy.core' has no attribute 'records'" and managed to find the root cause was networkx's `nx.lazy_import("numpy")`.

### Current Behavior

numpy's modules end up in a broken state

### Expected Behavior
numpy should behave the same way as it does when not lazily imported by networkx

### Steps to Reproduce

```python
# import numpy  # uncomment this line to prevent the lazy import and therefore error
import networkx
import astropy.time
```

```
Traceback (most recent call last):
  File "redacted.py", line 3, in <module>
    import astropy.time
  File "/myvenv/lib/python3.9/site-packages/astropy/time/__init__.py", line 19, in <module>
    from .formats import *  # noqa
  File "/myvenv/lib/python3.9/site-packages/astropy/time/formats.py", line 16, in <module>
    import astropy.units as u
  File "/myvenv/lib/python3.9/site-packages/astropy/units/__init__.py", line 21, in <module>
    from .quantity import *
  File "/myvenv/lib/python3.9/site-packages/astropy/units/quantity.py", line 31, in <module>
    from .quantity_helper import can_have_arbitrary_unit, check_output, converters_and_unit
  File "/myvenv/lib/python3.9/site-packages/astropy/units/quantity_helper/__init__.py", line 16, in <module>
    from . import erfa, function_helpers, helpers, scipy_special
  File "/myvenv/lib/python3.9/site-packages/astropy/units/quantity_helper/function_helpers.py", line 42, in <module>
    from numpy.lib import recfunctions as rfn
  File "/myvenv/lib/python3.9/site-packages/numpy/lib/recfunctions.py", line 13, in <module>
    from numpy.ma.mrecords import MaskedRecords
  File "/myvenv/lib/python3.9/site-packages/numpy/ma/mrecords.py", line 31, in <module>
    _byteorderconv = np.core.records._byteorderconv
  File "/myvenv/lib/python3.9/site-packages/numpy/core/__init__.py", line 161, in __getattr__
    raise AttributeError(f"Module {__name__!r} has no attribute {name!r}")
AttributeError: Module 'numpy.core' has no attribute 'records'
```

or

```python
# import numpy  # uncomment this line to prevent the lazy import and therefore error
import networkx
from numpy.lib import recfunctions
```

```
Traceback (most recent call last):
  File "redacted.py", line 2, in <module>
    from numpy.lib import recfunctions
  File "/myvenv/lib/python3.9/site-packages/numpy/lib/__init__.py", line 44, in <module>
    __all__ += type_check.__all__
NameError: name 'type_check' is not defined
```

### Environment

Python version: 3.9.6, 3.9.13, 3.10.5
NetworkX version: 2.8.4
Numpy version: 1.22.4
OS: macOS and Ubuntu Linux

**Comment by seberg** [comment] 2022-07-01 21:10
Seems all a bit strange.  I tried to lazyimport a module that does `from .submodule import *` and then fetches its `__all__`.  If I define the `__all__`, it actually seems to work fine.  But if I do not define `__all__` it fails, because `__all__` never ges auto-defined?

However, it errors then because `__all__` does not exist, not because the name itself is missing.  I am wondering if the `LazyLoader` is just subtly different when it comes to `__all__` (or maybe a bit more?).
I do suspect a it could be worked around by changing the imports a bit, but not quite sure.

**Comment by dschult** [comment] 2022-07-17 00:09
It does seem to be true that LazyLoader does not put the module name into the namespace while the regular import does.

My small example requires a package with a subpackage:
```
MyStuff:
 |  __init__.py
 |->    lib
          |  __init__.py
          |  somestuff.py
```
The outer `__init__.py` file is:
```python
from .lib import *
```
The inner `__init__.py` file is:
```python
#from . import somestuff
from .somestuff import *
print(somestuff.stuff)  # < -- NameError: name `somestuff` is not defined
```
The module `somestuff.py`:  `stuff = "stuff"`.

To construct the error run this script:
```python
import networkx as nx
ms = nx.lazy_import("MyStuff")
#import MyStuff
from MyStuff import lib    # or: `from MyStuff.lib import stuff`
```

The error only occurs for a subpackage, and does not depend on the relative reference`.somestuff` (the error still occurs with an absolute reference `MyStuff.lib.somestuff`).

The NameError goes away when you change the relative reference `from .lib import *` to an absolute reference `from MyStuff.lib import *`, or when the package is imported before the subpackage is imported -- shown here by uncommenting any one of the lines of code that are commented out above.  It also goes away if you don't try to LazyLoad.  (Note that the relative reference inside the subpackage does not matter. It is the relative import of the subpackage that determines the behavior.)

It seems that LazyLoader does not include the name of a module in a relatively referenced subpackage in the namespace of the subpackage when `from pkg import subpkg` or `from pkg.subpkg import *` form is used.  The regular (nonLazy) importing process does include the name of the module in the subpackage namespace.

**Comment by dschult** [comment] 2022-07-17 01:58
@seberg, the link you gave to a Python discussion/issue is similar, and certainly related to subpackages, but there the lazy load occurs in a sub package. And the full package is already imported explicitly before the subpackage names are requested.  Still, it does seem that both are related to how the LazyLoader is handling adding names to the sub_namespaces.

I suspect numpy could import the module names explicitly alongside importing their contents and the problem would go away. But that could make `__init__` much longer and is a shame to have to do simply because someone might lazyload your package. The best fix would be upstream in the LazyLoader code. I can raise an issue there if this discussion agrees that it is the best way forward.

If you want to try the `__init__` workaround, change each section like:
```python
from .type_check import *
from .index_tricks import *
from .function_base import *
from .nanfunctions import *
from .shape_base import *
```
to  (and this could instead group the two lines for each module if preferred):
```python
from . import type_check
from . import index_tricks
from . import function_base
from . import nanfunctions
from . import shape_base

from .type_check import *
from .index_tricks import *
from .function_base import *
from .nanfunctions import *
from .shape_base import *
```

**Comment by seberg** [comment] 2022-07-17 05:06
Yeah, that was my impression as well, Jarrod started trying it today and it looked good (but was very early).

I do wonder if LazyLoader could be "fixed" with respect to submodules here, but I have not looked at all whether it is easy.  The PEP explicitly mentions this as an incompatibility of the lazy loader!

**Comment by dschult** [comment] 2022-07-17 18:15
@RazerM Thanks for reporting this. We have a PR that removes the lazy load from networkx until this is worked out. We hope to have that in a release 2.8.5 very soon.  Hopefully we can get it fixed in Python's LazyLoader, but it's hard to know. As far as we know, this is a problem in NetworkX v2.7 - v2.8.4

Meanwhile the fix is to import numpy itself before importing from a subpackage of numpy.
```python
import networkx
import numpy
from numpy.lib import recfunctions
```

**Comment by RazerM** [comment] 2022-07-21 14:17
@dschult @seberg Thanks for the work on this. I didn't find any mention in the docs about incompatibilities with `importlib.util.LazyLoader`, and to be honest I'm not sure if it's a `LazyLoader` bug or a bug that numpy assumes submodules have already been imported implicitly. In the latter case we should probably file a numpy bug or start a discussion about whether they want to support it.

@seberg which PEP did you find? I only found https://peps.python.org/pep-0690/ which is about making all imports lazy-by-default in the future.

**Comment by seberg** [comment] 2022-07-21 14:20
@RazerM yes, that one: https://peps.python.org/pep-0690/#import-side-effects:
> relying on imported submodules being set as attributes in the parent module.

Which seems at least the main issue, possibly the only one.

**Comment by jamespharvey20** [comment] 2022-08-23 11:33
I think I ran into this same issue, but I'm not positive.

Using networkx 2.8.6, numpy 1.23.2, and matplotlib 3.5.3, with the following code:

```
import networkx as nx
import numpy as np
import matplotlib

array = np.array([[ 0, 1, 1],
   [1, 0, 1],
   [1, 1, 0]
   ])
graph = nx.from_numpy_matrix(array, create_using=nx.Graph)
layout=nx.circular_layout(graph)
nx.draw(graph, layout)
labels = nx.get_edge_attributes(graph, 'weight')
nx.draw_network_edge_labels(graph, pos=the_layout, edge_labels=labels)
```

I get the following exception:

```
Traceback (most recent call last):
  File "/mnt/fast/delivery.git/src/main.py", line 394, in <module>
    new_main()
  File "/mnt/fast/delivery.git/src/main.py", line 344, in new_main
    nx.draw_network_edge_labels(graph, pos=the_layout, edge_labels=labels)
  File "/mnt/fast/delivery.git/venv/lib/python3.10/site-packages/networkx/__init__.py", line 51, in __getattr__
    raise AttributeError(f"module {__name__} has no attribute {name}")
AttributeError: module networkx has no attribute draw_network_edge_labels
```

If I place a breakpoint on `__init__.py::51`, I can see that `name = {str} 'utils'`.

I seem to be running the merge from 29 days ago, since I think that's included in numpy 1.23.2.

**Comment by rossbar** [comment] 2022-08-23 14:53
@jamespharvey20 from the posted traceback it actually seems like the cause is a simple misspelling of the function name. Try `draw_networkx_edge_labels`.

Apologies if I'm missing something obvious

**Comment by jamespharvey20** [comment] 2022-08-23 16:01
> @jamespharvey20 from the posted traceback it actually seems like the cause is a simple misspelling of the function name. Try `draw_networkx_edge_labels`.
> 
> Apologies if I'm missing something obvious

Haha, my apologies!  Yes, you're right.  I hope you saw that quickly.  Adding the `x` makes it run fine.  PyCharm isn't able to pick up that there's a problem there.  I'm fairly new to Python, and didn't recognize that's the wording it gives if you try calling a non-existent function.

**Comment by stefanv** [comment] 2022-11-23 18:44
NumPy side resolved in https://github.com/numpy/numpy/pull/22045

**Closed** 2022-11-29 18:31 UTC
