### ISSUE TITLE
write_dot does not properly escape quotes in node attribute values

### ISSUE THREAD

**Issue by PaulRitter** [networkx/networkx#5499] opened 2022-04-08 10:52 UTC
when saving a graph with a node attribute value which contains one or more quotes, write_dot does not properly escape the quotes, leading to an invalid dot-file.

Actual:
```
NODEID [label="foo("bar")"];
```
Expected:
```
NODEID [label="foo(\"bar\")"];
```

I assume this issue also extends to edge attributes.

**Comment by MridulS** [comment] 2022-04-08 13:36
Thanks for the report! I can reproduce this.

Adding a minimal example:
```python
>>> import networkx as nx
>>> G = nx.Graph()
>>> G.add_node(0, label='"foo("bar")"')
>>> G.nodes.data()
NodeDataView({0: {'label': '"foo("bar")"'}})
>>> nx.nx_pydot.write_dot(G, 'test.dot')
>>> nx.nx_pydot.read_dot('test.dot').nodes.data()
NodeDataView({'0': {'label': '"foo("', 'bar': None, '")"': None}})

**Comment by yusuf-csdev** [comment] 2022-04-08 23:57
I have been debugging the sample code and I have came to conclusion that the issue is not related to NetworkX but Pydot. 

After nx.nx_pydot.write_dot(G, 'test.dot') line runs, we see that the label attribute is as expected (please see the image below).
![1](https://user-images.githubusercontent.com/62771956/162547262-05a6198c-f3f2-48ba-bd3e-a43ef992c51c.png)

This expected data is passed to read_dot function (please see the image below).
![2](https://user-images.githubusercontent.com/62771956/162547432-9bac75e6-429d-45e6-9562-6927c7dd3337.png)

However, after line 75 in nx.nx_pydot.py runs:
````python
P_list = pydot.graph_from_dot_data(data)
````
the attributes dictionary gets updated and it becomes:
````python
{'label': '"foo("', 'bar': None, '")"': None}
````
![3](https://user-images.githubusercontent.com/62771956/162547721-3893c538-0e2a-4b74-b7c8-f5e7f9853174.png)

**Comment by PaulRitter** [comment] 2022-04-10 14:45
@yusuf-csdev 
I'm a bit confused about what you discovered, but as far as i can tell, thats not the issue here.
The issue is that nx.nx_pydot.write_dot uses the to_string method provided by pydot to get the data to save to the file. The problem is that to_string returns a string-representation of the graph **without** properly escaped quotationmarks. Now this behaviour does make sense, since i'd assume the intended usecase of this method were to output the graph to the console to debug or something similar, not to write it to a file.

The invalid attribute dictionary you are observing after the read_dot call is due to the non-escaped quotes confusing the dot-parser.

The pydot library isn't at fault here and working as intended, networkx is just using the wrong function.

**Comment by MridulS** [comment] 2022-06-10 17:19
@PaulRitter this is indeed coming from pydot as the user needs to explicitly escape the strings in this case. Even if I use pydot to write the graph to a png file it will **not** automatically quote this specific string and throw an error. A minimal example here:

``` python
In [1]: import pydot

In [2]: graph = pydot.Dot("my_graph")

In [3]: graph.add_node(pydot.Node("A", foo='"foo("bar")"'))

In [4]: graph.write_png("output.png")
.....
.....
.....
AssertionError: "dot" with args .....

In [5]: graph.to_string()
Out[5]: 'digraph my_graph {\nA [foo="foo("bar")"];\n}\n'

In [6]: graph.write_raw("output_raw.dot")

In [7]: !cat output_raw.dot
digraph my_graph {
A [foo="foo("bar")"];
}
```

Now if the user properly quotes the string, pydot works.

``` python
In [1]: import pydot

In [2]: graph = pydot.Dot("my_graph")

In [3]: graph.add_node(pydot.Node("A", foo="foo(\"bar\")"))

In [4]: graph.write_png("output.png")

In [5]: graph.to_string()
Out[5]: 'digraph my_graph {\nA [foo="foo(\\"bar\\")"];\n}\n'

In [6]: graph.write_raw("output_raw.dot")

In [7]: !cat output_raw.dot
digraph my_graph {
A [foo="foo(\"bar\")"];
}
```

I'll close this issue for now, let us know if we can do something to make this better :)
Or you can open this issue on the pydot repo.

**Closed by MridulS** 2022-06-10 17:19 UTC
Labels: Defect
