### ISSUE TITLE
Feature request: MultiGraph.remove_edge(u, v) should removes all such edges, not an arbitrary one

### ISSUE THREAD

**Issue by clbarnes** [networkx/networkx#1349] opened 2015-02-05 19:36 UTC
Same goes for MultiDiGraph...

Currently, if a user wants to disconnect two nodes and doesn't know how many edges there are between them, the best way to do this is using an infinite while loop and breaking on exception. This has to throw and catch an exception for every edge removed, which can be a large number, and is thus inefficient.

**Comment by chebee7i** [comment] 2015-02-05 20:05
What if we added an `all=False` parameter?

**Comment by hagberg** [comment] 2015-02-05 20:10
Also

```python
In [1]: import networkx as nx

In [2]: G = nx.MultiGraph()

In [3]: G.add_edge(1,2)

In [4]: G.add_edge(1,2)

In [5]: G.add_edge(3,4)

In [6]: G.remove_edges_from(G.edges([1,2]))

In [7]: G.edges()
Out[7]: [(3, 4)]
```

**Comment by dschult** [comment] 2015-02-24 16:22
I think this should be a separate method:
Just as edges() returns edge info and neighbors() returns neighbor info, remove_edge() should remove individual edges and remove_neighbor() [or maybe disconnect_neighbor()] should remove all edges between two nodes.

I like the distinction between edges and neighbors.

**Comment by hagberg** [comment] 2015-02-24 17:02
I agree that this shouldn't be part of remove_edge.  But why is my suggested `remove_edges_from(G.edges())` solution not OK?  Too clunky or not obvious enough?

As a new method maybe `remove_all_edges()`?  We have a 'remove all nodes' (and edges) already with Graph.clear().

**Comment by dschult** [comment] 2015-02-24 17:15
Yes-- your solution with ```remove_edges_from(G.edges([u,v]))``` is sufficient. If not obvious enough we should add it to the doc_strings.

**Comment by hagberg** [comment] 2015-02-24 18:01
I'm also ok with `remove_all_edges(u=None, v=None)` or something like that.

**Comment by mad4alcohol** [comment] 2015-02-25 03:35
@hagberg if you look at `multigraph.py:517`, you will see what you suggest here is completely different than what is documented:
```python
>>> G = nx.MultiGraph()
>>> G.add_edges_from([(1,2),(1,2),(1,2)])
>>> G.remove_edges_from([(1,2),(1,2)])
>>> G.edges()
[(1, 2)]
```

I agree that `remove_all_edges(u=None, v=None)` seems better. A small problem: should we add an option `delete_node=False`, or automatically delete `u` when `remove_all_edges(u)` (`u` becomes isolated) is called?

**Comment by ysitu** [comment] 2015-02-26 07:38
I think that we should disallow `MultiGraph.remove_edge(u, v)`. Having unpredictable behavior is just bad. The user should always specify a key to name a specific edge.

**Comment by MridulS** [comment] 2015-02-26 07:56
I agree with @ysitu. The user should also be able to remove a specific edge.

**Comment by mad4alcohol** [comment] 2015-02-26 08:33
I feel OK with current 'remove_edge' method.

Firstly, you can delete a specific edge by filling the 'key' parameter if
you want. And if you look at 'add_edge', you'll find out that every edge
defined without a key will be given a numeric key in an incremental manner,
i.e. you can totally remove a specific edge.

Secondly, there are certain use cases e.g. when we do not care which edge
is deleted (for example, the edges are identical).

**Comment by ysitu** [comment] 2015-02-26 16:12
@mad4alcohol Removing an arbitrary element not caring about which is not usual programming practice. The user should be asked to explicitly express such desire for unpredictability.

**Comment by hagberg** [comment] 2015-02-26 17:32
Well there is

```python
In [1]: set.pop?
Type:        method_descriptor
String form: <method 'pop' of 'set' objects>
Namespace:   Python builtin
Docstring:
Remove and return an arbitrary set element.
Raises KeyError if the set is empty.```

so this type of thing isn't completely unprecedented.

As long as it is documented I feel it is OK.

**Comment by ysitu** [comment] 2015-02-26 21:58
@hagberg But `set.pop` in Python seems to be a weirdo of its own. You cannot do the same thing in C++, Java, Ruby or JavaScript.

**Comment by hagberg** [comment] 2015-02-26 22:25
The only other language I know other than Python is FORTRAN :-)
So maybe being weird is OK?

**Comment by mad4alcohol** [comment] 2015-02-27 04:43
Hi, @ysitu. The Python documentation for `dict.popitem` (version 3.4) explicitly states that "popitem() is **useful** to destructively iterate over a dictionary, as often used in set algorithms". So maybe it is at least **not discouraged** to have nondeterministic results when programming in Python.

I know that there are libraries which have their own design guidelines. But according to my observation, it seems that networkx does follow Python's style.

So IMHO, as long as this behavior is documented in `remove_edge` (which already is), we should leave it be to avoid any possible regressions or backward-incompatibility.

**Comment by ysitu** [comment] 2015-02-27 05:30
@mad4alcohol The use case of "destructive iteration" is along the line of

```python
try:
    while True:
        item = items.popitem()
        do_work(item)
except KeyError:
    pass
```

You do this with two intentions: 1) to iterate over all items; 2) discard the items as soon as you are done with them (so as to release memory, etc.). You just do not care about the iteration order and are therefore fine with nondeterminism.

One-off use of `dict.popitem()` is something very different. You want only one item and end up getting an arbitrary one. There is no guarantee for anything, not even for randomness. That makes it hard to reason about the semantics of the program.

`MultiGraph.remove_edge` is just like one-off use of `dict.popitem()`. Other than there being one edge less, there is not much you can say about the state of the graph. This creates code readability problems because code reviewers and others will scratch their heads when they encounter such arbitrariness. We should actively prevent people from getting into this kind of situations unnecessarily.

As for backward compatibility, it is not a big issue for NetworkX 2.0 because we have decided that breaking changes are okay as long as they improve the code.

**Comment by hagberg** [comment] 2015-02-28 18:56
I don't understand the fear of randomness or arbitrariness here.  

It seems like there are 3 cases for a multigraph M with multiple edges between u and v
1) want to remove edge and don't care which one - `MultiGraph.remove_edge(u,v)`
2) want to remove edge and have specific key - `MultiGraph.remove_edge(u,v,key=key)`
3) want to remove all edges - `MultiGraph.remove_edges_from(M.edges(u,v))`

Is that too confusing?

**Comment by dschult** [comment] 2015-02-28 20:44
Python is filled with arbitrary outcomes to the same code on different architectures. Many stem from the dict and set data structures. You can't even predict what order a dict's keys/values are printed.  You can't predict whether a lookup in a dict will require handling a collision. Arbitrary outcomes are not always a bad thing.

Removing an arbitrary edge between u and v leaves one less edge between u and v. That's pretty clear in many/most cases.

**Comment by hagberg** [comment] 2015-03-01 18:58
I suggest we close this and not adjust the behavior of `remove_edge()`.

**Closed** 2015-03-02 01:49 UTC
Labels: Declined

**Comment by ysitu** [comment] 2015-03-02 03:09
Closing this issue per se is okay, but I still believe that `key`-less`MultiGraph.remove_edge` is not a good thing. This is not about confusing names or functionality, but rather that the user should know and care about which edge gets removed. Argument based on arbitrariness in iteration order does not apply because such arbitrariness has only transient effect for being scoped to the iteration. Removing a single element has persistent effect and makes arbitrariness an implementation detail leaked into user code. `MultiGraph.remove_edge` makes it even worse because unlike `set.pop` and `dict.popitem`, it has no return value, i.e., the user does not even know what was lost and can do nothing about it. So, while yes, we certainly can keep `MultiGraph.remove_edge` as is, and there is little harm to NetworkX, we should try to make it harder for the user to do unfortunate things.
