### ISSUE TITLE
nx.simple_cycles counts more cycles than exist. 

### ISSUE THREAD

**Issue by serhiyandrejev** [networkx/networkx#4990] opened 2021-07-29 08:43 UTC
### Current Behavior
Function returns more than million cycles in graph that contains only 2000 edges and ~1300 nodes and 100-200 cycles.
### Steps to Reproduce
1. Load graph from this file. 
[graph_to_git.csv](https://github.com/networkx/networkx/files/6899157/graph_to_git.csv)
2. Call nx.simple_cycles on it. 

### Environment

Python version:3.7
NetworkX version: 2.5

**Comment by dschult** [comment] 2021-07-29 14:18
How are you counting the cycles to say that it only has 100-200 cycles?
Generally, constructing a graph with cycles will generate far more cycles than you might think.
The cycles you know are there can "add" together to create other possible cycles.

**Comment by serhiyandrejev** [comment] 2021-07-29 16:21
> How are you counting the cycles to say that it only has 100-200 cycles?
> Generally, constructing a graph with cycles will generate far more cycles than you might think.
> The cycles you know are there can "add" together to create other possible cycles.

I know, `cause I'm using the same algorithm for previous data. At that data was only 1709 edges and only 60 cycles. Now, there are only 2089 edges, but simple_cycles counts 1148313 cycles. 

So, after adding to the graph some new data its started to found too many cycles. 
There is old data. 
[first_graph_to_git.csv](https://github.com/networkx/networkx/files/6902032/first_graph_to_git.csv)

**Comment by MridulS** [comment] 2021-07-29 18:55
I tried this with the data provided but it looks like both `first_graph_to_git.csv` and `graph_to_git.csv` are the same files
``` python
>>> all(pd.read_csv('first_graph_to_git.csv') == pd.read_csv('graph_to_git.csv'))
True
```
Could you link to the dataset with the old data?

**Comment by serhiyandrejev** [comment] 2021-07-29 19:31
> I tried this with the data provided but it looks like both `first_graph_to_git.csv` and `graph_to_git.csv` are the same files
> 
> ```python
> >>> all(pd.read_csv('first_graph_to_git.csv') == pd.read_csv('graph_to_git.csv'))
> True
> ```
> 
> Could you link to the dataset with the old data?


My bad. It was a missclick. There is old data. 
[first_graph_to_git.zip](https://github.com/networkx/networkx/files/6903170/first_graph_to_git.zip)

**Comment by MridulS** [comment] 2021-07-30 13:23
So I started looking at the data and it seems like yes there are more than a million cycles in the new data but it doesn't seem like a bug in the code, maybe how this data is generated? (assuming you are expecting it have 100-200 cycles).

On the networkx implementation side most of it seems to follow the definition of a simple cycle in a directed graph. They are unique cycles.

I have added some code below I used while thinking through this.

``` python
import pandas as pd
import networkx as nx
from collections import defaultdict

old = nx.from_pandas_edgelist(pd.read_csv('first_graph_to_git.csv'), create_using=nx.DiGraph())
new = nx.from_pandas_edgelist(pd.read_csv('graph_to_git.csv'), create_using=nx.DiGraph())
```

Number of cycles
``` python
>>> len(list(nx.simple_cycles(old)))
60
>>> len(list(nx.simple_cycles(new)))
1148313
```

Let's look at the paths and their length.
``` python
paths = defaultdict(list)
for i in nx.simple_cycles(new):
    paths[len(i)].append(i)
```

There are more than 90k cycles just of length 27.
``` python
>>> sorted([(len(j), i) for i, j in paths.items()])
[(4, 46),
 (11, 3),
 (20, 4),
 (20, 5),
 (24, 6),
 (26, 2),
 (55, 7),
 (56, 45),
 (82, 8),
 (187, 9),
 (348, 44),
 (358, 10),
 (718, 11),
 (1317, 12),
 (1318, 43),
 (2393, 13),
 (3515, 42),
 (4099, 14),
 (6736, 15),
 (7251, 41),
 (10569, 16),
 (12189, 40),
 (15859, 17),
 (16705, 34),
 (17219, 39),
 (17884, 33),
 (18838, 35),
 (20948, 38),
 (21355, 36),
 (22374, 37),
 (22541, 18),
 (25297, 32),
 (30617, 19),
 (40109, 31),
 (40256, 20),
 (51687, 21),
 (60018, 30),
 (63908, 22),
 (74944, 23),
 (79311, 29),
 (83546, 24),
 (89967, 25),
 (92193, 28),
 (94809, 26),
 (96632, 27)]
```

 Let's look at a subgraph from just one of these paths.
``` python
temp = nx.subgraph(new, paths[27][0])
nx.draw_circular(temp)
```
<img width="541" alt="Screenshot 2021-07-30 at 15 11 20" src="https://user-images.githubusercontent.com/5363860/127657725-08c83d1c-cf55-43a3-ba2b-342e2a14c08f.png">

As you can see this isn't really a large graph, just 27 nodes and 51 edges.
``` python
>>> temp.number_of_edges(), temp.number_of_nodes()
(51, 27)
```
and it has 1008 cycles, as @dschult mentioned, these cycles add up pretty quickly.
``` python
>>> len(list(nx.simple_cycles(temp)))
1008
```

I would maybe look at the data generation process, if you expecting low number of cycles in the graph. It looks like the graph structure of the old dataset seemed to have "lucked" out in terms of cycles inside.

**Comment by rossbar** [comment] 2021-07-31 09:03
Thanks for the excellent analysis @MridulS !

I'm going to go ahead and close this as resolved given that it seems that the original question was caused more by unexpected properties of the specific graph rather than a bug in `simple_cycles`. If this proves not to be the case or a minimal reproducing example that illustrates a defect in NetworkX functionality is found, please feel free to reopen or open a new issue.

**Closed by rossbar** 2021-07-31 09:03 UTC
Labels: Question
