### ISSUE TITLE
graphviz_layout fails with certain node labels

### ISSUE THREAD

**Issue by rgrenz** [networkx/networkx#5662] opened 2022-05-25 10:06 UTC
### Current Behavior
When trying to layout a graph using nx_pydot.graphviz_layout, all nodes with labels of the form "A:B" that share the same prefix "A" are positioned at the same coordinates.

### Expected Behavior
The node labels should be properly escaped during the layout procedure, and should not share the same position on the final layout.

### Steps to Reproduce
```
G = nx.Graph()
G.add_edges_from([
    (1, "Example:A"),
    (2, "Example:B"),
])
pos = nx.nx_pydot.graphviz_layout(G)
nx.draw(G, pos, labels={node: node for node in G.nodes()})
```
![image](https://user-images.githubusercontent.com/82824798/170236870-0182c34e-e0f0-4059-825b-a456c44a318f.png)

This does not occur when changing ":" to another separator like "_":
```
G = nx.Graph()
G.add_edges_from([
    (1, "Example_A"),
    (2, "Example_B"),
])
pos = nx.nx_pydot.graphviz_layout(G)
nx.draw(G, pos, labels={node: node for node in G.nodes()})
```
![image](https://user-images.githubusercontent.com/82824798/170237188-213ff2ca-bb0e-4639-9d84-bddb4ec8126d.png)

### Environment
Python version: 3.8.13
NetworkX version: 2.8

**Comment by MridulS** [comment] 2022-05-26 17:51
Thanks for the report @rgrenz! This is indeed an issue but this comes from `pydot` and we already have raised this upstream https://github.com/pydot/pydot/issues/258.

``` python
>>> import pydot
>>> pydot.Node("Example:A").get_name()
'Example'
```
A quick way right now is to use this hack-ish way of dealing with `:` in node names:

``` python
G = nx.Graph()
G.add_edges_from([
    (1, '"Example:A"'),
    (2, '"Example:B"'),
])
``` 

I'll go ahead and close this for now, please feel free to reopen an issue if there is something else we can do here :)

**Closed by MridulS** 2022-05-26 17:51 UTC

**Comment by AnjoMan** [comment] 2022-07-20 03:40
Wondering if its possible to reopen this issue? I think the solution that we came to here was not nuanced enough to account for all of the 'dot' syntax and ignores some parts of pydot that seem to work fine.

The syntax `Example:A` and `Example:B` have a specific meaning in graphviz where `A` and `B` are supposed to be ports of the node `Example` within i visually structured node shape, allowing for arrows pointing to specific parts of the node. There is additional documentation [here](https://graphviz.org/doc/info/shapes.html#record). Rejecting `Example:A` because it isn't quoted means that existing code which uses networkx to build a graph using these features would break (this is the situation i'm in, since i have existing code that builds dot graphs using networkx and pydot)

In addition, while I agree that there is a bug in pydot where ':' is present in *certain* attribute values, i don't see it occurring universally.

For example, if i define the following graph using networkx:

```python
   G = nx.Graph(node=dict(shape='record'))
    G.add_node("TapeShieldCableInfo", label="{<header>TapeShieldCableInfo|<contents>name: +copper-wound\l}")
    G.add_node("Cable", label="{<header>Cable|<contents> + name: string\\l + length: integer}")
    G.add_edge(
        "TapeShieldCableInfo:header",
        "Cable:contents",
    )
```

I can convert this to pydot as follows:

```python
    source = nx.nx_pydot.to_pydot(G)
```

This produces a dot string that looks like this:

```
strict graph  {
node [shape=record];
TapeShieldCableInfo [label="{<header>TapeShieldCableInfo|<contents>name: +copper-wound\l}"];
Cable [label="{<header>Cable|<contents> + name: string\l + length: integer}"];
TapeShieldCableInfo;
Cable;
TapeShieldCableInfo:header -- Cable:contents;
}
```

Here you can see that the 'label' attribute of each of my node definitions is properly quoted (note i'm using networkx 2.7 to make these examples, since 2.8 rejects the values).

In addition, if i render this using `graphviz.Source(str(source).render(...)` i get the following image:

![image](https://user-images.githubusercontent.com/2414360/179889646-3ae90f7e-dbfb-4575-987e-8c9c6ee0777f.png)

You can see here that because i've defined my edge as `TapeShieldCableInfo:header -- Cable:contents" I get an edge linking the top of the `TapeShieldInfo` node to the bottom of the `Cable` node. This is exactly how `graphviz` is supposed to work, and although I agree its a bit counter-intuitive to someone who hasn't familiarized themselves with the syntax, its not a bug.


What I have found is that i can only reproduce an issue with the attribute values if i remove all special characters (other than colon) from the attribute before invoking pydot on the data:

```python
    G = nx.Graph(node=dict(shape='record'))
    G.add_node("TapeShieldCableInfo", label="TapeShieldCableInfoname:copperwound234")  # only apha-numeric  chars and :
    G.add_node("Cable", label="{<header>Cable|<contents> + name: string\\l + length: integer}")
    G.add_edge(
        "TapeShieldCableInfo:header",
        "Cable:contents",
    )
```
produces

```
strict graph  {
node [shape=record];
TapeShieldCableInfo [label=TapeShieldCableInfoname:copperwound234];
Cable [label="{<header>Cable|<contents> + name: string\l + length: integer}"];
TapeShieldCableInfo;
Cable;
TapeShieldCableInfo:header -- Cable:contents;
}
```

which results in a syntax error if i try to render to png using the graphviz backend. This relates to the issue in https://github.com/networkx/networkx/issues/4663 where someone had trouble specifying a gradient as an attribute value. In that case i think it makes more sense to only reject attribute values in the form `<alphanumeric string>:<alphanumeric string>' since pydot seems to properly handle other attribute values, and they are valid graphviz syntax.

**Comment by rossbar** [comment] 2022-07-20 11:42
Thanks for the feedback @AnjoMan . Long story short, the pydot interface in networkx has had a lot of problems lately, largely stemming from the fact that `pydot` does not currently seem to be actively maintained. Given this, the current plan is to deprecate the `nx_pydot` interface entirely - see [this pinned issue](https://github.com/networkx/networkx/issues/5723).

**Comment by AnjoMan** [comment] 2022-07-21 13:17
@rossbar ok, that makes sense to me. i will look at switching to `pygraphviz` on my end
