### ISSUE TITLE
Remove numpy matrix

### ISSUE THREAD

**Issue by NeilGirdhar** [networkx/networkx#3107] opened 2018-08-01 11:39 UTC
networkx crashes when run with `warnings.simplefilter("error")` because numpy emits:

> PendingDeprecationWarning: the matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.

`numpy.matrix` should not be used anymore.

**Comment by dschult** [comment] 2018-08-01 13:29
Agreed.  Let's replace ```numpy.matrix```

**Comment by NeilGirdhar** [comment] 2018-08-01 18:59
Are you okay with just ripping out methods like `to_numpy_matrix`?  I can make this change if so.

**Comment by dschult** [comment] 2018-08-01 21:03
Since numpy is just coming out with v1.15 and that documentation (see the link in the original post above) only states,  ```Given the above, we intend to deprecate matrix eventually.``` . I can't find any other indication of the impending deprecation.

Thus, I don't think there is any hurry here... And I think some people will still be using numpy.matrix for a long time. It looks like we have already fixed up most of the code in NetworkX that used ```numpy.matrix``` by replacing it with arrays. If it really is only the ```to_numpy_matrix``` and ```from_numpy_matrix``` functions that we are changing, then I'm much less worried about the whole thing.

Probably the right approach for those two functions is to insert a warning in the docstring that using numpy.matrix is discouraged and will eventually be deprecated. Also include a suggestion to use ```to_numpy_array``` instead.  That should nudge people the right direction.

But the primary question I think is:

**Are there other places in NetworkX that uses numpy.matrix?**

**Comment by NeilGirdhar** [comment] 2018-08-01 21:11
Yes, there are.  Search for `as_matrix`.  I got hit by one and since I run my code with all warnings are errors, it crashed my program.

**Comment by ericmjl** [comment] 2018-08-01 22:25
@dschult this apparently could be a good first issue, given how routine this one is. It mirrors the first issue that I worked on for matplotlib - removing all the pylab examples in the documentation (which really was just a bunch of changing imports). This looks like one that a newcomer could tackle (with some guidance, just as I had from the matplotlib devs).

I'll take a stab at a deprecation statement for to_numpy_matrix, but I'd like to hold off on the full removal of to_numpy_matrix from the codebase - it's a win-win opportunity to bring someone new on board!

**Comment by dschult** [comment] 2018-08-01 22:54
This all sounds good!   Thanks...

**Comment by NeilGirdhar** [comment] 2018-08-02 01:47
@ericmjl In that case do you mind committing #3109 since there might be a delay on this and I don't want to run into this deprecation again?

**Comment by stschoberg** [comment] 2019-07-15 05:01
@ericmjl Still looking for that newcomer to bring on board? I'd love to take a stab at this. Just started using networkx this summer and would love to contribute.

**Comment by rossbar** [comment] 2020-07-06 01:09
Here are some thoughts after having looked at this issue a bit.

Removing the use of `np.matrix` in networkx involves changing both *internal* and *user-facing* code. These two categories of changes are addressed separately.

**Internal code**

This refers uses of `matrix` objects or operations within `networkx` code, but where the function/method I/O is not a `matrix` object. An  example would be the `_tracemin_fiedler` function:
https://github.com/networkx/networkx/blob/c07bc09e8c9f698c8e8f0a500399272d807bb4c6/networkx/linalg/algebraicconnectivity.py#L190-L296
There are some important distinctions between the `np.matrix` and `np.ndarray` classes that need to be kept in mind. The two main ones are:
 1. `np.matrix` objects are *always* 2D
 2. the multiplication and power operations (which behave element-wise for `ndarray`) are overridden with *matrix multiplication* and *matrix power* operations whenever *any* of the inputs are matrix objects.

There are other subtle differences that are less likely to come up within networkx, things like:
 - `matrix` objects can be initialized with a special Matlab-like string syntax
 - `matrix` objects have additional properties like `.A`, `.H`, and `.I` (array, conjugate transpose, inverse) that are not available/applicable to `ndarray` objects.

Changing internal code to get rid of uses `matrix` is relatively straightforward as it shouldn't directly affect anything that the user sees. A general approach to handling the two main issues cited above is to:
 1. Replace instances of multiplication with a matrix object with the `@` operator
 2. Use approaches for guaranteeing the shape of arrays, e.g. the `ndmin` kwarg of `np.array` or the `np.atleast_2d` function.

**User-facing changes**

I.e. code that either *inputs* or *outputs* `matrix` objects. Changing the type of the objects expected/returned by such functions obviously has the potential to introduce changed behavior in downstream code. Therefore, I agree with @ericmjl that any changes need to be accompanied by clear and concise warnings. AFAICT, there are two such instances in the codebase (please add to this list if you find more!):
 - [ ] `networkx.convert_matrix.to_numpy_matrix`
 - [ ] `networkx.linalg.attrmatrix.attr_matrix`

The sole purpose of `to_numpy_matrix` is to return a `np.matrix` object, so I think deprecation makes the most sense. In the case of `attr_matrix`, the output is an attribute/adjacency matrix which could just as easily be represented with an `ndarray` instead. For this case, perhaps emitting a `FutureWarning` notifying users that the output type will change from `matrix` to `ndarray` makes the most sense.

**Comment by jarrodmillman** [comment] 2020-07-08 01:05
I would like the user-facing changes to be part of the 3.0 release.  The deprecation warnings should appear in the 2.5 release.

It may also be worth using this opportunity to revisit the names and unify things a bit.  For example, see Aric's comment in #2029.  I haven't looked at it, but there are some changes to ``convert_matrix.py`` in #2066.

To track deprecated code add a note here:
https://github.com/networkx/networkx/blob/master/TODO.txt

**Comment by rossbar** [comment] 2020-07-08 01:13
I need to do a more complete grepping of the code base to ensure we've found everything that needs to be changed/deprecated. I will continue to update this issue as I find instances. I'm adding this to the 2.5 milestone to ensure we get all the deprecation/future warnings in in time!

**Comment by dschult** [comment] 2021-01-07 21:09
How are we doing with removing `numpy.matrix` from networkx? 

I only know of #4089 still open.  I think we still haven't deprecated or changed `attr_matrix` (checkbox above).
And we **have** deprecated `to_numpy_matrix`.

Are there other issues/prs we need to finish before closing this issue?

**Comment by stefanv** [comment] 2021-01-08 08:51
The only place I could find not mentioned above is `algorithms.link_analysis.pagerank_alg.py:google_matrix`.

**Comment by stefanv** [comment] 2021-01-08 08:52
(`attr_matrix` can be solved as Jarrod suggested---by returning an array instead)

**Comment by mjschwenne** [comment] 2021-04-12 19:30
Hello!

I'm looking to get involved with NetworkX and this looks like a good first issue.

It seems that there are still a few places using `numpy.matrix` in the linalg module. Namely `directed_combinatorial_laplacian_matrix`, `directed_laplacian_matrix` and `_tranistion_matrix` which still use `numpy.matrix`. `attr_matrix` also still uses `numpy.matrix` as a return type.

Are we looking to change these methods now or simply add warnings that they are going to change in the future (NetworkX 3.0 seems to be the version mentioned)?

**Comment by rossbar** [comment] 2021-04-12 20:55
Hey @mjschwenne - this has proved to be a sticky issue. After spending many cycles on it, I had decided that I would actually be in favor of leaving internal uses of `np.matrix` in place. The reasoning here is that `scipy.sparse`, which is used heavily in linalg uses `np.matrix` by default - until that's changed upstream, any changes made in NX would essentially make our own code more complicated and less reliable for very little benefit. I have a longer take on this [here](https://github.com/networkx/networkx/pull/4141#issuecomment-774344058).

That being said, I do think we generally want to try to eliminate instances in networkx where our public functions return `np.matrix` objects. I *think* most of these have been changed or discussed, but if you find instances feel free to raise them!

**Comment by NeilGirdhar** [comment] 2021-04-12 21:24
@rossbar Did you file an issue with scipy, and if so would you mind linking it here?

**Comment by rossbar** [comment] 2021-04-13 15:47
> Did you file an issue with scipy, and if so would you mind linking it here?

Good point; I haven't, but it's definitely worth checking through the scipy issues/mailing list and linking to the relevant discussions.

**Comment by NeilGirdhar** [comment] 2021-04-13 16:27
@rossbar I think I found the issue: https://github.com/scipy/scipy/issues/8162.   Does what they say at the end about PyData Sparse address your concerns for networkx?

**Comment by rossbar** [comment] 2021-04-13 16:45
Thanks @NeilGirdhar that's definitely a very relevant discussion. pydata sparse has been discussed in the past, but AFAIK no one has looked at it enough in-depth to be able to determine whether or not it is suitable. At a glance, I think some of the issues mentioned in the thread (e.g. dependency on `numba`/`llvmlite`) would also be blockers for NetworkX, or at least require further discussion.

IMO the `sparse` question is deserving of an [NXEP](https://networkx.org/documentation/latest/developer/nxeps/index.html) - I had intended to start one in the past, but have never had the time to fully survey the current state of sparse data structures in the ecosystem. The first step would be compiling information about the various libraries including their advantages, drawbacks, limitations, and dependencies.

**Comment by NeilGirdhar** [comment] 2021-04-13 16:57
@rossbar Sounds great!

**Comment by jarrodmillman** [comment] 2021-05-20 19:54
We've done everything we can until we sort out the situation upstream.  We are well aware of the problem and will hopefully have time to look into this in the next couple of years.

**Closed** 2021-05-20 19:54 UTC
Labels: Maintenance

**Comment by NeilGirdhar** [comment] 2021-05-20 20:00
@jarrodmillman Does it make sense to close this issue while `np.matrix` still shows up in tests?

**Comment by dschult** [comment] 2021-05-20 20:08
@neilgirdhar the problem is that scipy.sparse uses np.matrix and we don't want to stop using scipy.sparse.

**Comment by NeilGirdhar** [comment] 2021-05-20 20:16
@dschult Yes, I understand, and I agree with your decisions.  I guess I would have left the issue open since it's still a problem that just happens to depend on https://github.com/scipy/scipy/issues/8162.
