### ISSUE TITLE
NetworkX read_edgelist() dropping nodes and edges from tsv input file

### ISSUE THREAD

**Issue by realmarcin** [networkx/networkx#3964] opened 2020-05-18 19:53 UTC
Hello,

I am trying to load a fairly large graph (16M edges) with NetworkX. The edge file can be found here:
http://genomics.lbl.gov/~marcin/merged_edges_simple.tsv.gz

This is the code to reproduce the issue:

g = nx.read_edgelist(input_file, nodetype=str, data=(('weight', int),), create_using=nx.Graph())
print("[INFO] Number of nodes:{} and number of edges: {}.".format(len(g.nodes()), len(g.edges())), flush=True)

This produces the following output:
Number of nodes:336359 and number of edges: 10292807.

However, the input tsv file has more edges and nodes, namely:
- 16173904 edges based on wc of the input file (this includes ~1000 redundant edges per 'sort | uniq')
- 451237 nonredundant nodes

For some reason about 6M edges are being lost and over 100k nodes, when the data is loaded by NetworkX. My best hunch is this may be because of odd characters in node labels? Is there anything else that could lead to this behavior?

This is using NetworkX 2.4 and python 3.7.

many thanks,
marcin

**Comment by dschult** [comment] 2020-05-18 20:34
The cause is hard to guess based on this (tho I didn't download and look at the file).
I would focus on nodes first (fewer of them). Is it possible that some are equated even though they aren't officially the same for some reason? 
Perhaps take a smaller portion of the file and run that through and see if you can track down specific nodes that are in the file but not in the resulting graph. It shouldn't be hard to write a small python scrip to read in the edgelist and create a set of nodes that you can compare to the generated graph. Sets will also check if any nodes are "equal" (only add one when there are many). You should check the delimiter too -- whitespace is fairly generic andis a common source of misreads. 

You can often get quite far with a short script like:

```python
for i,line in enumerate(file.readlines()):
    s = line.strip().split()
    if len(s) < 2:
        print(line, s, "Skipped line!", j)
        continue
    node1 = s.pop(0)
    node2 = s.pop(0)
    # add a print statement or many...
    nodes.add([node1, node2])
    if j>10:
        break
```

**Comment by realmarcin** [comment] 2020-05-22 19:20
Many thanks for the response and tips, indeed inspecting the nodes sounds like a great first test and I will try to step through the input file as you suggested. I also realized that there are effects of using specific Graph type classes vs what is in the input. So the edge count discrepancy  may actually be directed edges being represented as a single edge. But that stil leaves the nodes to be explained -- I will update here when I have a resolution.

**Comment by dschult** [comment] 2020-07-22 19:47
@realmarcin do you have any updates?   
I'm going to close this, but you can simply post anyway and we will see it. We can reopen if you find a bug.

**Closed by dschult** 2020-07-22 19:47 UTC
