### ISSUE TITLE
How to speed up calculating the graph edit distance between graphs whose size is about 30 nodes ?

### ISSUE THREAD

**Issue by tiankonghenlan20113046** [networkx/networkx#4113] opened 2020-07-29 04:57 UTC
Hello,dear author,

I have a dataset which covers about 2000 graphs, this dataset covers the graphs who has about 30 nodes.The dataset format is like as following

```
......
t # 11808
v 1 C  
v 2 C  
v 3 O  
v 4 O  
v 5 C  
v 6 S  
v 7 S  
v 8 O  
v 9 O  
v 10 C  
e 1 2 1
e 1 4 1
e 1 5 1
e 2 3 1
e 2 10 1
e 5 6 1
e 6 7 1
e 7 8 2
e 7 9 2
e 7 10 1
t # 15905
v 1 C  
v 2 C  
v 3 C  
v 4 C  
v 5 C  
v 6 C  
v 7 S  
v 8 C  
v 9 C  
v 10 C  
v 11 C  
v 12 C  
v 13 N  
v 14 O  
v 15 O  
e 1 2 1
e 2 3 2
e 3 4 1
e 4 5 2
e 1 6 2
e 4 7 1
e 7 8 1
e 8 9 1
e 9 10 2
e 10 11 1
e 11 12 2
e 8 13 2
e 7 14 2
e 7 15 2
e 5 6 1
e 12 13 1
t # 17157
....
```
The explanation of this train.txt is :
t # 11808 means the graph's id is 11808, 
v 1 C  means the label of vertex 1 is 'C' 
e 1 2 1 means the label of the edge from vertex 1 to vertex 2 is 1.

Now I should select a graph randomly as a query graph from this dataset. Next I will calculate the graph edit distance (GED) between this query graph and other graphs  from this dataset.  Before I calculate 1999 pais of graphs, I do a test between a pair of graphs. It cost me about 3.5 hours. [The code](https://github.com/networkx/networkx/blob/1800fe9108a7e9706c21659f9b9e01da7f4c74ef/networkx/algorithms/similarity.py#L37) I use is in the link ,it is shown as follows.

```
path,cost = nx.optimal_edit_paths(g,query_graph,
                                                        node_match = lambda node1,node2:node1['label']==node2['label'],
                                                        edge_match = lambda edge1:edge2:edge1['label']== edge2['label']) 
```

It is too slow for me. And want to speed up the speed. I  want to use parallel computing , but I cannot have the ability to implement it.So I have some questions : 

1.How to speed up the result of GED about 2000 pairs of graphs?
2.Could I use the parallel computing to implement it ?

The result of the code is too important for me ,because I want to do an index of the dataset to complete a query duty. So I want to do a ground_truth by the networkx code above. Hope I can get a contact with you  who has the idea.

**Comment by rossbar** [comment] 2020-08-03 17:24
A few things come to mind:

1. verify that your entire dataset (all 2000 graphs) are loaded into memory *before* the calculation is performed. If you are loading the graphs one-by-one for each GED calculation, then disk I/O is very likely your bottleneck.

2. Comparing every graph to every other in this way scales as n^2. It might be worth taking a step back to see if you can come up with an approach that avoids this one-to-every comparison for each graph.

3. Re: parallelism - at face value this problem does seem like it could be parallelized in a straightforward way. I recommend taking a look at `concurrent.futures`, `multiprocessing`, or any one of the many libraries that bring parallel computation features to Python.

This question is rather specific and not really specific to networkx, so I'm going to close it. Please feel free to respond (even though the issue is closed) or, if you have more nx-specific questions, reopen this or open a new issue.

**Closed by rossbar** 2020-08-03 17:24 UTC
Labels: Question
