### ISSUE TITLE
read_gml fails on python 3 due to chr/unichr issues

### ISSUE THREAD

**Issue by avgl-sstraub** [networkx/networkx#1440] opened 2015-03-31 15:29 UTC
From what I've seen there is no official support for python 3.x yet, but I've been working with networkx on python 3.4 without issues, well, until now: When I try to read a previously created GML file using `networkx.read_gml(file)`, I get this exception

    Traceback (most recent call last):
      (...)
      File "/usr/local/lib/python3.4/dist-packages/networkx/readwrite/gml.py", line 125, in read_gml
        G = parse_gml(lines, relabel=relabel)
      File "/usr/local/lib/python3.4/dist-packages/networkx/readwrite/gml.py", line 174, in parse_gml
        data = "".join(lines)
      File "/usr/local/lib/python3.4/dist-packages/networkx/readwrite/gml.py", line 124, in <genexpr>
        lines = (unescape(line.decode('ascii')) for line in path)
      File "/usr/local/lib/python3.4/dist-packages/networkx/readwrite/gml.py", line 79, in unescape
        return re.sub("&#?\w+;", fixup, text)
      File "/usr/lib/python3.4/re.py", line 175, in sub
        return _compile(pattern, flags).sub(repl, string, count)
      File "/usr/local/lib/python3.4/dist-packages/networkx/readwrite/gml.py", line 69, in fixup
        return unichr(int(text[2:-1]))
    NameError: name 'unichr' is not defined

I couldn't figure out whether this whole `unichr`/`chr`-thing between python 2 and 3 can be somehow resolved, but if there is an easy way to do it, I'd love to see an update. If someone can point me in the right direction here, I can try to fix it myself and create a pull request.

**Comment by chebee7i** [comment] 2015-03-31 16:52
What version of NetworkX are you running?

**Comment by chebee7i** [comment] 2015-03-31 16:52
And btw, we've been supporting 3.x for some time now.

**Comment by ajelesnia** [comment] 2015-03-31 20:38
Had the same issue here using python 3.4 and using networkx version 1.9.1, that version was last release in Sept. 2014 and the fix was merged in November 2014. 
Might have to checkout the repo to get the latest update

**Comment by mheilman** [comment] 2015-03-31 20:38
It looks like the issue is that this try catch on `unichr` isn't in 1.9.1:

https://github.com/networkx/networkx/blob/master/networkx/readwrite/gml.py#L66

**Comment by avgl-sstraub** [comment] 2015-04-01 07:50
sorry for the delay... I'm using the latest version from pypi, which is 1.9.1, and I'm running python 3.4. On pypi it says the supported python version is 2.7, so I was assuming there was no official python 3.x support yet.

But yeah, it looks like the issue is resolved on the master branch, so all I have to do is wait for the networkx 1.9.2 release, right?

**Comment by OrkoHunter** [comment] 2015-04-01 07:54
@avgl-sstraub You can install the latest version from the repo itself. And in the next version, NetworkX 2.0 will be rendering better Python 2/3 support.

**Comment by SanketDG** [comment] 2015-04-01 15:23
@avgl-sstraub 

If you want to get the latest development trunk of NetworkX, then do this in the command line:
`pip install git+https://github.com/networkx/networkx.git`

**Comment by SanketDG** [comment] 2015-05-07 16:49
I believe this can be closed.

**Closed** 2015-05-07 17:25 UTC
