### ISSUE TITLE
attribute values may change when written then read by nx_pydot

### ISSUE THREAD

**Issue by johntconklin** [networkx/networkx#2145] opened 2016-05-26 16:26 UTC
If an attribute value has a dot reserved character, the attribute value will be quoted when written by pydotplus.  But the reverse is not done when the value is read back.  In this example:

``` python
import networkx
import networkx.drawing
import tempfile

g1 = networkx.DiGraph()
g1.add_node("foo", nodeattr=":FOO:")
g1.add_node("bar", nodeattr=":BAR:")
g1.add_edge("foo", "bar", edgeattr="FOO->BAR")

with tempfile.NamedTemporaryFile() as f:
        networkx.drawing.nx_pydot.write_dot(g1, f.name)
        g2 = networkx.DiGraph(networkx.drawing.nx_pydot.read_dot(f.name))

print("G1:", g1.node["foo"])
print("G1:", g1.edge["foo"]["bar"])

print("G2:", g2.node["foo"])
print("G2:", g2.edge["foo"]["bar"])
```

The value of the _foo_ node's _nodeattr_ attribute is changed from ':FOO:' to '":FOO:"'.  Similarly the _foo_ to _bar_ edge's _edgeattr_ attribute is changed from 'FOO->BAR' to '"FOO->BAR'".

Arguably, this could be considered a bug in the way that pydotplus handles attribute values. However, since nx_pydot already handles quoted node and edge id's (at least to some degree),  it should probably handle attributes as well.

**Comment by hagberg** [comment] 2016-05-27 16:42
It would be great if pydot/pydotplus would fix this.  Would you report it there?  I know we can fix it to round-trip correctly with networkx but as I pointed out in #2050 we've spent quite a lot of time dealing with quotes and special dot string issues already
 - https://github.com/networkx/networkx/issues/1872
 - https://github.com/networkx/networkx/issues/1348
 - https://github.com/networkx/networkx/issues/317
 - https://github.com/networkx/networkx/issues/350
 - https://github.com/networkx/networkx/issues/184

**Comment by hagberg** [comment] 2016-05-28 15:19
This does work correctly with pygraphviz.  e.g.

```python
import networkx
import networkx.drawing
import tempfile

g1 = networkx.DiGraph()
g1.add_node("foo", nodeattr=":FOO:")
g1.add_node("bar", nodeattr=":BAR:")
g1.add_edge("foo", "bar", edgeattr="FOO->BAR")

with tempfile.NamedTemporaryFile() as f:
        networkx.drawing.nx_agraph.write_dot(g1, f.name)
        g2 = networkx.DiGraph(networkx.drawing.nx_agraph.read_dot(f.name))

print("G1:", g1.node["foo"])
print("G1:", g1.edge["foo"]["bar"])

print("G2:", g2.node["foo"])
print("G2:", g2.edge["foo"]["bar"])
```

**Comment by johntconklin** [comment] 2016-05-28 17:33
@hagberg, I think you're right that this should be handled in pydotplus.

From the experimentation I've done so far, all that is needed is a relatively simple change to the parser to have it de-quote quoted strings. Unfortunately, the pydotplus unit tests don't seem to be working, so I'm not yet 100% confident that this change doesn't break anything else. 

But if it works, is accepted, and a new pydotplus release is published, the code in nx_pydot to strip leading and trailing quotes could even be removed.

I have two pending pydotplus pull requests.  A third change is needed to address this issue, but it's dependent on one of the others.

**Comment by hagberg** [comment] 2016-05-28 17:54
Thanks, that is great, https://github.com/carlos-jenkins/pydotplus/pull/9

**Comment by johnyf** [comment] 2016-07-02 05:53
`pydot` is again maintained (I am the maintainer), over here: https://github.com/erocarrera/pydot.
`pydot == 1.2.2` has been released [on PyPI](https://pypi.python.org/pypi/pydot/1.2.2) and runs in both python 2 and 3, and all tests are passing on Travis CI.

I am planning to open a pull request to `networkx` to use `pydot` again, reverting #1898 and #1924.
@johntconklin, the pull requests to `pydotplus` can be reviewed to be applied upstream.

`pydotplus` is at e06552ea3989bfb998ef6920a07d6c966ff9b01b, from Dec 2014, so it may be unmaintained. Upstream `pydot` has merged (or replaced) almost all the changes from [this fork](https://github.com/nlhepler), on which `pydotplus` was based.

**Comment by johnyf** [comment] 2016-11-08 07:01
#2272 has been merged, so upstream `pydot` changes will affect `networkx`.

**Closed** 2017-01-15 23:14 UTC
Labels: External, Not a defect

**Comment by peternowee** [comment] 2020-10-29 17:55
Just for the record: The change proposed in https://github.com/carlos-jenkins/pydotplus/pull/9 got in pydot through another PR: https://github.com/pydot/pydot/pull/134, commit https://github.com/pydot/pydot/commit/160c1997918b7a601948961c705ced2942c9a9fb in October 2016.

**Comment by peternowee** [comment] 2020-10-29 20:18
However, that (commit pydot/pydot@160c199) did not solve the original issue:

```python3
import networkx
import networkx.drawing
import tempfile

g1 = networkx.DiGraph()
g1.add_node("foo", nodeattr=":FOO:")
g1.add_node("bar", nodeattr=":BAR:")
g1.add_edge("foo", "bar", edgeattr="FOO->BAR")

with tempfile.NamedTemporaryFile() as f:
        networkx.drawing.nx_pydot.write_dot(g1, f.name)
        g2 = networkx.DiGraph(networkx.drawing.nx_pydot.read_dot(f.name))

print("g1:", g1.nodes["foo"])
print("g1:", g1.edges[("foo", "bar")])

print("g2:", g2.nodes["foo"])
print("g2:", g2.edges[("foo", "bar")])

# Output with networkx 2.5, pydot 1.4.1:
# g1: {'nodeattr': ':FOO:'}
# g1: {'edgeattr': 'FOO->BAR'}
# g2: {'nodeattr': '":FOO:"'}
# g2: {'edgeattr': '"FOO->BAR"'}
```

I think the issue is more related to pydot/pydot#66, pydot/pydot#72 and pydot/pydot#170.
