### ISSUE TITLE
DiGraph in_edges returns wrong view when using nbunch

### ISSUE THREAD

**Issue by th1j5** [networkx/networkx#4745] opened 2021-04-20 10:46 UTC
### Current Behavior
`g.in_edges(nbunch=<node(s)>)` returns an `InEdgeDataView` if nbunch is supplied aka `is not None`.
Else (`nbunch is None`), it returns an `InEdgeView`.

### Expected Behavior
`g.in_edges(nbunch=<node(s)>)` returns an `InEdgeView`.
This would be more consistent and would enable the chaining of `.data()` call in all cases.
(It should be noted that this is duplicate behaviour compared by using the parameter `data=True`)
Moreover, the returned `InEdgeDataView` doesn't contain any data if not asked (with `data=True`)

### Steps to Reproduce
```python
>>> g = nx.DiGraph()
>>> g.add_edge(1,2,color='blue')
>>> g.in_edges() # == g.in_edges(nbunch=None)
InEdgeView([(1, 2)])
>>> g.in_edges(2) # == g.in_edges(nbunch=2)
InEdgeDataView([(1, 2)])
```
more observations
```python
>>> g.in_edges().data()
InEdgeDataView([(1, 2, {'color': 'blue'})])
>>> g.in_edges(2)
InEdgeDataView([(1, 2)])
>>> g.in_edges(2, data=True)
InEdgeDataView([(1, 2, {'color': 'blue'})])
```

### Environment

Python version: 3.8.5
NetworkX version: 2.5
Tested in IPython

**Comment by rossbar** [comment] 2021-04-20 18:23
This does indeed seem strange: it's not clear why providing `nbunch` would change the output type to `InEdgeDataView`. At face value I also agree with you on what the expected behavior would be, though it's worth noting that the other classes tend to return `*DataView`s even when `nbunch=None`, e.g.

```python
>>> G = nx.MultiGraph()
>>> G.add_edge(1, 2, color="blue")
>>> G.edges()
MultiEdgeDataView([(1, 2)])
>>> H = nx.MultiDiGraph()
>>> H.add_edge(1, 2, color="blue")
>>> H.in_edges()
InMultiEdgeDataView([(1, 2)])
```

**Comment by rossbar** [comment] 2021-04-20 20:39
>  Though maybe what you mean is that the names of the class view objects are incomplete in their description. 

This was the cause of my confusion, but the description you gave makes sense. This behavior [isn't quite captured in the docstring](https://github.com/networkx/networkx/blob/643f45705eb68068e430367847829a35152f0ca5/networkx/classes/digraph.py#L909-L914) so that could certainly be improved. That's also a good point about `.edges` vs. `.edges()`, which I've been confused by before as well.

**Comment by th1j5** [comment] 2021-04-20 21:31
I don't have anything to add, this was just some inconsistency in my eyes that I wanted to report (and your explanation helps to resolve a good part)
Also, I'm not sure if the chaining is documented anywhere, but this might be considered, if there is a good place.
(furthermore, the library is very handy for our project, thank you!)

**Comment by dschult** [comment] 2021-04-28 02:35
I'm closing this with the issue #4765 taking the lesson learned and focusing on improving the docs.

**Closed by dschult** 2021-04-28 02:35 UTC
