### ISSUE TITLE
Documentation Links Broken on Google

### ISSUE THREAD

**Issue by EntilZha** [networkx/networkx#2094] opened 2016-04-18 22:17 UTC
It looks like recently the documentation was migrated to readthedocs instead of github.io. This seems to be causing widespread link breakage on google results. Could there be any changes made to put a permanent redirect or have google pickup those changes?

**Comment by hagberg** [comment] 2016-04-18 22:21
#2093 

Apparently there is some trickery to make the redirect work with github pages but it is beyond my technical ability.  I hope the site gets reindexed by Google soon.  

The documentation is at https://networkx.readthedocs.org/

All of the old documentation is at https://networkx.github.io/documentation/

**Comment by Michael-E-Rose** [comment] 2016-04-21 08:52
Duplicate of #2093.

**Comment by Michael-E-Rose** [comment] 2016-05-03 11:52
Issue can be closed. Google reindexed networkx.

**Closed** 2016-05-03 16:57 UTC
