### ISSUE TITLE
Unable to parallelize with large graph objects

### ISSUE THREAD

**Issue by ischmidt20** [networkx/networkx#5922] opened 2022-08-09 00:34 UTC
With a large graph object (~6 GB), parallel jobs started with Dask and/or Ray fail to compute. The processes are distributed to the workers, but they will be inactive for large periods of time. The same parallel processing setup works with smaller graphs (<1 GB), and using forked workers via the `multiprocessing` package instead of Dask or Ray also works with the large graph object.

### Current Behavior

I need to compute lots of shortest paths on a relatively large graph. Through my university department, I have access to a compute cluster, so I wrote code to compute these shortest paths in parallel. A subset of nodes in the graph is analyzed, and for each of those nodes, I have to compute shortest paths to ~30 other nodes. The parallelization is at the node level, and each individual node should not take more than a few seconds to analyze.

With a smaller graph, the processes are distributed to the workers, and the computation runs in parallel as expected. However, with a larger graph, the processes are distributed, but the vast majority remain inactive for long periods of time. Then one will briefly come alive for a few seconds, complete the task, before falling silent again. The computation does not complete.

This is *not* an issue caused by memory constraints in the cluster. The large graph object is about 6 GB, and the compute nodes these were run on have between 128 GB and 256 GB of memory. Between 4 and 16 workers were chosen, and the same behavior was observed in all cases.

### Expected Behavior
The nodes should be processed in parallel, networkx should do the computation, and the program returns at the end. Currently, the processes are distributed, but no computation is being done.

### Steps to Reproduce

This one is tough as my code is fairly convoluted. But here is the structure of my code:

```
import dask
import dask.multiprocessing
import networkx as nx

if __name__ == '__main__':
    dask.config.set(scheduler = 'processes', num_workers = 16)
    # load data and preprocess
    def analyze(node): # do a bunch of shortest paths and return something

    futures = []
    for departureNode in G.nodes:
        if condition:
            futures.append(dask.delayed(analyze)(departureNode))
    results = dask.compute(futures)

    # do a bunch of post processing and save to files
```

### Environment

Python version: 3.8.3
NetworkX version: 2.8

### Additional context
CCing @paciorek, who is the admin of the compute cluster and is the one who spent lots of time trying to investigate this issue. I want to re-emphasize that there is nothing wrong with the parallel structure or the analysis code itself, considering that:

1. With a smaller graph, everything runs fine.
2. With the large graph, forked workers via `multiprocessing` runs as expected

The issue is that with Dask and Ray, the computation fails.

Per @paciorek:

>  So it seems like it has something to do with the fact that all the workers are sharing the (somewhat large) G object. That said, the behavior as I see it doesn't seem particularly consistent with delays involved in copying G to the worker processes, which was one initial hypothesis I had. (It's not entirely clear to me what copies are / are not made given G is a global variable used within analyze()). Given that, I also tried making G a variable that is passed into analyze()  but that didn't seem to have any effect.

> I tried running your workflow using ipyparallel and Ray instead of Dask and had similar problems. So it feels like there is something about the big network object that causes various parallelization frameworks to choke in some fashion. It almost seems like two workers can't be actively working on their tasks at the same time. Ray has a nice 'object store' paradigm where you can control things such that each worker gets a copy of an object rather than a copy being made for each task, but even with that more explicit control over copies to the workers, I still had the problem.

> I experimented some with Ray and simply passing 'G' in as an argument to analyze() without using it in analyze(), causes the weird behavior (either with or without G being put in the Ray object store). So it seems like something about the structure of the G object is causing extreme lags before the core computation in analyze() even starts, though it's not clear to me that it is as simple as the lag being the time involved to make a copy of G. Once the computation starts, it seems to go as quickly as expected.

It may also be worth noting that 6 GB seems fairly excessive for my graph object, considering that it "only" has about 1.6 million nodes and 2.4 million edges, and its XML representation is about 300 MB.

**Comment by rossbar** [comment] 2022-08-09 10:43
IIUC you *do* see the problems with e.g. `dask` and `ray`, but *don't* have problems when using `multiprocessing.pool`, did I get that right?

I don't have any particularly solid ideas as to why this would be the case. However, one thing that comes to mind that is at least easy to check is whether this might be the result of a bad reaction with an underlying library, such as OpenMP. This shows up every now and then when using e.g. BLAS on HPC. If your `analyze` function *only* contains calls to NetworkX functions then it's difficult to see how this would be the case, unless `dask.compute` is using OpenMP under the hood.

Anyways, the simple thing to try would be to manually suppress threading by setting the `OMP_NUM_THREADS=1` environment variable. This of course likely won't solve your problem (as you want to parallelize the computation), but may be useful for diagnostic purposes. If it is simple for you to do so, can you try this and see if there is any difference in the "hanging" before the computation starts with your 6+ GB input?

**Comment by MridulS** [comment] 2022-08-09 11:00
There doesn't seem to much detail here about what and how this is failing. Could you turn on logging in the dask cluster to get some more information here? It does seem like the all the processes will try to read the same graph object and that seems to be causing the issue. Dask doesn't really play well with global state (from what I remember) and in the code provided the graph object `G` is in the global state. One other thing you can try is to wrap the graph object with a delayed call to make it "dask aware" https://docs.dask.org/en/stable/delayed-best-practices.html#avoid-repeatedly-putting-large-inputs-into-delayed-calls and then pass that around to dask for computation

> It may also be worth noting that 6 GB seems fairly excessive for my graph object, considering that it "only" has about 1.6 million nodes and 2.4 million edges, and its XML representation is about 300 MB.

It's not excessive as the graph data structure also holds a lot of empty dictionaries if you haven't put in edge attributes. One way of decreasing the memory usage is to use something like `ThinGraph` (search for it in the [documentation here](https://networkx.org/documentation/latest/reference/classes/graph.html)).

**Comment by SultanOrazbayev** [comment] 2022-08-09 15:34
Does your `analyze` function refer to `G`? If so, it might help to create a delayed version of G and pass it explicitly to the function, which should help as I suspect that passing around this large object is bottlenecking the execution (given what you described with long pauses between observed actions). Roughly:

```python
G = dask.delayed(G)

def analyze(n, G=G):
   ...
```

**Comment by SultanOrazbayev** [comment] 2022-08-09 15:37
>  for departureNode in G.nodes:

Also, if you are running this on every node in the graph that has 1+ mln nodes, you will overwhelm the dask scheduler (based on my experience it used to struggle with too many tasks), so you might want to execute a batch of 100-1K nodes at a time (something to fine-tune based on the experience).

**Comment by paciorek** [comment] 2022-08-09 21:17
Thanks for the suggestions. Setting `OMP_NUM_THREADS` to 1, using`dask.delayed` on the graph object, and using a small number of tasks don't resolve the problem.

Here's a reproducible example that illustrates the problem. Even though the function being called does essentially nothing, it takes 10s of seconds for the output of the print statements to be shown and for the tasks to finish. If anyone has suggestions as to how best to log what Dask is doing, please let us know. 

```
import pandas as pd
import numpy as np
import networkx as nx

import dask
import dask.multiprocessing

## graphSeason.xml is available from:
## https://www.stat.berkeley.edu/~paciorek/transfer/graphSeason.xml
## G = nx.read_gexf('graphSeason.xml')

import urllib.request
import io

url = 'https://www.stat.berkeley.edu/~paciorek/transfer/graphSeason.xml'
req = urllib.request.Request(url)
with urllib.request.urlopen(req) as resp:
    G = nx.read_gexf(io.BytesIO(resp.read()))


## Dummy function that uses G but without any real computation
def analyze(departureNode, GG):
    print(departureNode, flush = True)
    return(GG.name)

dask.config.set(scheduler = 'processes', num_workers = 4)

G = dask.delayed(G)

## Set up a small number of tasks
futures = []
for departureNode in range(12):
        futures.append(dask.delayed(analyze)(departureNode, G))

## This takes a long time for the print statement output to be shown.
results = dask.compute(futures)
```

**Comment by ischmidt20** [comment] 2022-08-09 21:51
> IIUC you do see the problems with e.g. `dask` and `ray`, but don't have problems when using `multiprocessing.pool`, did I get that right?

Correct!

> It's not excessive as the graph data structure also holds a lot of empty dictionaries if you haven't put in edge attributes.

Thanks for the explanation, the edges do have weight attributes, but the nodes have nothing more than the label. I'll look into `ThinGraph` for the future!

> Also, if you are running this on every node in the graph that has 1+ mln nodes, you will overwhelm the dask scheduler (based on my experience it used to struggle with too many tasks), so you might want to execute a batch of 100-1K nodes at a time (something to fine-tune based on the experience).

The computation is only performed on a subset of the nodes, which is about 90K in this case, and it doesn't appear that reducing that number changes the behavior.

**Comment by SultanOrazbayev** [comment] 2022-08-10 03:28
After experimenting locally with the actual file, I am confident that the issue is caused by passing around a fairly large object (graph). Below is a snippet using `future` API:

```python
from distributed import Client

from networkx import read_gexf

# !wget --no-check-certificate https://www.stat.berkeley.edu/~paciorek/transfer/graphSeason.xml
G = read_gexf("graphSeason.xml")

## Dummy function that uses G but without any real computation
def analyze(departureNode, GG):
    print(departureNode, flush=True)
    return GG.name


# instantiate the client (can open the link to view computations)
c = Client()
print(c.dashboard_link)

# make sure every worker has a copy of the graph, note the loading speed
GG = c.scatter(G, broadcast=True)

# submit tasks and compute on the fly, if the tasks are tiny, it's better to
# chunk them
futs = []
for n in range(12):
    f = c.submit(analyze, n, GG)
    futs.append(f)

# collect the final results
res = c.gather(futs)
```

**Comment by MridulS** [comment] 2023-12-05 10:47
I'll go ahead and close this as we don't really have anything particularly actionable from networkx side. Thanks for opening the discussion @ischmidt20 !

**Closed by MridulS** 2023-12-05 10:47 UTC
Labels: Question
