### ISSUE TITLE
TestKatzCentralityDirectedNumpy tests fail

### ISSUE THREAD

**Issue by mcepl** [networkx/networkx#4030] opened 2020-06-29 14:41 UTC
With networkx-2.4 and Python 3.8, I get these errors:
```
[   24s] + py.test-3.8 --ignore=_build.python2 --ignore=_build.python3 --ignore=_build.pypy3 -v -n auto
[   25s] ============================= test session starts ==============================
[   25s] platform linux -- Python 3.8.3, pytest-5.4.3, py-1.8.1, pluggy-0.13.1 -- /usr/bin/python3

[ many PASSED tests ignored ]

[  197s] =================================== FAILURES ===================================
[  197s] _______ TestKatzCentralityDirectedNumpy.test_katz_centrality_unweighted ________
[  197s] [gw5] linux -- Python 3.8.3 /usr/bin/python3
[  197s] 
[  197s] self = <networkx.algorithms.centrality.tests.test_katz_centrality.TestKatzCentralityDirectedNumpy object at 0xe611c430>
[  197s] 
[  197s]     def test_katz_centrality_unweighted(self):
[  197s] >       H = self.H
[  197s] E       AttributeError: 'TestKatzCentralityDirectedNumpy' object has no attribute 'H'
[  197s] 
[  197s] networkx/algorithms/centrality/tests/test_katz_centrality.py:287: AttributeError
[  197s] ________ TestKatzCentralityDirectedNumpy.test_katz_centrality_weighted _________
[  197s] [gw4] linux -- Python 3.8.3 /usr/bin/python3
[  197s] 
[  197s] self = <networkx.algorithms.centrality.tests.test_katz_centrality.TestKatzCentralityDirectedNumpy object at 0xe50885f8>
[  197s] 
[  197s]     def test_katz_centrality_weighted(self):
[  197s] >       G = self.G
[  197s] E       AttributeError: 'TestKatzCentralityDirectedNumpy' object has no attribute 'G'
[  197s] 
[  197s] networkx/algorithms/centrality/tests/test_katz_centrality.py:280: AttributeError
```

[Complete build log with all details](https://github.com/networkx/networkx/files/4846177/_log.txt)

**Comment by jarrodmillman** [comment] 2020-07-07 20:07
It looks like there is a problem with using ``pytest-xdist``.  Remove ``-n auto`` and your tests should pass.

**Comment by jarrodmillman** [comment] 2020-07-07 20:21
@rossbar Have you used ``pytest-xdist``?  Do you have any idea what is happening here?  It seems like when using ``pytest-xdist``, ``TestKatzCentralityDirectedNumpy`` is not inheriting the setup.

**Comment by rossbar** [comment] 2020-07-07 20:23
Hmm, no I'm not familiar with `pytest-xdist` so at first glance the problem is not obvious to me. I'd have to look at it more closely.

**Comment by mcepl** [comment] 2020-07-07 20:34
Yes, it is true: without `-n auto` tests pass.

**Comment by jarrodmillman** [comment] 2020-07-07 20:48
> Hmm, no I'm not familiar with `pytest-xdist` so at first glance the problem is not obvious to me. I'd have to look at it more closely.

It wasn't obvious to me what the issue was either.  It could be a bug in ``pytest-xdist``.  I am closing this issue, since at worse we have a bug in our test suite that causes an issue when you use a ``pytest-xdist``.

**Closed by jarrodmillman** 2020-07-07 20:48 UTC
