### ISSUE TITLE
Feature: adding a testing module to NetworkX.

### ISSUE THREAD

**Issue by LukasMoll** [networkx/networkx#6392] opened 2023-01-24 12:43 UTC
### Current Behavior

We currently have graph_equal. 
When used in assertion this doesn't provide options like wether to include the graph date.
It doesn't provide feedback.

### Expected Behavior

We would like to have a testing module similar to Pandas and Numpy.
You'd have options wether to compare data, nodes, edges etc.
We would also like to get detailed feedback when the assertion fails.

**Comment by LukasMoll** [comment] 2023-01-24 12:43
I can work on this.

**Comment by MridulS** [comment] 2023-01-24 13:49
@LukasMoll could you give an example what do you mean by this testing module? What exactly do you want to test?

**Comment by LukasMoll** [comment] 2023-01-24 15:02
@MridulS 

[Here](https://pandas.pydata.org/docs/reference/api/pandas.testing.assert_frame_equal.html) is an example from a pandas. an assertion that works with DataFrames.
[Here](https://github.com/pandas-dev/pandas/tree/v1.5.3/pandas/_testing) is the testing module from pandas.

A testing module would be a collection of various functions like the above that we could reuse in tests. It'll be mostly asserters.
I'd like to be able to assert a nx.DiGraph, nx.Graph, nx.nodes etc.. All objects that I might want to assert with their own unique assertion function.

**Comment by MridulS** [comment] 2023-01-24 17:06
> I'd like to be able to assert a nx.DiGraph, nx.Graph, nx.nodes etc.. All objects that I might want to assert with their own unique assertion function.

I don't think this translates that well to graphs. Maybe you are looking for graph isomorphism? Could you please give a concrete example where `graph_equal` fails?

**Comment by rossbar** [comment] 2023-01-24 17:19
I'm -1 on adding an explicit testing module. Adding "helper functions" to check graph attributes during testing is an unnecessary indirection that makes tests harder to read. Using assert statements directly is both correct and more flexible.

As a matter of fact, NetworkX used to have a dedicated testing module, but it was deprecated and removed - see #5782. I don't think there's any appetite to re-introduce it.

**Comment by LukasMoll** [comment] 2023-01-24 17:40
@MridulS graph_equal doesn't provide feedback or arguments to it, we might only want to assert the graph nodes and edges. You could write multiple assert statements for this but having one `assert_graph_equal` for this is very clean IMO. I can open a small PR for this and post a few examples of before and after if you want.

Don't think graph isomorphism is necessary if you have an expected output in test cases.

<img width="772" alt="Screenshot 2023-01-24 at 18 37 50" src="https://user-images.githubusercontent.com/86722560/214366881-c949787d-40b2-4b49-9489-75a7bc9cd1f9.png">
In this very simple example the test fails but we don't really know why. That's why we need a testing module with asserters.

**Comment by LukasMoll** [comment] 2023-01-24 17:46
@rossbar Big libraries like Pandas, Numpy etc. all have their own testing module. Why shouldn't we? The testing module will make it a lot easier to practice things like TDD.

From what I can see the old testing module is basically calling assert `graph_equal(graph1, graph2)` and nothing extra. I plan to introduce extra arguments where you can chose what specifically you want to assert e.g. nodes, edges, data etc. and when the test fails you'll get a traceback with the exact differences between the 2 graphs.

I have appetite :).

**Comment by MridulS** [comment] 2023-01-24 18:57
> Why shouldn't we?

Adding new things is nice but the problem is maintenance. Every new line of code put in needs to be checked/maintained until it's removed/deprecated. We should avoid adding new bits to the API if they can just be one liners in Python. We really need a compelling reason to expand the API surface of networkx :)

There are a lot of ways users can write these assert statements in one liners, anything specific that you would like to expose that isn't already covered by these examples? We definitely wouldn't want to add too custom of testing code.
``` python
# To compare nodes
>>> G.nodes == H.nodes

# To compare nodes with attributes
>>> G.nodes.data() == H.nodes.data()

# To compare specific attribute
>>> G.nodes.data('attribute') == H.nodes.data('attribute')
```

All of this can also be used for edges.

**Comment by LukasMoll** [comment] 2023-01-24 19:18
You'd have the same assertion statement basically everywhere in your tests. It's cleaner to have a function replace that stuff/encapsulate it to ensure that it is all the same and works everywhere.

```
def test1():
...
assert G.nodes == H.nodes, "insert custom failure message here."
assert G.edges == H.edges, "insert custom failure message here."

def test2():
...
assert G.nodes == H.nodes, "insert custom failure message here."
assert G.edges == H.edges, "insert custom failure message here."

def test3():
...
assert G.nodes.data() == H.nodes.data(), "insert custom failure message here."
assert G.edges.data() == H.edges.data(), "insert custom failure message here."
assert G.adj == H.adj, "insert custom failure message here."
```

```
def test1():
...
assert_graphs_equal(G, H)

def test2():
...
assert_graphs_equal(G, H)

def test3():
...
assert_graphs_equal(G, H, node_data=True, edge_data=True)
```

**Comment by MridulS** [comment] 2023-01-25 05:06
All of these things can exist inside the user codebase, not necessarily inside networkx.

We already provide some basic function like `edges_equal`, `nodes_equal`: https://networkx.org/documentation/latest/reference/utils.html

I'm not too excited about adding these things to networkx but if someone else would like to push for this I'm okay with that.

**Comment by LukasMoll** [comment] 2023-01-29 09:21
What features are you interested in? Or is this project in maintenance mode?

**Comment by MridulS** [comment] 2023-01-29 13:42
> What features are you interested in? 

Just my personal list:

- Review old pull requests
- Speed up current implementations
- Fixup code in the `draw` subpackage
- Add new algorithms

There are a LOT of things that can be done here.

I'll go ahead and close this issue for now, feel free to open a new issue/discussion if there is anything else you are interested in contributing :)

**Closed by MridulS** 2023-01-29 13:42 UTC
