### ISSUE TITLE
contracted_nodes with weights giving different answers according to order of inputs

### ISSUE THREAD

**Issue by TheShadow29** [networkx/networkx#2470] opened 2017-06-13 17:37 UTC
I am trying to use contracted nodes for a graph with weights. Here is the code : 
```
import networkx as nx
G = nx.Graph()
G.add_edge(1,3,weight=0.5)
G.add_edge(1,5,weight=0.5)
G.add_edge(1,7,weight=0.5)
G.add_edge(0,2,weight=0.7)
G.add_edge(0,4,weight=0.7)
G.add_edge(0,6,weight=0.7)
G.add_edge(1,6,weight=0.6)
M = nx.contracted_nodes(G,1,0)
N = nx.contracted_nodes(G,0,1)
G.edges(data=True)
M.edges(data=True)
N.edges(data=True)
```
Here is the output:
![screenshot from 2017-06-13 10-36-04](https://user-images.githubusercontent.com/10602903/27095888-21715c0e-5024-11e7-85e0-b66c7ddc8fc7.png)
The thing is after the contraction the new weight depends upon the order of contraction, and I feel that shouldn't be the case. It should be either the maximum or minimum of the two or perhaps an average.

**Comment by dschult** [comment] 2017-06-14 03:22
The behavior of edge weights under contraction of the nodes is not universally agreed upon. And not as well specified in the documentation as it could be. When you contract two nodes the second node copies its edges to the first node. All the edge data also gets copied. So if they shared any common neighbors and those two edges have the same edge data attribute, the new edge to that common neighbor has the edge data attribute value of the edge from the newly deleted node to that neighbor. 

I haven't played with this to see how it would work, but I think if you start with a multigraph and then contract two nodes, any common neighbors now have two edges from the new node to that neighbor. You could then compute the edge value you would want for that new edge. 

The problem is that it is not defined what to do with edge data when you contract two nodes. It is likely to be different for different use cases. You could copy the code for the contract_nodes function.  It is pretty short and quite readable. It is likely that you could make it do what you want it to do.  If that is better than what we have think about justifying why it is better and submit a pull request to help us improve that function.

**Comment by TheShadow29** [comment] 2017-06-14 16:56
Sure, I will look into this.

**Comment by TheShadow29** [comment] 2017-06-20 14:58
To anyone else who needs a similar functionality, here is the code I wrote. I have written only for undirected graphs but it shouldn't be tough to extend to directed graphs. Also I am not considering self-loops here. The code might be a bit sub-optimal but here it goes.
```
def contracted_nodes(G, u, v, self_loops=True):
    """Returns the graph that results from contracting `u` and `v`.
    Node contraction identifies the two nodes as a single node incident to any
    edge that was incident to the original two nodes.
    Parameters
    ----------
    G : NetworkX graph
       The graph whose nodes will be contracted.
    u, v : nodes
       Must be nodes in `G`.
    self_loops : Boolean
       If this is True, any edges joining `u` and `v` in `G` become
       self-loops on the new node in the returned graph.
    Returns
    -------
    Networkx graph
       A new graph object of the same type as `G` (leaving `G` unmodified)
       with `u` and `v` identified in a single node. The right node `v`
       will be merged into the node `u`, so only `u` will appear in the
       returned graph.
    Examples
    --------
    Contracting two nonadjacent nodes of the cycle graph on four nodes `C_4`
    yields the path graph (ignoring parallel edges)::
        >>> import networkx as nx
        >>> G = nx.cycle_graph(4)
        >>> M = nx.contracted_nodes(G, 1, 3)
        >>> P3 = nx.path_graph(3)
        >>> nx.is_isomorphic(M, P3)
        True
    See also
    --------
    contracted_edge
    quotient_graph
    Notes
    -----
    This function is also available as `identified_nodes`.
    """

    H = G.copy()
    if H.is_directed():
        in_edges = ((w, u, d) for w, x, d in G.in_edges(v, data=True)
                    if self_loops or w != u)
        out_edges = ((u, w, d) for x, w, d in G.out_edges(v, data=True)
                     if self_loops or w != u)
        new_edges = chain(in_edges, out_edges)
    else:
        # new_edges = ((u, w, d) for x, w, d in G.edges(v, data=True)
        #              if self_loops or w != u)
        # new_edges = ((u, w, d) for x, w, d in G.edges(v, data=True)
        # if self_loops or w != u)
        new_edges = list()
        nodes_u = [w for x, w in G.edges(u)]
        for x, w, d in G.edges(v, data=True):
            if w != u:
                if w not in nodes_u:
                    new_edges.append((u, w, d))
                else:
                    max_d = max(d, G[u][w])
                    new_edges.append((u, w, max_d))
    v_data = H.node[v]
    pdb.set_trace()
    H.remove_node(v)
    H.add_edges_from(new_edges)
    if 'contraction' in H.node[u]:
        H.node[u]['contraction'][v] = v_data
    else:
        H.node[u]['contraction'] = {v: v_data}
    return H

```

**Comment by dschult** [comment] 2017-06-26 21:24
Be careful here with ```data=True```.  That makes the edge return a dict. So your ```max_d = max(d, G[u][w])``` may not be calculating what you want. It compares dicts not weights. Try something like this:

    nodes_u = G[u]
    for w, dd in G[v].items():
        d = dd.get('weight', 1)
        if w not in nodes_u:
            new_edges.append((u, w, d))
        else:
            max_d = max(d, G[u][w]['weight']) 
            new_edges.append((u, w, max_d))

**Comment by TheShadow29** [comment] 2017-06-26 22:39
Oh, I made quite the terrible mistake. Thanks for pointing that out. @dschult

**Comment by dschult** [comment] 2017-07-08 23:24
For anyone who has ideas about a better way to handle the node/edge data when contracting nodes please feel free to post to this issue or to open a new one.  I'm going to close this as I don't see an obvious way forward with it

**Closed by dschult** 2017-07-08 23:24 UTC
