### ISSUE TITLE
Error in `random_state` decorator with decorator 5.0.0 version

### ISSUE THREAD

**Issue by ivkireev86** [networkx/networkx#4718] opened 2021-04-02 09:23 UTC
### Current Behavior
```
Traceback (most recent call last):
  File "./env/lib/python3.8/site-packages/networkx/utils/decorators.py", line 396, in _random_state
    random_state_arg = args[random_state_index]
IndexError: tuple index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt2/kireev/pycharm-deploy/pytorch-stream-graph/notebooks/ppp.py", line 12, in <module>
    pos = nx.drawing.random_layout(G)
  File "./env/lib/python3.8/site-packages/decorator.py", line 214, in fun
    return caller(func, *(extras + args), **kw)
  File "./env/lib/python3.8/site-packages/networkx/utils/decorators.py", line 400, in _random_state
    raise nx.NetworkXError("random_state_index is incorrect") from e
networkx.exception.NetworkXError: random_state_index is incorrect
``` 

### Expected Behavior
Work without errors

### Steps to Reproduce
Code example for this issue:
```
import networkx as nx

G = nx.Graph()
G.add_nodes_from([0, 1, 2, 3])
G.add_edges_from([
    (0, 1),
    (1, 2),
    (2, 3),
    (1, 3),
])

pos = nx.drawing.random_layout(G)
print(pos)
```

### Environment

Python version: 3.8.0
NetworkX version: 2.5
decorator version: 5.0.0

### Additional context

All functions decorated by `random_state` don't works.
Broken after decorator module update.
Works well with decorator==4.4.2

**Comment by fgrunewald** [comment] 2021-04-02 10:20
I get the same error regardless of the version of networkx as long as it installs decorator version 5.0.0 with it. Any decorator version <5.0.0 are fine for me.

**Comment by LexTek** [comment] 2021-04-02 12:29
I have the same issue using algorithms.tree.branchings :
```python
ed = nx.algorithms.tree.branchings.Edmonds(dep)
```

I don't specify the optional seed parameter that seems to be linked to random_state_index in some way.

I get this error : 
```
  File "/builds/fernandez/gran-turismo/data/Graph.py", line 424, in pat
    ed = nx.algorithms.tree.branchings.Edmonds(dep)
  File "/usr/local/lib/python3.9/site-packages/networkx/algorithms/tree/branchings.py", line 272, in __init__
    self.template = random_string(seed=seed) + '_{0}'
  File "/usr/local/lib/python3.9/site-packages/decorator.py", line 214, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.9/site-packages/networkx/utils/decorators.py", line 456, in _random_state
    raise nx.NetworkXError("random_state_index is incorrect")
networkx.exception.NetworkXError: random_state_index is incorrect
```

**Comment by dschult** [comment] 2021-04-02 13:17
The latest decorator version is now listed as 5.0.1 on PyPi so I don't think you will have to worry about 5.0.0 for very long.
Just hold on for a couple of hours and it should all go away. :}

**Comment by dschult** [comment] 2021-04-03 14:36
It looks like this change in behavior will not be fixed by a future release -- that is, it is a change in the API for `decorator`.
We are working on a fix. In the meantime pin decorator to <5.

**Comment by njzjz** [comment] 2021-04-03 20:14
Will networkx release a patch for `v2.5` to pin the version?

**Comment by rossbar** [comment] 2021-04-03 21:54
> Will networkx release a patch for v2.5 to pin the version?

Yes, we're working on a 2.5 patch to pin the decorator version now.

**Comment by jarrodmillman** [comment] 2021-04-03 23:05
I released NetworkX 2.5.1:
- https://pypi.org/project/networkx/2.5.1/

I also asked the folks at conda-forge to update as well:
- https://github.com/conda-forge/networkx-feedstock/issues/21

**Comment by jarrodmillman** [comment] 2021-04-04 04:00
Updated to 2.5.1 here:
https://github.com/conda-forge/networkx-feedstock

**Comment by dschult** [comment] 2021-04-04 13:36
Decorator v5.0.5 has been fixed.  It now provides the v4 behavior by default and allows the new behavior with an optional flag argument. We should be able to use v5 now.

**Comment by garibarba** [comment] 2021-04-13 09:25
It works for me with decorator 5.0.5, but it is broken again with 5.0.6 .

**Comment by dschult** [comment] 2021-04-13 12:39
I can verify that decorator is broken again in 5.0.6

**Comment by dschult** [comment] 2021-04-14 12:45
This is now working with decorator 5.0.7

**Comment by rossbar** [comment] 2021-05-19 16:33
`decorator` now includes a test (see micheles/decorator#121) that should prevent the behavior from breaking in future patch releases, so the version pinning (#4773, #4815) should be sufficient to keep this issue closed for both the development branch and stable releases moving forward.

**Closed by rossbar** 2021-05-19 16:33 UTC

**Comment by DataStrategist** [comment] 2021-06-18 10:52
Still seeing the issue in python3.8 with decorator 5.0.6 in a secure Ubuntu VM. Screenshots follow (sorry can't post as text cause secure platform doesn't allow that):
![image](https://user-images.githubusercontent.com/8094091/122550377-79c42180-d02b-11eb-8a55-6395ebe2b355.png)
![image](https://user-images.githubusercontent.com/8094091/122550460-96605980-d02b-11eb-9a57-f76e1957f7d2.png)

**Comment by rossbar** [comment] 2021-06-18 11:19
See [the above comment](https://github.com/networkx/networkx/issues/4718#issuecomment-819489576) - decorator 5.0.6 is known not to work, it needs to be 5.0.7 or later.

This has caused a lot of problems, so we are hoping to remove the decorator dependency entirely in the next release.

**Comment by DataStrategist** [comment] 2021-06-18 13:07
Sorry... I exactly read that wrong! Doh! I force-installed 5.0.9 and confirm it's fine.

**Comment by GoingMyWay** [comment] 2021-08-01 11:02
Same issue with the newest networkx.

**Comment by RaghavKhandelwal31** [comment] 2021-08-04 08:41
Hi! I was working with NetworkX for the 1st time by following a tutorial and got this error. Can someone please tell me how to change the decorator version to the one that works.

**Comment by KHBAAW** [comment] 2021-09-14 05:36
I have same problem Random state index is incorrect 
how to resolve it 
![Screenshot (2)](https://user-images.githubusercontent.com/68842470/133200924-dc72fe9a-05e1-429e-89b0-95b9dec9ef45.png)

**Comment by MridulS** [comment] 2021-09-14 07:50
@KHBAAW Please update your networkx installation or your decorator installation to the latest versions.

**Comment by KHBAAW** [comment] 2021-09-14 08:16
Error while updating the decorator 

![Screenshot (4)](https://user-images.githubusercontent.com/68842470/133221506-744f6e02-7222-45f4-903f-0ff08aa40989.png)

**Comment by MridulS** [comment] 2021-09-14 08:24
Could you try deleting networkx and then reinstalling it? Maybe it will solve the dependencies issues as newer versions of networkx don't depend on decorator.

**Comment by KHBAAW** [comment] 2021-09-14 09:21
No, I did not delete it

**Comment by dschult** [comment] 2021-09-14 13:08
Try deleting both decorator and networkx and then reinstall it to get the latest version.
You should probably also be using the anaconda channel "conda-forge" (seems to behave better).

**Comment by c3-premjithbalakrishnan** [comment] 2021-09-14 17:36
Thank you, dschult. Removing networkx and decorator and then reinstalling them is what worked for me. 

Just trying to upgrade decorator ran into some complex package dependency check and kept failing.

**Comment by atiyabzafar** [comment] 2021-09-17 06:00
Hey, I am a TA in a course on network science that is being taught and some of the students are facing the exact same error with nx.draw(). The error seems to be in the random_state decorator only. I am wondering if someone can mention this to folks at conda and make sure the dependencies are met already. 
`IndexError                                Traceback (most recent call last)

~\anaconda3\lib\site-packages\networkx\utils\decorators.py in _random_state(func, *args, **kwargs)
    395         try:
--> 396             random_state_arg = args[random_state_index]
    397         except TypeError as e:

IndexError: tuple index out of range
`
I will try to work around this issue and let them know the appropriate steps, but it sometimes is difficult for kids who aren't very proficient in solving such problems to deal with dependencies problems.

**Comment by dschult** [comment] 2021-09-17 12:37
The random_state decorator error does not look like the same error as this Issue. That is, I do not believe it is due to having a specific version of the decorator library.  Have you determined that it *can* be fixed by changing the version of the decorator library?

If the decorator library version has not been determined to fix this error, can you open a new issue with more details about what versions of networkx and Python you are using, and maybe a short example of code that reproduces the error?

**Comment by atiyabzafar** [comment] 2021-09-17 12:43
Yes, I was planning to do the same. will do the same later today and get back to this forum. I have encountered this same error in 3 different machines in the last couple of days on fresh install of Anaconda Individual edition.

**Comment by dschult** [comment] 2021-09-17 12:48
Ahh.. so it is repeatable --- but what is it that they were doing? :}

**Comment by MridulS** [comment] 2021-09-17 13:28
> fresh install of Anaconda Individual edition

This could be the issue, as the Anaconda distribution could have pinned to a previous release by default instead of the latest one.
Could you confirm the version of networkx and decorator after a fresh install?

Something like
```python
In [1]: import networkx as nx

In [2]: nx.__version__
Out[2]: 'X.X.X'

In [3]: import decorator

In [4]: decorator.__version__
Out[4]: 'X.X.X'
```

**Comment by atiyabzafar** [comment] 2021-09-17 13:45
@MridulS Yeah It is definitely due to Fresh conda install pinning the modules.
Networkx and Decorator versions are as mentioned below
```
2.5
5.0.6
```
Conda is not letting me update the version as well.

```
(base) C:\Users\username> conda update decorator
Collecting package metadata (current_repodata.json): done
Solving environment: /

Updating decorator is constricted by

- anaconda -> requires decorator==5.0.6=pyhd3eb1b0_0

If you are sure you want an update of your package either try `conda update --all` or install a specific version of the package you want using `conda install <pkg>=<version> 
```

Same issue with updating networkx obviously. 

I removed networkx (this removes a lot of dependent packages including numpy, pandas,etc) And then installed networkx again this time to 2.6.2. And then it worked well. 

If anyone wants to recreate. You can simply do a fresh install of Anaconda (Used windows for all 4 recreations).

Use this code to get the error:

```
G=nx.Graph()
nodes=[1,2,3,4,5]
edges=[(1,2),(3,4),(4,5),(2,3),(5,1)]
G.add_nodes_from(nodes)
G.add_edges_from(edges)
nx.draw(G,with_labels=True)
plt.show()

```


```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\anaconda3\lib\site-packages\networkx\utils\decorators.py in _random_state(func, *args, **kwargs)
    395         try:
--> 396             random_state_arg = args[random_state_index]
    397         except TypeError as e:

IndexError: tuple index out of range

The above exception was the direct cause of the following exception:

NetworkXError                             Traceback (most recent call last)
<ipython-input-5-f21a0ac2d507> in <module>
      4 G.add_nodes_from(nodes)
      5 G.add_edges_from(edges)
----> 6 nx.draw(G,with_labels=True)
      7 plt.show()

~\anaconda3\lib\site-packages\networkx\drawing\nx_pylab.py in draw(G, pos, ax, **kwds)
    121         kwds["with_labels"] = "labels" in kwds
    122 
--> 123     draw_networkx(G, pos=pos, ax=ax, **kwds)
    124     ax.set_axis_off()
    125     plt.draw_if_interactive()

~\anaconda3\lib\site-packages\networkx\drawing\nx_pylab.py in draw_networkx(G, pos, arrows, with_labels, **kwds)
    331 
    332     if pos is None:
--> 333         pos = nx.drawing.spring_layout(G)  # default to spring layout
    334 
    335     draw_networkx_nodes(G, pos, **node_kwds)

~\anaconda3\lib\site-packages\decorator.py in fun(*args, **kw)
    229             if not kwsyntax:
    230                 args, kw = fix(args, kw, sig)
--> 231             return caller(func, *(extras + args), **kw)
    232     fun.__name__ = func.__name__
    233     fun.__doc__ = func.__doc__

~\anaconda3\lib\site-packages\networkx\utils\decorators.py in _random_state(func, *args, **kwargs)
    398             raise nx.NetworkXError("random_state_index must be an integer") from e
    399         except IndexError as e:
--> 400             raise nx.NetworkXError("random_state_index is incorrect") from e
    401 
    402         # Create a numpy.random.RandomState instance

NetworkXError: random_state_index is incorrect
```

**Comment by atiyabzafar** [comment] 2021-09-18 02:26
Commenting for anyone who face this problem. 

This is an issue with conda freezing the versions of packages. 

Safest way to handle this is

`conda update --all`

This solves the environment and updates most of the packages that conda can update to latest stable release without breaking the environment . 

No need to open another issue for this. I guess people at anaconda will update this in later releases.
