### ISSUE TITLE
from_pandas_edgelist does not create weighted graphs despite providing weight column in edge_attrs

### ISSUE THREAD

**Issue by ajmal92** [networkx/networkx#5248] opened 2022-01-07 13:04 UTC
I am using snowflake as my data source. I fetched the contents of a table and wanted to build a directed weighted graph based on the contents of different columns in snowflake table. 
Using snowflake connector in python, I was able to fetch the contents of the table as a data frame using  
```
import snowflake.connector
ctx = snowflake.connector.connect(
    user=username,
    password=password,
    account=server
)

cs = ctx.cursor()
G=nx.DiGraph()
query = 'select col1, col2, weight from dbo.table '
cs.execute(query)

data_frame = cs.fetch_pandas_all().
```
I am now trying to provide the data frame as input to 
`from_pandas_edgelist(data_frame, source= 'col1', target = 'col2', edge_attr=True, create_using = G)`

Now, after this when I check the graph object created is weighted or not, it returns `False`. 

`nx.is_weighted(G)
`
How do we provide weights to the edges in from_pandas_edgelist method?

**Environment**
Python version : 3.8.10
Network x : 2.6.3

**Comment by MridulS** [comment] 2022-01-07 14:00
Can you look at the output of `data_frame`? I am not able to reproduce this.

Does it matches a schema like this?
``` python
In [1]: import pandas as pd

In [2]: df = pd.DataFrame({'col1': [0, 1], 'col2':[3, 0], 'weight': [0.1, 3.4]})

In [3]: df
Out[3]:
   col1  col2  weight
0     0     3     0.1
1     1     0     3.4
```

Running the minimal example below seems to work for me.

``` python
In [1]: import networkx as nx

In [2]: import pandas as pd

In [3]: df = pd.DataFrame({'col1': [0, 1], 'col2':[3, 0], 'weight': [0.1, 3.4]})

In [4]: G = nx.DiGraph()

In [5]: nx.from_pandas_edgelist(df, source= 'col1', target = 'col2', edge_attr=True, create_using = G)
Out[5]: <networkx.classes.digraph.DiGraph at 0x108504940>

In [6]: nx.is_weighted(G)
Out[6]: True

In [7]: G.edges.data()
Out[7]: OutEdgeDataView([(0, 3, {'weight': 0.1}), (1, 0, {'weight': 3.4})])
```

**Comment by ajmal92** [comment] 2022-01-10 02:10
```
print(dataframe)

COL1 COL2 COL3  COL4    WEIGHT


[830188 rows x 5 columns]
```

**Comment by MridulS** [comment] 2022-01-10 07:59
If this is the output of dataframe it should give you an error while you run `from_pandas_edgelist(data_frame, source= 'col1', target = 'col2', edge_attr=True, create_using = G)` as `col1 != COL1`.

It would be great if you can you give a minimal example where it's failing. Thanks!

**Comment by rossbar** [comment] 2022-02-03 20:45
I'm going to close this as I think there needs to be an MRE to make progress here. If the issues persists, please reopen with an executable example to illustrate the issue.

**Closed by rossbar** 2022-02-03 20:45 UTC
Labels: Question
