### ISSUE TITLE
network_simplex hangs, likely due to floating point precision

### ISSUE THREAD

**Issue by marcovc** [networkx/networkx#4641] opened 2021-02-26 16:13 UTC
Calling network_flow on the below DiGraph runs forever.

```python3
from networkx import DiGraph, network_simplex

sent_vol = {
    ('T1', 'T2'): 0.8818872633908762,
    ('T3', 'T4'): 0.1687976577642258,
    ('T5', 'T3'): 1.033634774231754,
    ('T6', 'T7'): 1.1883270406785664,
    ('T4', 'T8'): 3.5719973907827627,
    ('T4', 'T9'): 1.0,
    ('T4', 'T10'): 0.9880445182987674,
    ('T4', 'T5'): 0.8785895580969909,
    ('T4', 'T6'): 0.25,
    ('T4', 'T11'): 0.6924783869938211
}

d = DiGraph()
d.add_weighted_edges_from((f, t, -1) for f, t in sent_vol.keys())
for ft, vol in sent_vol.items():
    f, t = ft
    d[f][t]['capacity'] = sent_vol[f, t]

r = network_simplex(d)
```

### Environment
Python 3.7.3 (default, Jul 25 2020, 13:03:44) 
[GCC 8.3.0] on linux
NetworkX version: 2.5

### Additional context
It seems removing any of the arcs (even the first that is on its separate connected component!) makes the problem go away.

**Comment by dschult** [comment] 2021-02-26 17:59
What should it return in this case?
Have you been able to shrink the network smaller than this and reproduce the same issue? 

It looks like you are creating edges with negative weight. Is that really what you want?

**Comment by marcovc** [comment] 2021-02-26 18:11
> What should it return in this case?
I don't know what should be returned, just that expected that it returns something and doesn't run forever. I have plenty other instances with different edges/capacities that work fine.

> Have you been able to shrink the network smaller than this and reproduce the same issue?
As said, if I remove one of the edges it works.

> It looks like you are creating edges with negative weight. Is that really what you want?
Yes, I want to maximize, hence the negative weights.

**Comment by dschult** [comment] 2021-02-26 18:18
If I understand correctly the negative weights might be the problem.

To maximize you could try using reciprocal weights (multiplicative inverse) instead of negative weights (additive inverse). I'll look more closely to see whether negative weights should work. 

I'm not surprised that there are (small) cases where this code takes forever to run.
But this is small enough it might be useful to figure out what is causing it to take so long.

**Comment by marcovc** [comment] 2021-02-26 18:22
> To maximize you could try using reciprocal weights (multiplicative inverse) instead of negative weights (additive inverse). I'll look more closely to see whether negative weights should work.

Not sure I understand. I want to maximize the sum of the flows, so my weights are -1. If instead I use the reciprocal of 1, which is 1, that would minimize the sum of the flows, right?

**Comment by dschult** [comment] 2021-03-01 21:12
Yes -- Of course you are right about the reciprocal weights...  I was (and probably still am) confused.

I tried removing each edge and the infinite loop is avoided. (just as you say about removing ('T1', 'T2')).
I tried truncating the edge weights after the 4th decimal place. That also avoided the infinite loop.
Even truncating at the 11th decimal place gets rid of the infinite loop.

(To be clear -- I don't know that it is an infinite loop -- it might just be really long.)

So, this is almost certainly an issue of round-off error in the edge weights. 
To track it down will require tracing the code to see why a stopping condition is not being met.
Based on hitting Cntrl-C midloop it seems to be part of `find_entering_edges` which continually increases m until an entering edge is found -- yields that and resets m to 0.  If it is finding the same edge over and over it would cause this symptom.  Not sure why it would be doing that though...

In other places in the NetworkX code base we have run into problems with using floating point values in edge weights.  It looks like this is another of those places.  A workaround is to replace the edge weights with rounded versions, or (what amounts to the same thing) scaling the weights and rounding them to integers.

In this case: `d[f][t]['capacity'] = round(sent_vol[f, t], 10)` seems to work.

**Comment by marcovc** [comment] 2021-03-02 07:31
Thanks for looking into this @dschult ! It seems like even a small change in input can make the problem go away. I imagine there is some comparison somewhere that needs to use some tolerance. I'll have a look into the code when I have some spare time.

Thanks again!
Marco

**Comment by rossbar** [comment] 2021-03-07 19:24
A quick pdb session seems to indicate that the problem is in `find_entering_edges`, presumably in the construction of the [while loop](https://github.com/networkx/networkx/blob/1de57a8ca852cf27820512720968c6cffb51a74b/networkx/algorithms/flow/networksimplex.py#L313-L337). Specifically, the inputs seem to put this loop in a condition where the reduced cost `c` seesaws between `-0.0` and `0.0` on subsequent iterations, resulting in `m` never dropping below `M`, hence the infinite loop.

On a side note, it doesn't seem that the `network_simplex` function is explicitly tested (the `network_simplex` function is only called internally in some of the tests in `test_mincost`). In addition, `network_simplex` defines quite a few internal functions/generators that are themselves not tested. This module/function seem like great candidate for a refactor to split out some of the nested functions and write unit tests for them.

**Comment by dschult** [comment] 2021-03-14 16:18
The `reduced_cost` function is the culprit.  That's where we should figure out how to use a tolerance.
```python
def reduced_cost(i):
    """Returns the reduced cost of an edge i."""
    c = C[i] - pi[S[i]] + pi[T[i]]
    return c if x[i] == 0 else -c
```
The last line seems to try to avoid this problem with 0 switching to -0. But it isn't enough when edge weights are floats.

**Comment by dschult** [comment] 2021-07-28 22:19
The doc_string for `networkx_simplex` has a note:

```
    This algorithm is not guaranteed to work if edge weights or demands
    are floating point numbers (overflows and roundoff errors can
    cause problems). As a workaround you can use integer numbers by
    multiplying the relevant edge attributes by a convenient
    constant factor (eg 100).
```

I'm inclined to let that warning be enough... users should not using floating point values for edge weights where equality is important. Similarly floating point values are not good choices for nodes.  If we need to check equality using approximation ideas it will potentially add a lot of extra checking to our code. I think this is potentially a problem in just about any function that optimizes any attribute (like weight/capacity/demand).

**Comment by rossbar** [comment] 2023-08-24 16:51
I will go ahead and close this as the issue is documented and there's no (t yet) a workable, general approach to issues related to fp precision.

**Closed by rossbar** 2023-08-24 16:51 UTC
Labels: floating-point, close ?
