### ISSUE TITLE
networkx is unable to save graphs in dot format where node names contain a colon

### ISSUE THREAD

**Issue by josch** [networkx/networkx#2050] opened 2016-03-29 11:21 UTC
Steps to reproduce:

```python
>>> import networkx as nx
>>> G=nx.Graph()
>>> G.add_node("foo:bar")
```

writing out this graph in GraphML format yields the expected result:

```python
>>> print(nx.readwrite.graphml.GraphMLWriter(G))
<graphml xmlns="http://graphml.graphdrawing.org/xmlns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">
  <graph edgedefault="undirected">
    <node id="foo:bar" />
  </graph>
</graphml>
```

but writing the same graph in dot format replaces the node id `foo:bar` by the
node id `foo`:

```python
>>> print(nx.nx_pydot.to_pydot(G).to_string())
strict graph "" {
foo;
}
```

The reason for this is, that the colon in node ids has a special meaning in the
dot format. Namely, the colon in a node name is used to specify input or output
ports. For references see:

http://stackoverflow.com/questions/33722809/
http://stackoverflow.com/questions/31523810/
https://github.com/erocarrera/pydot/issues/38
http://www.graphviz.org/doc/info/attrs.html#k:portPos

A possible fix might be, to surround the node name with quotes if it contains a
colon. Without quotes, pydot will understand the colon as a special character:

```python
>>> import pydot
>>> g = pydot.Dot()
>>> g.add_node(pydot.Node('foo:bar'))
>>> print(g.to_string())
digraph G {
foo;
}
```

If networkx would surround such vertex names with quotes, the problem would
vanish:

```python
>>> import pydot
>>> g = pydot.Dot()
>>> g.add_node(pydot.Node('"foo:bar"'))
>>> print(g.to_string())
digraph G {
"foo:bar";
}
```

Thanks!

**Comment by hagberg** [comment] 2016-03-31 01:30
We could do that. But perhaps the problem is better addressed in pydot (pydotplus)?  

```python
In [7]: import pydotplus

In [8]: P = pydotplus.Graph()

In [9]: P.add_node(pydotplus.Node('foo:bar'))

In [10]: print(P.to_string())
digraph G {
foo;
}
```

Note that this works with pygraphviz
```python
import networkx as nx
G=nx.Graph()
G.add_node("foo:bar")
print(nx.nx_pydot.to_pydot(G).to_string())
print(nx.nx_agraph.to_agraph(G).to_string())```

```
strict graph "" {
foo;
}

strict graph  {
	"foo:bar";
}
```

**Comment by josch** [comment] 2016-03-31 07:32
From the links I gave in my original report you can see, that this is a feature and not a bug. So I don't think that this behaviour will change in pydot/pydotplus in the feature. Instead I think because of this feature it is expected that users of pydot/pydotplus will do the quoting if they need it. But maybe you have a contact with the pydot/pydotplus people to explicitly ask about this :)

As for pygraphviz, at least with my graphs (750 vertices, 7000 edges), pygraphviz is unacceptably slow. Using `nx.nx_pydot.write_dot`:

```
$ python3 -m timeit --verbose --setup "import networkx as nx; g=nx.nx_pydot.read_dot('out.dot')" "nx.nx_pydot.write_dot(g, '/dev/null')"
10 loops -> 14.4 secs
raw times: 13.9 13.7 13.9
10 loops, best of 3: 1.37 sec per loop
```

Using `nx.nx_agraph.write_dot`:

```
$ python3 -m timeit --verbose --setup "import networkx as nx; g=nx.nx_pydot.read_dot('out.dot')" "nx.nx_agraph.write_dot(g, '/dev/null')"
```

The above has now been running for more than an hour and I didn't even get the first print yet...

Thus, I'm relying on pydot/pydotplus for my dot printing needs and thus, having this bug fixed is important for me.

**Comment by hagberg** [comment] 2016-03-31 13:16
I still think this is a pydot/pydotplus bug.  Can't you do a workaround by adding quotes in your node names?
```python
In [14]: G = nx.Graph()

In [15]: G.add_node('"foo:bar"')

In [16]: print nx.nx_pydot.to_pydot(G).to_string()
strict graph "" {
"foo:bar";
}
```

Also you likely have a broken pygraphviz installation.  It should be faster than pydot - for me writing a 750 nodes 7000 edges dot file from networkx is 3-4 times faster with pygraphviz.


```python
In [1]: import networkx as nx

In [2]: G = nx.gnm_random_graph(750,7000)

In [3]: %timeit -n 1 -r 2 nx.nx_pydot.write_dot(G,'foo.dot')
1 loops, best of 2: 2.33 s per loop

In [4]: %timeit -n 1 -r 2 nx.nx_agraph.write_dot(G,'foo.dot')
1 loops, best of 2: 671 ms per loop

In [5]: import pygraphviz

In [6]: pygraphviz.__version__
Out[6]: '1.4.dev'

In [7]: import pydotplus.version

In [8]: pydotplus.version.__version__
Out[8]: u'2.0.2'
```

**Comment by josch** [comment] 2016-03-31 19:18
My software does not only output graphs in dot format. If I create my node ids such that they always contain quotes around them, then these would be printed in the graphml format for example which is not desirable. Manually traversing and changing all node names specifically for the dot output is also an option but if pydot(plus) requires this (as you were able to reproduce) then why doesn't networkx do it for me already? As networkx is just a pydot(plus) wrapper, it seems to me that it would be a good place to take care of such backend-specific behaviour. As the links I posted show, I'm not the only one who is apparently facing this problem. What negative effect would it have if networkx was taking care of this by adding double quotes around node its which contain a colon? Would it brake something?

About pygraphviz: or maybe you are using a version that nobody else is ;) Looking at https://pypi.python.org/pypi/pygraphviz and 
http://pygraphviz.github.io it seems that the latest release is 1.3.1 and that's what I'm using. Can you confirm that you don't see the speed regressions that I see with version 1.3.1?

**Comment by hagberg** [comment] 2016-03-31 20:54
```python
In [3]: import networkx as nx

In [4]:  G = nx.gnm_random_graph(750,7000)    

In [5]: %timeit -n 1 -r 2 nx.nx_pydot.write_dot(G,'foo.dot')   
1 loops, best of 2: 1.28 s per loop

In [6]: %timeit -n 1 -r 2 nx.nx_agraph.write_dot(G,'foo.dot')    
1 loops, best of 2: 548 ms per loop

In [7]: import pygraphviz     

In [8]:  pygraphviz.__version__             
Out[8]: '1.3.1'

In [9]:  import pydotplus.version          

In [10]:  pydotplus.version.__version__
Out[10]: u'2.0.2'
```

**Comment by hagberg** [comment] 2016-03-31 21:05
I'm not enthusiastic about putting in hacks to fix bugs in other packages.  So I'm going to keep advocating for not "fixing" this and encouraging the pydot maintainers to do so instead.  

I've spent quite a lot of time dealing with quotes and special dot string issues:
 - https://github.com/networkx/networkx/issues/1872
 - https://github.com/networkx/networkx/issues/1348
 - https://github.com/networkx/networkx/issues/317
 - https://github.com/networkx/networkx/issues/350
 - https://github.com/networkx/networkx/issues/184

I don't want to break any of that.   

I hope you can make pygraphviz work.  It can handle more complicated files than pydot and in the end might be worth the time to get installed correctly.  E.g. try pydot on https://raw.githubusercontent.com/ellson/graphviz/master/rtest/windows/tree.gv

**Comment by josch** [comment] 2016-04-01 05:52
Okay, then I'll see three options for me here:

 1. add a preprocessing step into my code just before whenever I call `nx.nx_pydot.write_dot` which mangles the node names
 1. make things work with pygraphviz
 1. convince the pydot(plus) maintainers that this behaviour is a bug and let them fix it

As for the last point, I wrote to the pydot and pydotplus maintainers to ask them about their opinion on this matter:

https://github.com/carlos-jenkins/pydotplus/issues/3
https://github.com/erocarrera/pydot/issues/118

Unfortunately, if they claim it's a feature and you keep insisting it's a bug which you will not work around, then we are still at a stalemate...

So for the second point, I'd kindly ask you, to load the following dot graph in networkx with the dot parser of your choice (either trigger the problem) and then try to write it in dot format with `nx.nx_agraph.write_dot`:

https://mister-muffin.de/p/J1fN.txt

If I try this:

```python
>>> import networkx as nx
>>> g = nx.nx_pydot.read_dot('out.dot')
>>> nx.nx_agraph.write_dot(g, '/dev/null')
```

then the command will never finish (at least I gave up after a few hours). The problem is independent of whether the graph is read with `nx.nx_pydot.read_dot` or `nx.nx_agraph.read_dot`.

Can you confirm this effect?

**Comment by hagberg** [comment] 2016-04-01 13:22
There is probably some issue with your pygraphviz install.  Does it run the tests?
`python -c "import pygraphviz; pygraphviz.test()"`


```
$ time python -c "import networkx as nx; G=nx.nx_agraph.read_dot('J1fn.txt');nx.nx_agraph.write_dot(G,'foo.dot')"

real	0m2.087s
user	0m1.390s
sys	0m0.592s
```

**Comment by hagberg** [comment] 2016-04-01 13:25
Also, there is another option for you.  Adjust this line 
https://github.com/networkx/networkx/blob/master/networkx/drawing/nx_pydot.py#L202
in your own copy of the nx_pydot module.

**Comment by josch** [comment] 2016-04-01 13:30
My copy of pygraphviz is its Debian package. The tests run fine:

```
python3 -c "import pygraphviz; pygraphviz.test()"                     ~
Running PyGraphiz tests:....................................................................................
----------------------------------------------------------------------
Ran 84 tests in 0.214s

OK
```

Thanks for testing my graph. I'll have a look whether the package from upstream shows different behaviour than the copy I get from Debian.

Editing my own copy of `nx_pydot.py` is not an option because that would make it work just for me but nobody else.

**Comment by hagberg** [comment] 2016-04-01 13:30
Also I just noticed that running that J1fn.txt file through the graphviz dot layout program causes it to never finish (or at least takes a very long time).  It does process correctly with other layouts (neato, sfdp,...)
That is 
`dot -Txdot J1fN.txt >foo.dot`
isn't working well - that is a graphviz issue.

**Comment by josch** [comment] 2016-04-01 13:32
That is because the graph is a strongly connected component. Thus, it is expected that the dot layout (which tries to order the nodes) will do a very bad job (like being slow). The graphs here are not meant to be visualized (they are too big for that anyways) but used as a machine-readable representation of the underlying data structures.

**Comment by hagberg** [comment] 2016-04-01 13:34
You can distribute your own copy of nx_pydot.py with the rest of your software.

**Comment by hagberg** [comment] 2016-04-01 13:36
In my tests I have been using graphivz-2.36.0 or graphviz-2.38.0 on a Linux system (Ubuntu). Both work for me.

But also OSX
```
$ time python -c "import networkx as nx; G=nx.nx_agraph.read_dot('J1fn.txt');nx.nx_agraph.write_dot(G,'foo.dot')"

real    0m1.030s
user    0m0.961s
sys     0m0.061s
aric:tmp aric$ uname -a
Darwin aric.local 14.5.0 Darwin Kernel Version 14.5.0: Mon Jan 11 18:48:35 PST 2016; root:xnu-2782.50.2~1/RELEASE_X86_64 x86_64
$ dot -V
dot - graphviz version 2.38.0 (20140413.2041)
```

**Comment by josch** [comment] 2016-04-01 13:43
I can distribute my own copy but I choose not to. There are several reasons for not using embedded code copies. By doing so, I basically am creating and have to maintain my own fork, have to merge back all the bug fixes and new features that you make. Carrying 300 lines of duplicate code that I have to maintain if the workaround is just two lines of code, is not worth the extra time I have to then spend maintaining that fork. See here for a more comprehensive list of why I avoid doing this: 
https://wiki.gentoo.org/wiki/Why_not_bundle_dependencies

**Comment by josch** [comment] 2016-04-01 15:23
Thanks to your help, I was able to track down the problem with pygraphviz. It turns out that the Debian version does not contain the fixes made by commits  https://github.com/pygraphviz/pygraphviz/commit/e90c881c8c9ca4bc5e6ecc28eb47e647b54a25a5 and earlier. Specifically, applying the following patch to the Debian version of pygraphviz fixes my issues:

```diff
@@ -948,9 +948,8 @@
 
     def clear(self):
         """Remove all nodes, edges, and attributes from the graph."""
-        self.edge_attr.clear()
-        self.node_attr.clear()
-        self.graph_attr.clear()
+        self.remove_edges_from(self.edges())
+        self.remove_nodes_from(self.nodes())
         # now "close" existing graph and create a new graph
         name = gv.agnameof(self.handle)
         strict = self.strict
```

While this means that I can just switch from using `nx.nx_pydot.write_dot` to `nx.nx_agraph.write_dot`, users of the pydot function will still suffer from this particular problem. You might leave this bug open until you hear back from the pydot maintainers on their stance on the node id colon issue.

**Closed** 2016-04-11 13:51 UTC
Labels: Not a defect
